### ISSUE TITLE
Recommended strategy for not publishing messages if there are no subscribers

### ISSUE THREAD

**Issue by garrardkitchen** [nats-io/nats.net.v1#100]
Hi,

What strategy do you recommend I implement if I only want to publish messages when there is at least one subscriber?

Warmest regards,

Garrard.

**Comment by ColinSullivan1** [comment]
@garrardkitchen Could you define your use case further?

If the message is small, or infrequent, I would suggest just sending the message anyhow, and letting the server drop it.  It keeps your application very simple, and unless you are sending a very large amount of data, the performance impact will be negligible.

If your case may be determining whether or not to initiate a stream of messages or an extremely large message, you can use request/reply.  The publishing application issues a Request on a discovery subject with a timeout, and subscribing applications respond to this request by publishing a response message on the reply subject from the incoming message (See the Replier example [here](https://github.com/nats-io/csnats/blob/master/examples/Replier/Replier.cs#L84)).  If the request times out in the publishing application, then you know there are no subscribers.

**Comment by garrardkitchen** [comment]
Thank you Colin, this makes perfect sense to me.
