### ISSUE TITLE
very very serious performance problem

### ISSUE THREAD

**Issue by s921102002** [nats-io/nats.net.v1#113]
Hi All,

This is a very simple program. but you can see that the subscriber callback function is very very slow and it suspend - run - suspend - run, you can see it on subscribe console.

I tested on Windows 8 64bit and gnatsd 0.9.4 and csnats 0.6.0

I've tested golang client, it seems better than cs client.

I've tested if subscribe maybe 1-2 subjects, it's ok, but if subscribe count more than 20 or 30. the performance is very very terrible.

Can anyone tell what's wrong with this? or how can I fix it?

I think subject count should't significant impact on performance and I only use 30-50. I think 30-50 is very very easy to NATS. 

It's not about data size because I use just 10 bytes. and it's same as 500 bytes
I look at taskmgr, the cpu usage is very low, but it's very slow :(

Publish  

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NATS.Client;
namespace Publish
{
    class Program
    {
        static void Main(string[] args)
        {
            Options opts = ConnectionFactory.GetDefaultOptions();
            opts.Url = "nats://127.0.0.1:4222";
            string data = "01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789";
            using (IConnection c = new ConnectionFactory().CreateConnection(opts))
            {
                for(int i=0;i<100000; ++i)
                {
                    c.Publish("ABCDEFGHIJK_" + (i % 200).ToString(), Encoding.Default.GetBytes(data + i.ToString()));
                }
                c.Flush();
            }
            Console.WriteLine("Finish");
            Console.Read();
        }
    }
}

```

Subscriber  

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NATS.Client;
namespace Subscribe
{
    class Program
    {
        static void Main(string[] args)
        {
            Options opts = ConnectionFactory.GetDefaultOptions();
            opts.Url = "nats://127.0.0.1:4222";

            int count = 0;
            object obj = new object();

            IConnection c = new ConnectionFactory().CreateConnection(opts);
            EventHandler<MsgHandlerEventArgs> msgHandler = (sender, args2) =>
            {
                lock(obj)
                {
                    count++;
                    Console.WriteLine(count);
                    if (count == 100000)
                    {
                        Console.WriteLine("Finish");
                    }
                }
            };


            for (int i = 0; i < 30; ++i)
            {
                string subject = "ABCDEFGHIJK_" + (i).ToString();
                c.SubscribeAsync(subject, msgHandler);
            }
            c.Flush();
            Console.Read();
        }
    }
}
```

**Comment by ColinSullivan1** [comment]
Thank you for raising the issue - I will take a look.

**Comment by ColinSullivan1** [comment]
@s921102002 , 

You are likely running into contention with thread scheduling.  Internally, each subscription uses a task to deliver messages (firing the message handler event) - increasing the thread pool will help performance here.

What happens when you add `ThreadPool.SetMinThreads(128, 128);` at the beginning of your subscriber application?  You can tune this higher or lower to meet the memory/performance requirements of your application.  It really increased performance in my tests.

Also, I notice that there is an inconsistency between your publisher and subscriber - the example provided publishes to 200 subjects, but the subscriber uses 30 subjects - you should publish and subscribe to the same subjects for the test.

**Comment by s921102002** [comment]
Hi @ColinSullivan1 
I've add 

```
int workerThreadsMin, completionPortThreadsMin;
ThreadPool.GetMinThreads(out workerThreadsMin, out completionPortThreadsMin);
int workerThreadsMax, completionPortThreadsMax;
ThreadPool.GetMaxThreads(out workerThreadsMax, out completionPortThreadsMax);
ThreadPool.SetMinThreads(workerThreadsMax, completionPortThreadsMax);
```

but it's no use, consider if subjects 5000 or 10000, you can see the taskmgr that  thread count reach 1035, I think a process use 1035 threads is incorrect.

it cause run-suspend-run-suspend in print count ( do you know what I means?)

here's a link about task start slowly

 http://stackoverflow.com/questions/22036365/newly-created-threads-using-task-factory-startnew-starts-very-slowly

one subscription one task I think maybe it's not good design.

maybe use a thread pool and fit cpu counts to do callback is better?

 I test golang client it works very very well even 5000 subscription, when send complete, the receive complete immediately too.

Thanks.

**Comment by ColinSullivan1** [comment]
@s921102002 , 10000 subscriptions for an application is a very large number indeed.  About tasks compared to go routines - this is an area where go is exceptional - go routines are very efficient compared to .NET tasks.

There are a few of approaches you can take to scale to that many subscribers.  You can subscribe to a wildcard and then distribute messages internally based on subject, or an identifier in the message.  This will utilize network bandwidth _much_ better, since a message is sent to each subscription.  

Alternatively you can scale using synchronous subscriptions distributed across threads, multiplexing a set of synchronous subscribers in each thread.

Can you share your use case where you need 10000 subscriptions in an application?

Thanks,
Colin

**Comment by s921102002** [comment]
Hi, @ColinSullivan1  
The use case very difficult to say here.  
And subscribe to 5000 is possible, you can image if you be a DataHub, client->DataHub->DataProvider1-10

DataHub hold all data from DataProvider, and user will subscribe any subject, and the problem is here.
DataHub asyncsub 5000 subject, but it will be very slow because task issue.

I think client can't using goroutine style by task here.

1 How do I poll SyncSubscription?
2.using wildcard is not a good choice.

I've done a callback thread pool version, and I test it, I just open one thread to execute callback, and the performance is very very good. and it can improve better, but I dont know is there any problems in my version.

I  test C client too, there's same problem in C client, but it provide to use libuv and libevent, I think that's right way to solve this issue.

Thanks for your help.

**Comment by kozlovic** [comment]
In regards to the C client, you said that you have experienced the same problem. Have you tried with the latest release? https://github.com/nats-io/cnats/releases/tag/v1.4.4

As you can see, I have introduced the option `natsOptions_UseGlobalMessageDelivery()` (or set the environment variable `NATS_DEFAULT_TO_LIB_MSG_DELIVERY` to any value) to use a global thread pool. When this option is set, all asynchronous subscribers will use a shared thread pool responsible for message delivery.

**Comment by s921102002** [comment]
Hi, @kozlovic  
Sorry I don't notice natsOptions_UseGlobalMessageDelivery() before, but I tested it, and it works very good.  
Thanks for your reminder and can set it as default?(but it should be test how many time diff in using thread pool and one subscription per thread).

Thank you very much.

**Comment by ColinSullivan1** [comment]
@s921102002 ,

I can look at adding some functionality into the .NET client that mirrors UserGlobalDeliveryOption in C.  

To poll sync subscribers, setup your subscribers in a list, then continually traverse the list, retrieving messages with a timeout of 0.  This services subscribers fairly and will reduce the number of tasks created in your application.

Here's example code demonstrating what I'm describing:

```
        static void Main(string[] args)
        {
            using (var c = new ConnectionFactory().CreateConnection())
            {

                Task.Run(() =>
                {
                    // let the subscribers start
                    Thread.Sleep(1000);
                    for (int i = 0; i < 20000; i++)
                    {
                        c.Publish("foo-" + (i % 1000), Encoding.UTF8.GetBytes("hello"));
                    }
                });


                // 1000 subscribers in one task
                var t = Task.Run(() =>
                {
                    var subs = new List<ISyncSubscription>();
                    for (int i = 0; i < 1000; i++)
                    {
                        subs.Add(c.SubscribeSync("foo-" + i));
                    }

                    // listen to all subscribers in this thread.
                    int count = 0;
                    while (true)
                    {
                        foreach (var s in subs)
                        {
                            try
                            {
                                var msg = s.NextMessage(0);

                                // PROCESS MESSAGE HERE

                                if (++count % 1000 == 0)
                                {
                                    Console.WriteLine("Recieved {0} msgs.", count);
                                }
                            }
                            catch (NATSTimeoutException)
                            {
                                // ignore
                            }
                        }
                    }
                });

                t.Wait();
            }
        }
```

You can then add subscribers in additional threads/tasks to scale as necessary.

**Comment by s921102002** [comment]
Hi, @ColinSullivan1  
Your code like I think, but there's a big problem in channel.cs, 
When timeout, channel throw NATSTimeoutException. throw exception is very very expensive.
you can test in subscribe 
Here's example code 

```
  private TimeSpan receiveSyncSubscriber(IConnection c)
        {
            using (ISyncSubscription s = c.SubscribeSync(subject))
            {
                Stopwatch sw = new Stopwatch();

                while (received < count)
                {
                    if (received == 0)
                        sw.Start();
                    try
                    {
                        Msg m = s.NextMessage(0);
                    }
                    catch
                    {

                    }
                    received++;
                }

                sw.Stop();

                return sw.Elapsed;
            }
        }
```

So using this way will reduce performance significant and waste cpu usage.

I think NATS says it's high performance, so I think the measure unit is microsecond not millisecond  

So I think client should consider all performance issue, like throw exception or lock.  

@ColinSullivan1  thank you very much, I think this is a very very good project, and I want it more powerful.  

If there's any words or suggestion make you uncomfortable, I apologize and forgive me please :)

**Comment by ColinSullivan1** [comment]
@s921102002 , No worries, no words or suggestions are making me uncomfortable, and I welcome the discussion!  We are happy you are using NATS, and appreciate your suggestions!  

I do agree that throwing an exception is expensive, although it keeps the NATS C# client in line with the other clients.  I could add an option that will make `NextMessage(int)` return null instead of throwing an exception, or provide another mechanism similar to the global delivery thread in C.  I'll have to think about it a bit.  Even with the exception being thrown, will this perform well enough for you right now?

Regarding microsecond vs millisecond, for a timeout it's unusual to require that level of precision, but the API can always be expanded...

**Comment by s921102002** [comment]
Hi, @ColinSullivan1  
I mean if this client do benchmark, it should consider microsecond level.  
 I think a high performance system should be consider microsecond level, so I say throw exception is expensive.    

Now, I use my version (I make a callback thread pool version)  and using async subscribe, because I use it on a real-time system, and the system require in microsecond level, so I don't use sync subscribe and poll it, because it's too slow for me

I am looking forward to see global delivery thread in c# client!! 

Thank you very much!!

**Comment by ColinSullivan1** [comment]
@s921102002,  #124 should address your performance issue here.  Please let me know how it works out for you.  Thanks!
