### ISSUE TITLE
Slow consumer false positive

### ISSUE THREAD

**Issue by Greatsamps** [nats-io/nats.net.v1#118]
i have been tracking some issues in this section of the code for past 24 hours. We have around 1,000 clients connected to NATS, and this issue will pop up on 1 about every 3-4 hours.

The symptoms is that the client receives a slow consumer exception. This initially caused some confusion, because the only code on the subscriber callback is a function where the message is added to a Queue<Msg> for processing by a different thread.

i have downloaded the source, and have been putting some additional debug info in, and have found 2 situations where it has been triggered incorrectly.

Below is my test code:

`// Check for a Slow Consumer
            if (pMsgs > pMsgsLimit || pBytes > pBytesLimit)
            {
                Console.WriteLine($"pMsgs: {pMsgs} pMsgsLimit: {pMsgsLimit}");
                Console.WriteLine($"pBytes: {pBytes} pBytesLimit: {pBytesLimit}");
                Console.ReadKey();
                // slow consumer
                handleSlowConsumer(msg);
                return false;
            }`

on 1 occasion this block was entered with the following items logged:

pMsgs:3
pMsgsLimit:65536
pBytes:4294967170
pBytesLimit:67108864

now this is clear why its there, but this is an error in its self. there is no way that it received 3 messages totalling 429mb. to verify this i looked at memory the process was using, and it was only using 55mb. so need to understand where this crazy value of pBytes has come from.

on another occasion i got the following logged:

pMsgs:2
pMsgsLimit:65536
pBytes:-126
pBytesLimit:67108864

so the first issue is i can't see how it made it past the if statement with those figures. secondly the pBytes figure is negative. i have seen a few instances where this is triggered when pBytes is negative.

lastly, my understanding is that the client is supposed to disconnect and reconnect if this happens. i have checked the code and can see no logic to do this, and from the results in my app, its not working.

right now my only guess is that this is a threading issue, but am pretty much at a loss here.

Edit:

Just had another one with following logged:

pMsgs:4294967295
pMsgsLimit:65536
pBytes:0
pBytesLimit:67108864

again, stats are just crazy, no way that it got that many messages, and even if it did, it would have stopped at 65537 not that far out...

any ideas?

**Comment by ColinSullivan1** [comment]
This is certainly odd.  I'll take a look into this.

**Comment by ColinSullivan1** [comment]
@Greatsamps, I was not able to reproduce this, but believe you are on to something regarding threading.  I have a branch setup with a potential threading fix - would you mind trying the branch at https://github.com/nats-io/csnats/tree/sub-tally-locking?

**Comment by ColinSullivan1** [comment]
@Greatsamps, master branch has this change now.

**Comment by Greatsamps** [comment]
@ColinSullivan1 Many thanks.. i won't be able to update this until the weekend, but i will do on Saturday and should have an answer pretty quickly if there is an issue still.

**Comment by ColinSullivan1** [comment]
@Greatsamps , Happy to help!  Thank you for reporting the issue, and helping to test.  Much appreciated!  I look forward to hearing about the results.

**Comment by Greatsamps** [comment]
@ColinSullivan1 So i updated the library with the new version and added my debugging code. Pleased to report it has been running over 48 hours on over 1,500 clients without a single issue. Not only are we not getting crazy values detected, that section of code is not being hit now which is more important as it should never have been hit in our setup in first place.

id say this is now fixed, so can you update nuget? Thanks for your prompt action

**Comment by ColinSullivan1** [comment]
@Greatsamps, I'm glad to hear it is fixed!  I'll schedule another release and update NuGet.
