### ISSUE TITLE
Update .NET core dependencies

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.net.v1#148]
.NET core moves fast.  Update dependencies for the client, tests, and samples to reference the latest stable libraries/frameworks.

Update:  Best to wait and do this with the .NET core 2.0 release barring any security issues or major bugs.

**Comment by basingh89** [comment]
I would like to use NATS on Universal Windows Platform. However, it does mean targetting .NET Standard 1.3 (technically, 1.4). It seems that the only thing requiring .NET Standard 1.6 is `BufferedStream`.

**Comment by ColinSullivan1** [comment]
@basingh89 , Thank you for raising this issue.  Removing `BufferedStream` would significantly reduce performance (one of the key features of NATS).  Would you have an alternative you'd suggest?

This does look straightforward to change as variables use the `Stream` interface.

I'd like to open this up for discussion, and would love to hear from anyone else needing older support of .NET 1.3 standard or lower.  Please chime in!

**Comment by basingh89** [comment]
On the flip side, Microsoft is planning to update [UWP to support .NET Standard 2.0](https://blogs.msdn.microsoft.com/dotnet/2017/08/25/uwp-net-standard-2-0-preview).

**Comment by ColinSullivan1** [comment]
@basingh89 , IMO .NET standard 2.0 will be the way to go.

**Comment by basingh89** [comment]
I agree. But at the same time, I'm not sure how long it will take Microsoft to release the update on the devices I'm working on (e.g. HoloLens).

**Comment by ColinSullivan1** [comment]
I understand, but would hate to move backward at this point.

Supporting code uses the `Stream` interface - you could modify [Connection.getWriteBufferedStream()](https://github.com/nats-io/csharp-nats/blob/v0.8.0/NATS.Client/Conn.cs#L519) to return the appropriate stream directly rather than wrapping in a `BufferedStream`.  You'd likely have a performance hit and would lose extremely large message support, but for most uses cases should be sufficient.

**Comment by nataly87s** [comment]
I can upgrade the project to .NET standard 2.0

I would also love to refactor the code a little, for example use async/await instead of Threads, it should improve performance

**Comment by ColinSullivan1** [comment]
Upping the priority on this, will dedicate time to move to .NET standard 2.0, and visual studio 2017 in the next few weeks.

**Comment by ColinSullivan1** [comment]
@basingh89, I wanted to follow up, is this still an issue?

**Comment by basingh89** [comment]
I don't have the need anymore. @ColinSullivan1 thanks for checking.

**Comment by ColinSullivan1** [comment]
@basingh89 , thanks.  If it ever does become an issue again, please feel free to re-open.
