### ISSUE TITLE
Rx support

### ISSUE THREAD

**Issue by jaklithn** [nats-io/nats.net.v1#149]
Daniel Wertheim has implemented a very nice Rx support in his .Net client. https://github.com/danielwertheim/mynatsclient
I really like that approach as it is fast, elegant and modern. On the other hand I prefer to use officially supported libraries as they tend over time to be more stable and supported.
Can you please consider to include the Rx support in the core of the official client lib?

**Comment by ColinSullivan1** [comment]
@jaklithn , Thank you for looking at NATS, and raising this issue. Absolutely, and I certainly agree - Rx is a nice programming model for the reasons you mentioned.  Providing Rx support is on our list; and I hope to get to it fairly soon.  

In the meantime, we also do accept user contributions -  a performant, well written, separate Rx assembly over the official NATS assembly is something we would certainly consider adopting.

**Comment by nataly87s** [comment]
I want to work on this issue

**Comment by ColinSullivan1** [comment]
@nataly87s , Absolutely, would love the help here!  

I'd suggest as next steps:

1)  You propose an API, which we can review.  A simple layer on top of this NATS assembly (versus built-into NATS) would be ideal.  It'd be be easiest if you'd provide a skeleton API with documentation in a repository you own, where we can collaborate.

2) After the API is defined, once code is complete and unit tests are passing, I'll setup a NATS repository, setup CI, get the NuGet package put together, etc.  You can create a PR with all of your code so github properly reflects your contribution.

3) We'll get some members of NATS community to review it and test it.

4) We create an alpha release, and move forward with your contribution.

Throughout this process I'll be available to answer questions you may have, review code, etc.

We're pretty flexible and want to make things easy, so if you prefer to work another way please let me know.

BTW - If you would like to see what a third party NATS Rx API looks like, check out https://github.com/danielwertheim/mynatsclient (as mentioned above).

Sound good?  Looking forward to your contribution - Thanks!

**Comment by nataly87s** [comment]
I think the easiest way to do it would be to just add a project to this repository with extention methods for `IConnection`. 
Of course I'll add documentation and tests as well

**Comment by ColinSullivan1** [comment]
If it facilitates development I'm OK starting that way, but we'll want to differentiate releases for NATS and NATS-RX, which will require different repositories.

**Comment by nataly87s** [comment]
It was easier for me to just rewrite everything, so I created a new client
https://github.com/nataly87s/SimpleNatsClient
I still need to add reconnect, and add some more integration tests, but what do you think so far?

**Comment by sixlettervariables** [comment]
@ColinSullivan1 @nataly87s, we're definitely interested in this as we move into the NATS Streaming realm. I'm going to take a look too!

**Comment by ColinSullivan1** [comment]
@nataly87s, Thanks!  I'll dig in...

Upon a quick first pass, would it help if we exposed some of the NATS.Client connection internals for you to use?  You'd be able to leverage reconnect, asynchronous info updates, ping/pong (heartbeats), the flush timer, etc, and you'd be insulated from possible future protocol updates.  Also, much of the lower level NATS connection code has been highly optimized for performance (many thanks to @sixlettervariables there).

**Comment by nataly87s** [comment]
It was kinda hard to use the NATS.Client connection because the structure was not really suited for RX.
But I implemented everything with RX, so all of the async stuff is pretty easy, and no need for locks and stuff like that.
I will also add some benchmarks to check the performance, but so far the tests look good.

**Comment by nataly87s** [comment]
I think I finished the client.
What do you think about it? Is anything missing?

**Comment by sixlettervariables** [comment]
@nataly87s I have some questions about it, are you on the NATS slack?

**Comment by nataly87s** [comment]
@sixlettervariables No, but I can join if you send me an invite

**Comment by ColinSullivan1** [comment]
@nataly87s , I'll take a look - thanks!  I've sent you a slack invite.

**Comment by ColinSullivan1** [comment]
@nataly87s , very clean code, well done.  Are you sure there isn't way to extend the core NATS client for use under your RX assembly here?  I know we'll have some protocol updates coming, and there are a number of useful client features that are built into the core NATS connection and subscriptions.  Would be happy to extend what you'd need...

**Comment by danielwertheim** [comment]
@ColinSullivan1 as far as I can tell, it should be covered by #303 which has been solved by #304
