### ISSUE TITLE
Timeout not working as expected

### ISSUE THREAD

**Issue by chrismcv** [nats-io/nats.net.v1#150]
I'm doing some testing on failure scenarios, and am testing what happens if the NATS server is stopped while my process is running.

I'm finding the timeout periods seem to be getting ignored, assuming I've configured it correctly.

Here is my reproduce code.
```
using NATS.Client;
using System;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;

namespace TestNats
{
    class Program
    {
        static void Main(string[] args)
        {
            Task.Run(() => Run());
            Console.ReadLine();
            
        }

        static async Task Run()
        {
            Console.WriteLine("Hello World!");
            var cf = new ConnectionFactory();
            var opts = ConnectionFactory.GetDefaultOptions();
            opts.Timeout = 1000;
            opts.AllowReconnect = false;
            var conn = cf.CreateConnection(opts);
            conn.SubscribeAsync("test", (p, a) => conn.Publish(a.Message.Reply, new byte[0]));
            await conn.RequestAsync("test", new byte[0], 1000);

            Console.WriteLine("Now stop nats server, you have 5 seconds");
            Thread.Sleep(5000);
            
            var s = new Stopwatch();
            s.Start();
            try
            {
                await conn.RequestAsync("test", new byte[0], 1000);
                s.Stop();
                Console.WriteLine(s.ElapsedMilliseconds / 1000 + "s");
            }
            catch (Exception ex)
            {
                s.Stop();
                Console.WriteLine(s.ElapsedMilliseconds / 1000 + "s");
                Console.WriteLine(ex.Message);
            }
        }
    }
}
```

Output:
```
Hello World!
Now stop nats server, you have 5 seconds
60s
Timeout occurred.
```

**Comment by ColinSullivan1** [comment]
@chrismcv , thanks for raising this issue - I'll take a look.  What version of of the NATS C# streaming client are you using?

**Comment by chrismcv** [comment]
using `Nats.Client@0.7.0` on coreclr in a NetStandard1.6 project

**Comment by ColinSullivan1** [comment]
@chrismcv , Thanks - what version of STAN.Client would you be using?  A build from master branch?

**Comment by chrismcv** [comment]
I'm not using STAN.client

**Comment by ColinSullivan1** [comment]
@chrismcv Ahh, yeah, I see - sorry, my mistake.

**Comment by chrismcv** [comment]
no problem

**Comment by ColinSullivan1** [comment]
@chrismcv , I'll let you know what I find...  Thanks again.  (BTW cleared out the STAN comments).

**Comment by ColinSullivan1** [comment]
@chrismcv , How are you stopping the NATS server?  

If I kill the NATS server while testing the API, I immediately get a `NATSConnectionClosed` exception thrown when making the request.  I've also verified correct timeout behavior with a valid connection but without a subscriber.

I suspect your client is not detecting the server is down, and you are hitting the default flush timeout of 60s.

**Comment by chrismcv** [comment]
I had a docker container called nats and was using `docker stop nats`,
which I suspect might be comparable to a network failure?

On Tue, 28 Mar 2017, 20:14 Colin Sullivan, <notifications@github.com> wrote:

@chrismcv <https://github.com/chrismcv> , How are you stopping the NATS
server?

If I kill the NATS server while testing the API, I immediately get a
NATSConnectionClosed exception thrown when making the request. I've also
verified correct timeout behavior without a subscriber.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nats-io/csharp-nats/issues/150#issuecomment-289874815>,
or mute the thread

**Comment by ColinSullivan1** [comment]
@chrismcv , I really appreciate the code you've provided and quick responses.  Yep, I suspect docker stop may simulate a network failure.  May have to work that into the tests.  ;)

I have a PR open, but will run a few more manual tests to verify before merging.  If you'd like, please feel free to test out https://github.com/nats-io/csharp-nats/pull/151.

Thanks,
Colin

**Comment by chrismcv** [comment]
@ColinSullivan1 no problem - and thank for the quick response too.

I've tested your PR and it is giving the following output for my sample code.

```
Hello World!
Now stop nats server, you have 5 seconds
0s
Timeout occurred.
```

This seems good to me. Thanks for your help!

**Comment by ColinSullivan1** [comment]
@chrismcv, Great - thank you for testing!  My local tests pass as well; I'll merge the PR.
