### ISSUE TITLE
Paket Support

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.net.v1#156]
Support the [Paket](https://fsprojects.github.io/Paket/) dependency manager.

**Comment by cjbhaines** [comment]
+1 for looking at Paket, it's awesome!

I could look at doing this for you once the project is moved to the new .NET SDK in #148 , I've recently done it for some internal projects. Paket doesn't work with the DNX build system because there are no build hooks so that is a prerequisite.

**Comment by ColinSullivan1** [comment]
@cjbhaines , that would be great, we'd love a contribution in this area!

I just merged changes to move to VS 2017 Community (MSBuild 15), so that shouldn't pose a problem anymore.

**Comment by danielwertheim** [comment]
Is this one about start using Paket in the solution or?

**Comment by danielwertheim** [comment]
The NATS project it self will continue to use NuGet as a package manager.

Paket in it self supports NuGet packages via e.g. NuGet.org where NATS.Client is distributed, hence no action need to be taken on this issue.
