### ISSUE TITLE
Add ManyRequests feature

### ISSUE THREAD

**Issue by ogoun** [nats-io/nats.net.v1#157]
From official documentation:

> NATS supports two flavors of request reply messaging: point-to-point or **one-to-many**. Point-to-point involves the fastest or first to respond. In a one-to-many exchange, you set a limit on the number of responses the requestor may receive.

Your implementation does not contain a method for one-to-many scenario.

**Implementation example**

```
public IEnumerable<Msg> RequestMany(string subject, byte[] data, int timeout)
{
    if (timeout <= 0)
    {
        throw new ArgumentException("Timeout must be greater that 0.", "timeout");
    }
    string inbox = InboxNameGen.NewInbox();
    SyncSubscription s = subscribeSync(inbox, null);
    publish(subject, inbox, data);
    Flush();
    var set = new List<Msg>();
    Msg m = null;
    do
    {
        try
        {
            m = s.NextMessage(timeout);
            set.Add(m);
        }
        catch(Exception ex)
        {
            break;
        }
    } while (m != null);
    s.unsubscribe(false);
    return set;
}
```

**Comment by ColinSullivan1** [comment]
@ogoun , Thank you for the suggestion, it is very much appreciated.  This topic has come up in the past; we'll consider this.  Note, if something like this is implemented, we will likely start with the [golang](https://github.com/nats-io/go-nats) client, then we'll add to other clients (including C# here).
