### ISSUE TITLE
More protocol friendly request pattern. 

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.net.v1#158]
Add functionality to mirror the go-nats feature, https://github.com/nats-io/go-nats/pull/295.

**Comment by sixlettervariables** [comment]
If I'm reading this correctly, does the following describe that behavior?

- Each client (when initiating the first request) would create a connection local inbox
- The client (read: per connection) would subscribe to that inbox as a wildcard
- Each request from the client would have a reply to referencing that inbox plus a unique ID
- The reply would be dispatched locally based on that unique ID

**Comment by ColinSullivan1** [comment]
@sixlettervariables , were you thinking of contributing here?

**Comment by sixlettervariables** [comment]
As I understand it we, basically, do exactly this in our usage of the client (but for a different purpose than performance). Trying to understand the feature and how it may/may not affect us.

**Comment by ColinSullivan1** [comment]
It really shouldn't affect you (beyond better performance), unless you have some subject based authorization enabled that would interfere with the internal subscription.

**Comment by ColinSullivan1** [comment]
Resolved by #167.
