### ISSUE TITLE
Does/can Connection.Publish block?

### ISSUE THREAD

**Issue by BrannonKing** [nats-io/nats.net.v1#172]
The Publish method returns void. How long will it block?

It has its own local buffer? What happens when the buffer is full? How do I configure the buffer?

It appears to throw an exception if the connection is closed? But what about if we're reconnecting? Do we go into a closed state and then into a reconnecting state? Is "closed" a manual close only or does it go into that state with a connection fault?

**Comment by ColinSullivan1** [comment]
@BrannonKing , Thank you for your interest in NATS!

The publish method uses a buffer owned by the connection, and when all of the buffers are full, it can block, but IMO you are not likely to run into that situation.  Today, there is no way to configure buffer sizes, but we could certainly add a feature if there is a need.  There is an [issue](https://github.com/nats-io/go-nats/issues/197) open for this on our canonical go client.

During reconnect, a memory stream is used to temporarily buffer published messages, and upon successfully reconnecting, the client will send all messages it has buffered up.  This is a convenience to minimize disruption to your application.

The connection is in a closed state when your application closes the connection, or all reconnect attempts have failed.

Can you describe your use case?

Thanks,
Colin

**Comment by BrannonKing** [comment]
I was trying to write a speed test (see the unit tests here: https://github.com/BrannonKing/Kts.ObjectSync). I want to push data through NATS as fast as possible. When doing it in a tight loop, I was hitting the "consumer too slow" message. I had to add in some arbitrary spin-waits. I need some way to know how much room is in the buffer. That way I can stall my system until there is room. Similarly, it might be nice to have an event for changes in the connection's state.

**Comment by ColinSullivan1** [comment]
@BrannonKing ,  Have you tried injecting a request/response in your test to meter your publisher?  

Every N messages (N being a value you select that works best in your use case, e.g. 10,000), you can send a request to your consuming application and block publishing while waiting for a response.  This could be on a different subject, or you could flag a message with special content.  It is one way to meter your publish rate to the throughput capacity of the consuming application.

**Comment by ColinSullivan1** [comment]
Closing this PR due to inactivity; please feel free to re-open if you still have questions.  

One thing to add - in NATS, publishing is completely decoupled from associated subscribers, so there is no built in way to meter a publisher with a subscriber, so you'll want to implement a strategy to meter the publisher. 

Alternatively, NATS streaming will allow you to prevent overrunning publishers and subscribers, although it may be overkill is this is the sole problem you are trying to mitigate.
