### ISSUE TITLE
Subscription EventHandler Async/Await Support

### ISSUE THREAD

**Issue by james-andrewsmith** [nats-io/nats.net.v1#173]
Are there any plans to support async / await within an EventHandler? Is this what #59 is referring to?

eg:

```csharp
IAsyncSubscription s = c.SubscribeAsync("foo");
s.MessageHandler += async (sender, args) =>
{
    await SomeAsyncMethod(args.Message);
};
s.Start();
```

**Comment by ColinSullivan1** [comment]
@james-andrewsmith, 

Thank you for your interest in NATS!

Can you go into more detail?  The following code snippet works for me with the latest version:
```csharp
            var done = new AutoResetEvent(false);
            var c = new ConnectionFactory().CreateConnection();
            IAsyncSubscription s = c.SubscribeAsync("foo");
            s.MessageHandler += async (sender, args) =>
            {
                await Task.Run(() => Console.WriteLine ("Received msg on subject: " + args.Message.Subject));
                done.Set();
            };
            s.Start();
            c.Publish("foo", null);
            done.WaitOne();
```  
Output:
```text
Received msg on subject: foo
```

#59 refers to a different issue which I'll need to clarify; thank you for bringing that up.

**Comment by james-andrewsmith** [comment]
@ColinSullivan1 Thanks for clarifying, I swear visual studio is playing games with me, my snippet wasn't working last I checked and now with fresh eyes it works, regardless I am glad to see that it works!

I also wanted to clarify blocking behaviour / threading of the AsyncSubscription as well, each message is processed by the handler completely before it moves onto the next. 

So in order process messages in parallel I am doing something like the below, holding onto the subscription references in a local collection (obviously this is really rough, going to production will have proper locking etc). 

```csharp
public async Task WatchForRequests(int limit = 1)
{
	for (var i = 0; i < limit; i++)
	{
		var sub = _conn.SubscribeAsync("my-subject", "my-queue-group");
		sub.MessageHandler += async (sender, args) =>
		{
			await MessageHandler(sender, args);
		};
		sub.Start();
		_mySubsriptions.Add(sub);
	}
}
```

**Comment by ColinSullivan1** [comment]
@james-andrewsmith , No worries!  Sometimes code is broken until the exact moment you ask someone else to look at it.  :)  

The message handler for each queue subscriber will process each message sequentially and will block - every subscriber is serviced by a task assigned to it at creation. *However*, messages will be distributed randomly by the server to subscribers in the queue group and you'll lose the source order delivery guarantee.  ...with this approach you'll really distribute your work nicely, but your messages must atomic, each representing a complete unit work.  Does that make sense?

BTW, if you have a large number of subscriptions, you'll want to checkout [NATS.Client.Options.SubscriberDeliveryTaskCount](http://nats-io.github.io/csharp-nats/class_n_a_t_s_1_1_client_1_1_options.html#a030dfa5eac04072735d7529147d5c562).

**Comment by james-andrewsmith** [comment]
@ColinSullivan1 Thank you very much for your guidance - I will definitely ensure I tweak the task count accordingly.
