### ISSUE TITLE
Compatibility issue with case-sensitive operating systems.

### ISSUE THREAD

**Issue by niarbeht** [nats-io/nats.net.v1#176]
Adding the Nuget package for NATS.Client on Linux results in getting a NATS.Client.DLL file.  This file cannot be found when attempting to load assemblies unless it is renamed NATS.Client.dll.

**Comment by ColinSullivan1** [comment]
@niarbeht , thank you for raising this issue; I'll look into it.

**Comment by niarbeht** [comment]
Check nuget/NATS.Client.nuspec, look for the lines:
`<file src="lib\net45\NATS.Client.DLL" target="lib\net45\NATS.Client.DLL" />`
`<file src="lib\net45\NATS.Client.XML" target="lib\net45\NATS.Client.XML" />`
`<file src="lib\netstandard1.6\NATS.Client.DLL" target="lib\netstandard1.6\NATS.Client.DLL" />`
`<file src="lib\netstandard1.6\NATS.Client.XML" target="lib\netstandard1.6\NATS.Client.XML" />`
Consider changing to:
`<file src="lib\net45\NATS.Client.DLL" target="lib\net45\NATS.Client.dll" />`
`<file src="lib\net45\NATS.Client.XML" target="lib\net45\NATS.Client.xml" />`
`<file src="lib\netstandard1.6\NATS.Client.DLL" target="lib\netstandard1.6\NATS.Client.dll" />`
`<file src="lib\netstandard1.6\NATS.Client.XML" target="lib\netstandard1.6\NATS.Client.xml" />`

I would try re-building with this change myself, but currently I'm at work, and I noticed this problem with a non-work project, so I can't do much more right now.

**Comment by niarbeht** [comment]
Further information:

```
$ mono --version
Mono JIT compiler version 5.0.0 (Stable 5.0.0.100/9667aa6 Wed Jul 12 17:00:30 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```

**Comment by ColinSullivan1** [comment]
Thank you @niarbeht , I'll get to this soon, likely tomorrow.

**Comment by ColinSullivan1** [comment]
@niarbeht , I'm setting up an environment to test this.  Would you happen to have a small project that reproduces this error, or maybe a docker file that demonstrates this?

Thanks,
Colin

**Comment by niarbeht** [comment]
I can try to get something together for you tonight or tomorrow. For 
now, Everything Is On Fire at work.  It was all fine yesterday morning, 
and now nothing works, even though I didn't change anything.

It's definitely one of those days right now...

**Comment by ColinSullivan1** [comment]
@niarbeht , Sorry to hear that; good luck putting out fires.  Whenever you get to it is fine here - no rush.  I'll look into to this further later today or tomorrow AM.  I did verify the NuGet package does work on MacOS X.

**Comment by ColinSullivan1** [comment]
@niarbeht , I did verify that mono doesn't like the case sensitivity.  I'll make a fix.  Is this holding you back from production at the moment?

**Comment by niarbeht** [comment]
@ColinSullivan1 It's a home project, so don't worry about it too much, just be aware that it will probably bite someone someday.  I can work around it personally for now by just leaving a properly-named .dll file in my deployed environment.

Also, sorry for not assisting more, I'm in Houston, and it's a bit wet outside right now.

**Comment by ColinSullivan1** [comment]
OK, thanks, and good luck there in Houston - try and stay dry!  

Agreed - someone may run into this, I appreciate your raising this issue.  Whenever time permits, would you mind giving this NuGet package a shot to verify?  (just remove the .zip postfix).

[NATS.Client.0.8.1.nupkg.zip](https://github.com/nats-io/csharp-nats/files/1258768/NATS.Client.0.8.1.nupkg.zip)
