### ISSUE TITLE
Cluster + Reconnect + Auth - wrong ServerPool list

### ISSUE THREAD

**Issue by sebastien-curutchet** [nats-io/nats.net.v1#197]
Hello,

This scenario failed :

auth_5678.conf
```
port: 5678 # port to listen for client connections

# Authorization for client connections
authorization {
  user:     username
  password: password
  timeout:  1
}

cluster {
  host: '0.0.0.0'  # host/net interface
  port: 5670       # port for inbound route connections

  # Authorization for route connections
  authorization {
    user: clusterlogin
    password: clusterpassword
    timeout: 1
  }
  routes = [
    nats-route://clusterlogin:clusterpassword@localhost:5671
  ]
}
```

auth_5679.conf
```
port: 5679 # port to listen for client connections

# Authorization for client connections
authorization {
  user:     username
  password: password
  timeout:  1
}

cluster {
  host: '0.0.0.0'  # host/net interface
  port: 5671       # port for inbound route connections

  # Authorization for route connections
  authorization {
    user: clusterlogin
    password: clusterpassword
    timeout: 1
  }
  routes = [
    nats-route://clusterlogin:clusterpassword@localhost:5670
  ]
}
```

Unit Test:
```csharp
        [Fact]
        public void TestAuthWithClusterFailure()
        {
            NATSServer s1 = null, s2 = null;
            IConnection c = null;
            try
            {
                s1 = util.CreateServerWithConfig("auth_5678.conf");
                s2 = util.CreateServerWithConfig("auth_5679.conf");
                var opts = ConnectionFactory.GetDefaultOptions();
                opts.Servers = new[] {"nats://username:password@localhost:5678","nats://username:password@localhost:5679"};
                opts.AllowReconnect = true;
                opts.MaxReconnect = 10;
                opts.Timeout = 2;
                opts.ReconnectWait = 2;
                c = new ConnectionFactory().CreateConnection(opts);
                Assert.True(c.State == ConnState.CONNECTED);
                s1.Shutdown();
                Thread.Sleep(200);
                s1 = util.CreateServerWithConfig("auth_5678.conf");
                Thread.Sleep(200);
                Assert.Equal(2, c.Servers.Length);
            }
            finally
            {
                c?.Dispose();
                s1?.Shutdown();
                s2?.Shutdown();
            }
        }
```

The connection server list  is : 
nats://username:password@localhost:5678
nats://username:password@localhost:5679
nats://localhost:5678 => generated by the cluster autodiscovery mechanism but without login/pwd ??

3 options : 
* fix this issue (seems to be a server one)
* add an options to not take into account the server discovery messages
* add new option properties to manage server auth (if all servers have the same authentication setup)

I can push in few days an improvement for the second option :)

What are you recommending ?

PS: In my environment, I have a 3 servers cluster and the ServerPool list contains 9 items : initial 3 items (nats connection strings with login and password), 3 items with IPv4:port without auth information, and 3 items with IPv6:port without auth information. The client can stay in CONNECTING state once at least one gnatsd process restarted.

Regards,

**Comment by ColinSullivan1** [comment]
Hello @sebastien-curutchet , thanks for raising this issue. 

If you use the credentials parameters in the options rather than using the username/password in the url, the client will always connect using those credentials including when using urls provided by the server.  We should make this behavior more apparent.

```c#
                opts.User = "username";
                opts.Password = "password";
```

Regarding the extra items in your returned url list, if you specify a specific listen interface, you should only receive one url per server.  The NATS server is returning every interface (including IPv6) as it defaults to 0.0.0.0.

For example:
```
listen: 192.168.0.2:5678
```
(change this for your environment)

I hope this helps; please let me know.

**Comment by sebastien-curutchet** [comment]
Oh sorry, I don't know why, but I haven't seen User and Password properties in Options class.  The UT works fine with these two properties. Thank you.
About making this behavior more apparent, I don't think that is necessary : there are existing UTs with this behavior. Or maybe a quick sample in the main README.md.
