### ISSUE TITLE
Allow the client to infinitely attempt to reconnect

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.net.v1#201]
Allow setting maximum reconnects to a value (-1) that represents infinite, to continually trying to reconnect.

**Comment by BenDerPan** [comment]
that's not work for me, only works when I set MaxReconnect>0

**Comment by sfrooster** [comment]
@ColinSullivan1 I thought you mentioned this was fixed or would be soon?  Is it?  If so, has it made its way to a nuget?

**Comment by ColinSullivan1** [comment]
Not yet, I'm lining up both .NET clients for releases soon.  It's not added yet, I'll add it before I release.

**Comment by ColinSullivan1** [comment]
Resolved with #217
