### ISSUE TITLE
NATSNoServersException if connecting from .NET Core 2.0

### ISSUE THREAD

**Issue by dannyyy** [nats-io/nats.net.v1#209]
Hi,

I'm facing the issue, that connecting from a .NET Core 2.0 console application, no connection can be established. I got always a "NATSNoServersException" with the reason "Unable to connect to server". If I connect from a .NET 4.6.2 console application with the absolutely same source code all is going well.

Is there any known issue about this? By the way I'm using the NuGet Package 0.8.0 which is might be a bit outdated compared to the version on GitHub. Do you recommend to compile and use the GitHub code over the published Nuget package?

Best regards,
Danny

**Comment by ColinSullivan1** [comment]
Hi Danny,

Thank you for using NATS, and for raising this issues.  There is no known issues in this area...  can you provide verbose server output from a time when this happens?  To do this, run the NATS server with the `-DV` flag, e.g. `gnatsd -DV`

Master branch will be more up to date, but v0.8.0 should be stable.

Thanks,
Colin

**Comment by ColinSullivan1** [comment]
I'm going to go ahead and close this - if you a still encountering this problem, please feel free to re-open this issue.  Thanks!
