### ISSUE TITLE
Needs to set timeout to StreamReader

### ISSUE THREAD

**Issue by ys-zhao** [nats-io/nats.net.v1#222]
When Nats server is stuck, sr.ReadLine() won't return, needs to pass Options.Timeout to readOp()

https://github.com/nats-io/csharp-nats/blob/d1b1ec379a865ebafc742e0707dc57871fbb7ff6/NATS.Client/Conn.cs#L1298

**Comment by ColinSullivan1** [comment]
@ys-zhao , Thank you for raising this issue, I'll take a look.

**Comment by danielwertheim** [comment]
@ys-zhao @ColinSullivan1 How would one re-produce this in a test? I mean, it's rather "simple" to add an `option.ReadTimeout` or similar that could be configured, but I'm wondering when this happens.

**Comment by ColinSullivan1** [comment]
The only deterministic way would be to mock the server, which imo is not worth the time.  I think some simple tests setting it and testing bad values will suffice.
