### ISSUE TITLE
StanConnectRequestTimeoutException leaves client in invalid state

### ISSUE THREAD

**Issue by mabzd** [nats-io/nats.net.v1#225]
After `StanConnectRequestTimeoutException` is thrown client is in invalid state with resources hanging in the void. This prevents application from closing gracefully. 

```
class Program
{
  static void Main(string[] args)
  {
    TestTimeout();
  }

  private static void TestTimeout()
  {
    var options = StanOptions.GetDefaultOptions();
    options.ConnectTimeout = 1;

    try
    {
    new StanConnectionFactory().CreateConnection("test-cluster", "test", options);
    }
    catch (StanConnectRequestTimeoutException)
    {
    Console.WriteLine("Timeout");
    }
  }
}
```

After executing this code application stays open. My machine runs Windows 10 64-bit with nats-streaming-server 0.10.2.

**Comment by ColinSullivan1** [comment]
@mabzd , thank you for raising this issue.  I've moved it to the csharp-nats-streaming repository as https://github.com/nats-io/csharp-nats-streaming/issues/73
