### ISSUE TITLE
[Linux] Disconnected Event Handler does not work

### ISSUE THREAD

**Issue by markusr** [nats-io/nats.net.v1#226]
I am testing the ```DisconnectedEventHandler```. 

I use the following test procedure:
1. Start ```gnatsd``` 
2. Start dotnet program and let it run for some seconds and check that messages are published
3. Stop ```gnatsd``` (CTRL + C)

I expect that after some time the ```DisconnectedEventHandler``` is thrown, which is not the case.

```
using System;
using System.Diagnostics;
using System.Text;
using System.Threading;
using System.Collections.Generic;
using NATS.Client;

namespace SampleNamespace
{
    class Program
    {
        static void Main(string[] args1)
        {
            Options opts = ConnectionFactory.GetDefaultOptions();
            opts.AllowReconnect = true;
            opts.Url = "nats://localhost:4222";

            opts.AsyncErrorEventHandler += (sender, args) =>
            {
                Console.WriteLine("Error: ");
                Console.WriteLine("   Server: " + args.Conn.ConnectedUrl);
                Console.WriteLine("   Message: " + args.Error);
                Console.WriteLine("   Subject: " + args.Subscription.Subject);
            };

            opts.ServerDiscoveredEventHandler += (sender, args) =>
            {
                Console.WriteLine("A new server has joined the cluster:");
                Console.WriteLine("    " + String.Join(", ", args.Conn.DiscoveredServers));
            };

            opts.ClosedEventHandler += (sender, args) =>
            {
                Console.WriteLine("Connection Closed: ");
                Console.WriteLine("   Server: " + args.Conn.ConnectedUrl);
            };

            opts.DisconnectedEventHandler += (sender, args) =>
            {
                Console.WriteLine("Connection Disconnected: ");
                Console.WriteLine("   Server: " + args.Conn.ConnectedUrl);
            };

            IConnection c = new ConnectionFactory().CreateConnection(opts);

            while (true)
            {
                c.Publish("foo", new byte[] { 1, 2, 3 });
                // c.Flush();
                Thread.Sleep(100);
            }

        }
    }
}
```

I am using dotnet core under ubuntu 16.04

```
$ ./gnatsd -v
nats-server version 1.2.0
```

```
$ dotnet --info
.NET Core SDK (gemäß "global.json"):
 Version:   2.1.302
 Commit:    9048955601

Laufzeitumgebung:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-preview1-26216-03 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by ColinSullivan1** [comment]
@markusr , thank you for using NATS and raising this issue.

What could be going on is that the client library is still attempting to reconnect.  By default it will attempt to reconnect 60 times, with up to a two second delay between reconnect attempts.  You can either wait a few minutes to iterate through the reconnect attempts, or to quickly test this functionality you can disable reconnect functionality.  Some example code is [here](https://github.com/nats-io/csharp-nats/blob/v0.8.1/NATSUnitTests/UnitTestConn.cs#L108).  I advise allowing the client to attempt to reconnect unless your use case specifically requires it not.

Does this make sense?

**Comment by markusr** [comment]
@ColinSullivan1 
> Does this make sense?

Not Really. I want to know if the client is connected to the server or not. So if the client can expect to receive SUB messages.

I tried several points:

## Reduce reconnect time (and tries)
I added:
```
opts.AllowReconnect = true;
opts.MaxReconnect = 2;
opts.ReconnectWait = 10;
```
So here the DisconnectedEventHandler should be thrown after 20 ms (or 30 ms). This does not happen.

## Disable reconnect time (and tries)
```
opts.AllowReconnect = false;
```
Also no DisconnectedEventHandler is thrown.



## Check status of connection
```
            while (true)
            {
                Console.WriteLine("c.State is {0}", c.State);
                c.Publish("foo", new byte[] { 1, 2, 3 });
                // c.Flush();
                Thread.Sleep(100);
            }
```

This constantly prints out, even after I stop gnatsd:
```
c.State is CONNECTED
c.State is CONNECTED
```

It seems to me there is a bug in detection of the connection status.

**Comment by ColinSullivan1** [comment]
@markusr , I'll take a look...

**Comment by ColinSullivan1** [comment]
@markusr , I ran your initial example code (.NET core on windows, 2.0.7) and it worked for me...

ctrl-C the server...
```
Connection Disconnected:
   Server:
```
Restarted the server, the client reconnected, then killed the server again...
```
Connection Disconnected:
   Server:
```

The `args.Conn.ConnectedUrl` value will be `null` after being disconnected, so that is expected behavior.

I added a reconnect handler to verify:
```csharp
            opts.ReconnectedEventHandler += (sender, args) =>
            {
                Console.WriteLine("Connection Reconnected: ");
                Console.WriteLine("   Server: " + args.Conn.ConnectedUrl);
            };
```

Here is the output after bouncing the server:
```text
Connection Disconnected:
   Server:
Connection Reconnected:
   Server: nats://localhost:4222
```
Before we dive into .NET versions, can you share the output of the NATS server using the debug and trace flags (`gnatsd -DV`) so we can see what is going on in the server with respect to client connections?

Thanks,
Colin

**Comment by markusr** [comment]
```
$ ./gnatsd -DV
[13471] 2018/08/07 14:36:07.943250 [INF] Starting nats-server version 1.2.0
[13471] 2018/08/07 14:36:07.943361 [DBG] Go build version go1.10.3
[13471] 2018/08/07 14:36:07.943381 [INF] Git commit [not set]
[13471] 2018/08/07 14:36:07.943894 [INF] Listening for client connections on 0.0.0.0:4222
[13471] 2018/08/07 14:36:07.943914 [DBG] Server id is C9ECt6WoqI0GLkFbcsCMmY
[13471] 2018/08/07 14:36:07.943921 [INF] Server is ready
[13471] 2018/08/07 14:36:45.249241 [DBG] 127.0.0.1:42775 - cid:1 - Client connection created
[13471] 2018/08/07 14:36:45.457476 [TRC] 127.0.0.1:42775 - cid:1 - ->> [CONNECT {"auth_token":null,"lang":".NET","name":null,"pass":null,"pedantic":false,"protocol":1,"ssl_required":false,"user":null,"verbose":false,"version":"0.0.1"}]
[13471] 2018/08/07 14:36:45.458103 [TRC] 127.0.0.1:42775 - cid:1 - ->> [PING]
[13471] 2018/08/07 14:36:45.458110 [TRC] 127.0.0.1:42775 - cid:1 - <<- [PONG]
[13471] 2018/08/07 14:36:45.506374 [TRC] 127.0.0.1:42775 - cid:1 - ->> [PUB foo 3]
[13471] 2018/08/07 14:36:45.506637 [TRC] 127.0.0.1:42775 - cid:1 - ->> MSG_PAYLOAD: []
[13471] 2018/08/07 14:36:45.553991 [TRC] 127.0.0.1:42775 - cid:1 - ->> [PING]
[13471] 2018/08/07 14:36:45.554006 [TRC] 127.0.0.1:42775 - cid:1 - <<- [PONG]
[13471] 2018/08/07 14:36:45.659926 [TRC] 127.0.0.1:42775 - cid:1 - ->> [PUB foo 3]
[13471] 2018/08/07 14:36:45.659945 [TRC] 127.0.0.1:42775 - cid:1 - ->> MSG_PAYLOAD: []
[13471] 2018/08/07 14:36:45.659955 [TRC] 127.0.0.1:42775 - cid:1 - ->> [PING]
[13471] 2018/08/07 14:36:45.659960 [TRC] 127.0.0.1:42775 - cid:1 - <<- [PONG]
[13471] 2018/08/07 14:36:45.760633 [TRC] 127.0.0.1:42775 - cid:1 - ->> [PUB foo 3]
[13471] 2018/08/07 14:36:45.760676 [TRC] 127.0.0.1:42775 - cid:1 - ->> MSG_PAYLOAD: []
[13471] 2018/08/07 14:36:45.760718 [TRC] 127.0.0.1:42775 - cid:1 - ->> [PING]
[13471] 2018/08/07 14:36:45.760734 [TRC] 127.0.0.1:42775 - cid:1 - <<- [PONG]
....
(a lot of messages...)
....
[13471] 2018/08/07 14:36:51.802501 [TRC] 127.0.0.1:42775 - cid:1 - ->> [PING]
[13471] 2018/08/07 14:36:51.802524 [TRC] 127.0.0.1:42775 - cid:1 - <<- [PONG]
[13471] 2018/08/07 14:36:51.903112 [TRC] 127.0.0.1:42775 - cid:1 - ->> [PUB foo 3]
[13471] 2018/08/07 14:36:51.903157 [TRC] 127.0.0.1:42775 - cid:1 - ->> MSG_PAYLOAD: []
[13471] 2018/08/07 14:36:51.903200 [TRC] 127.0.0.1:42775 - cid:1 - ->> [PING]
[13471] 2018/08/07 14:36:51.903222 [TRC] 127.0.0.1:42775 - cid:1 - <<- [PONG]
^C[13471] 2018/08/07 14:36:51.965823 [DBG] Trapped "interrupt" signal
[13471] 2018/08/07 14:36:51.965855 [INF] Server Exiting..
```

After restart there is only:
```
$ ./gnatsd -DV
[14343] 2018/08/07 14:40:39.503735 [INF] Starting nats-server version 1.2.0
[14343] 2018/08/07 14:40:39.503781 [DBG] Go build version go1.10.3
[14343] 2018/08/07 14:40:39.503785 [INF] Git commit [not set]
[14343] 2018/08/07 14:40:39.503855 [INF] Listening for client connections on 0.0.0.0:4222
[14343] 2018/08/07 14:40:39.503859 [DBG] Server id is 3mlRtVVSOz40bJ9jb8u1qh
[14343] 2018/08/07 14:40:39.503863 [INF] Server is ready
```

**Comment by markusr** [comment]
@ColinSullivan1 Any updates on this?

**Comment by ColinSullivan1** [comment]
@markusr , My apologies, I missed this.  I wasn't able to reproduce this, but will take another look at your test code.

**Comment by ColinSullivan1** [comment]
I just tried and it worked for me.  I've uploaded a project with source so you can give it a try:  [disconn_test.zip](https://github.com/nats-io/csharp-nats/files/2470376/disconn_test.zip).  This uses NATS.Client 0.8.1.

```E:\src\github.com\nats-io\csharp-nats\disconn_test>dotnet --info
.NET Command Line Tools (2.1.201)

Product Information:
 Version:            2.1.201
 Commit SHA-1 hash:  7932dc6179

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.201\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```
Here's the output...

```text
Connection Disconnected:
   Server: nats://localhost:4222
Connection Reconnected:
   Server: nats://localhost:4222
```

How does this work for you?

**Comment by markusr** [comment]
@ColinSullivan1
The problem is with Linux (or the socket handler part in dotnet core specific to linux):

I compiled with 
```
dotnet publish -r win-x64 -c Release
```
and run it under a (virtual) Windows 10. The code works as expected.

Then I did the same under Ubuntu 18.04. 
```
dotnet publish -r linux-x64 -c Release
```
and it does not work.

I am not sure what to do next.

**Comment by ColinSullivan1** [comment]
@markusr , I'll take a look.  Unfortunately, this sounds like a bug in .NET core.

**Comment by ColinSullivan1** [comment]
@markusr , My assumption right now is that .NET core socket reads aren't breaking out with an exception when the server's TCP connection is broken, and we are dealing with very long OS timeouts here to detect the broken connection.  I started the test, bounced the server, and then left the test running:

```text
colin@ubuntu18:~/test$ date
Mon Oct 15 20:17:19 UTC 2018
colin@ubuntu18:~/test$ dotnet run
Connection Disconnected: 
   Server: nats://localhost:4222
Connection Reconnected: 
   Server: nats://localhost:4222
^C
colin@ubuntu18:~/test$ date
Mon Oct 15 20:23:40 UTC 2018
```

So, the client did reconnect, but after an unacceptable 6+ minute timeout.  I'll look further.

**Comment by ColinSullivan1** [comment]
@markusr , I've been experimenting a bit, and unfortunately, our default settings depend on a quick detection of connection errors by the OS/.NET SDK.

The good news we have client-side options that can help here, namely [Options.PingInterval](http://nats-io.github.io/csharp-nats/class_n_a_t_s_1_1_client_1_1_options.html#a5b593b856ab2b9df03637efdffff135c) and [Options.MaxPingsOut](http://nats-io.github.io/csharp-nats/class_n_a_t_s_1_1_client_1_1_options.html#af72a56c42d59f70432c80f8526edda6e).

Here's some example usage:
```csharp
            Options opts = ConnectionFactory.GetDefaultOptions();
            opts.PingInterval = 1000;
            opts.MaxPingsOut = 3;
```

With the options above, your NATS client should detect the broken server connection in about 3 seconds.  Bear in mind this creates additional network chatter.  If you have a small number of clients, then it really doesn't matter, but if you have thousands or tens of thousands clients, you'll want to avoid using a small `PingInterval` here.  Ping messages are small, but 10,000+ extra ping messages per second is likely something you'll want to avoid.

I was able to recreate your issue with Ubuntu 18.04 with the dotnet 2.1 sdk, and these settings did help mitigate the problem in my environment. There didn't seem to be anything directly related to this in .NET core open issues.  There may be some other OS options we can look at setting, but presently this is the workaround I'd recommend.

Please let me know if this resolves your issue - and I appreciate your patience.  It's frustrating dealing with fundamental runtime SDK behavior differences based on the underlying operating system.

Thanks,
Colin

**Comment by markusr** [comment]
@ColinSullivan1 Thank you a lot for looking into this issue.

 I can reproduce your findings:
- The disconnected event is called after ~6 minutes. I didn't wait that long on my tests before. I always stopped after 1 or 2 minutes.
- Setting ```PingInterval``` and ```MaxPingsOut``` to what you suggested has the desired effect that the event is called after 3 seconds. 

Should we close this issue or do you want to leave it open since there is an underlying problem?

**Comment by ColinSullivan1** [comment]
@markusr , I'm glad the workaround worked for you.  I've created another issue to track this and referenced this one so we can close.  Again, thanks for your patience.
