### ISSUE TITLE
Netcore performance improvements

### ISSUE THREAD

**Issue by plaisted** [nats-io/nats.net.v1#230]
Recent netcore releases (2.1) have had some large improvements in performance (specifically sockets) and added lots of features to help improve performance of a library like this (Span<T> and Memory<T> as low level building blocks but also libraries like System.IO.Pipelines and System.Buffers built on top of these).

Adding an issue to get this on the radar. Refactoring to use these and support netcore2.1 would likely see large increases in performance but also simplify the code base significantly.

**Comment by ColinSullivan1** [comment]
@plaisted , thanks for the issue.  Moving forward, we'll keep this in mind.

**Comment by scottf** [comment]
This should be addressed in the V2 client which will be async and zero allocation / zero copy
