### ISSUE TITLE
On Linux with Dotnet core 2.1, broken connections do not raise errors

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.net.v1#235]
When the server is killed on linux (Ubuntu 18.04), Dotnet 2.1 core 2.1 does not throw an exception when reading from a network stream.   On Windows 10 it does.

The workaround is to use client-side options, namely [Options.PingInterval](http://nats-io.github.io/csharp-nats/class_n_a_t_s_1_1_client_1_1_options.html#a5b593b856ab2b9df03637efdffff135c) and [Options.MaxPingsOut](http://nats-io.github.io/csharp-nats/class_n_a_t_s_1_1_client_1_1_options.html#af72a56c42d59f70432c80f8526edda6e).

Here's some example usage:
```csharp
            Options opts = ConnectionFactory.GetDefaultOptions();
            opts.PingInterval = 1000;
            opts.MaxPingsOut = 3;
```

With the options above, the NATS client should detect the broken server connection in about 3 seconds.  Bear in mind this creates additional network chatter.  If you have a small number of clients, then it really doesn't matter, but if you have thousands or tens of thousands clients, you'll want to avoid using a small `PingInterval` here.  Ping messages are small, but 10,000+ extra ping messages per second is likely something you'll want to avoid.

TODO:
 - [ ] Make small TCP test case and file with .NET core
 - [ ] Investigate other TCP options to mitigate this

See more information in issue https://github.com/nats-io/csharp-nats/issues/226.

**Comment by robertmircea** [comment]
Any news about fixing this? Running on .net core Mac and even with your workaround there is no luck: I keep receiving "Connection is closed". Here is the code: 

```
            var opts = ConnectionFactory.GetDefaultOptions();
            opts.AllowReconnect = true;
            opts.Url = "nats://localhost:4222";
            opts.PingInterval = 1000;
            opts.MaxPingsOut = 3;
            opts.MaxReconnect = -1;

            var cf = new ConnectionFactory();
            
            var stanOpts = StanOptions.GetDefaultOptions();
            stanOpts.NatsConn = cf.CreateConnection(opts);

            var scf =new StanConnectionFactory();
            var cnx = scf.CreateConnection("test-cluster", "smsgw-csharp", stanOpts);
            [... initialize an obj ]
            using (var m = new MemoryStream())
            {
                Serializer.Serialize(m, obj);
                var messageId = await stanConnection.PublishAsync("outgoing.topic", m.ToArray());
            }
```
I connect to NATS Streaming server, I publish a message successfully and then I shutdown the server. After waiting a little while (more than 10 secs), I restart the NATS Streaming server and try to publish again another message, I receive the exception below and I cannot recover from it anymore:

```
NATS.Client.NATSConnectionClosedException: Connection is closed.
   at NATS.Client.Connection.publish(String subject, String reply, Byte[] data)
   at STAN.Client.Connection.publish(String subject, Byte[] data, EventHandler`1 handler)
   at STAN.Client.Connection.PublishAsync(String subject, Byte[] data)
```

**Comment by ColinSullivan1** [comment]
@robertmircea, Thanks for letting us know you're having an issue.  I'll take a look - likely later this week.  I highly suspect this is a .NET core issue, but there may be ways to mitigate or fix this behavior with socket configuration.

**Comment by robertmircea** [comment]
Any update on this issue? It is pretty annoying and makes the library unusable in production on Linux/Mac or Docker. Many thanks!

**Comment by ColinSullivan1** [comment]
Hi @robertmircea , I ran this code on MacOS (Darwin Kernel Version 17.7.0)

```c#
using System;
using STAN.Client;
using NATS.Client;
using System.Threading;

namespace testconn
{
    class Program
    {
        static void Main(string[] args)
        {
            IConnection nc;
            IStanConnection sc;
            AutoResetEvent ev = new AutoResetEvent(false);

            // Setup NATS connection
            Options nopts = ConnectionFactory.GetDefaultOptions();
            nopts.MaxReconnect = -1;
            nopts.MaxPingsOut = 2;   
            nopts.PingInterval = 500;
            nopts.ReconnectedEventHandler = (o, a) => {
                Console.WriteLine("Reconnected.");
                ev.Set();
            };
            nc = new ConnectionFactory().CreateConnection(nopts);
           
            // Setup NATS streaming connection
            StanOptions so = StanOptions.GetDefaultOptions();
            so.NatsConn = nc;

            sc = new StanConnectionFactory().CreateConnection("test-cluster", "smsgw-csharp", so);
            Console.WriteLine("Connected.");
            sc.Publish("foo", null);

            Console.WriteLine("Bounce the server now...");
            ev.WaitOne(20000);

            for (int i = 0; i < 20; i++)
            {
                Console.WriteLine("Publishing.  ConnState {0}.", sc.NATSConnection.State);
                try
                {
                    sc.Publish("foo", null);
                }
                catch (Exception e)
                {
                    System.Console.WriteLine("exception:  {0}", e.Message);
                }
                Thread.Sleep(1000);
            }
        }
    }
}

```

I used a file store for client continuity between restarts.

```nats-streaming-server -SDV -DV -st file -dir /tmp/t1```

Bounced the server when the app was ready, and here was the output.  The first timeout was not unexpected.  Could you give it a shot?

Here was the output:
```text
Connected.
Bounce the server now...
Reconnected.
Publishing.  ConnState CONNECTED.
exception:  Timeout occurred.
Publishing.  ConnState CONNECTED.
Publishing.  ConnState CONNECTED.
Publishing.  ConnState CONNECTED.
Publishing.  ConnState CONNECTED.
Publishing.  ConnState CONNECTED.
```

**Comment by robertmircea** [comment]
Hi Collin,

I have solved the mystery. It seems that STAN.Client package v0.1.4 (latest) which I used has a dependency to NATS.Client 0.7.1. This NATS client pacakge version has this bug that I am experiencing. In my project, I didn't explicitly add NATS.Client as a library in my csproj file and STAN.Client was loading NATS.Client 0.7.1. 

I have explicitly added in csproj:
`<PackageReference Include="NATS.Client" Version="0.8.1" />`
 and STAN.Client used 0.8.1 version afterwards which seems to work in my project as well.

You can try my scenario with your test app as well.

Would it be possible to update the dependency for STAN.Client to latest version of NATS.Client in order to fix this issue for everybody else?

**Comment by watfordgnf** [comment]
This looks resolved in STAN.Client 0.1.5.
