### ISSUE TITLE
Add extension method for Nats services DI

### ISSUE THREAD

**Issue by alancapc** [nats-io/nats.net.v1#246]
Is it possible to have an extension resolving the service bus for us?
e.g.:
```csharp
public void Configure Services(IServiceCollection services) 
{ 
    services.AddNats( defaultOptions => 
    { 
        defaultOptions.Servers = myLIstOfServers; 
    }); 
}
```

**Comment by watfordgnf** [comment]
Would you envision this as a singleton? Transient? Scoped? Examples of each you're free to include in your project:

https://gist.github.com/watfordgnf/7008f9fc1aef3fc2d4a284b63b6eec2a

**Comment by scottf** [comment]
Addressed in https://github.com/nats-io/nats.net/pull/609
