### ISSUE TITLE
RequestAsync on IEncodedConnection

### ISSUE THREAD

**Issue by camp-007** [nats-io/nats.net.v1#247]
I've noticed that IConnection has a RequestAsync() method.  However, IEncodedConnection does not.  Is this intentional?  EncodedConnection inherits from Connection, so this method is implemented on EncodedConnection, however, since ConnectionFactory.CreateEncodedConnection() returns IEncodedConnection, it prevents me from calling RequestAsync() (at least without using a cast that assumes the implementation which seems like a bad practice).

Is there another way that I am missing to use an EncodedConnection but also support the async version of the Request method?

**Comment by sixlettervariables** [comment]
@camp-007 Async code came along later in the library, and EncodedConnection does not seem to get the same amount of usage as a normal connection with custom serialization. Is EncodedConnection your only choice, or could you wrap the connection and use that instead?

**Comment by camp-007** [comment]
Yes, after looking at the source for EncodedConnection and realizing there is no magic there, I found it even preferable to just create some serialization extension methods on IConnection instead.  Thanks for the feedback!

In case anyone else is interested, something like this seems to do the trick nicely:

```csharp
public static class IConnectionExtensions
{
	public static void PublishJson(this IConnection connection, string subject, object message)
	{
		var data = JsonConvert.SerializeObject(message);
		connection.Publish(subject, Encoding.UTF8.GetBytes(data));
	}

	public static IAsyncSubscription SubscribeJsonAsync<T>(this IConnection connection, string subject, string queue, Action<EncodedMessage<T>> messageHandler) where T : class
	{
		return connection.SubscribeAsync(subject, queue, (sender, args) =>
		{
			var data = JsonConvert.DeserializeObject<T>(Encoding.UTF8.GetString(args.Message.Data));
			var msg = new EncodedMessage<T>
			{
				Data = data,
				ArrivalSubscription = args.Message.ArrivalSubcription,
				Reply = args.Message.Reply,
				Subject = args.Message.Subject
			};
			messageHandler(msg);
		});
	}

	public static async Task<T> RequestJsonAsync<T>(this IConnection connection, string subject, object message, TimeSpan timeout)
	{
		var data = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(message));
		var msg = await connection.RequestAsync(subject, data, (int)timeout.TotalMilliseconds);
		return JsonConvert.DeserializeObject<T>(Encoding.UTF8.GetString(msg.Data));
	}
}

public class EncodedMessage<T> where T:class
{
	public T Data { get; set; }
	public string Reply { get; set; }
	public string Subject { get; set; }
	public ISubscription ArrivalSubscription { get; set;}
}
```
