### ISSUE TITLE
Should IConnection be a singleton in an asp.net app?

### ISSUE THREAD

**Issue by camp-007** [nats-io/nats.net.v1#248]
Hello,

I'm new to the C# NATS client and I'm curious about the proper/recommended way of using IConnection.  In an asp.net application that needs to publish messages, should every request use ConnectionFactory.CreateConnection() and use/dispose the connection as a transient object?  Or is it preferable to have a singleton instance of IConnection that all threads/requests share?

I've noticed that the internal implementation of the 'publish' method (and many methods within Connection) have thread synchronization / locking which would seem to imply that contention could happen if a single connection is reused for all requests in the app.  Or is that somehow avoided?

On the flip side, it isn't obvious that there is any connection pooling happening with ConnectionFactory.CreateConnection(), so it may not be desirable to pay some connection overhead on every single request.

Thanks for any guidance you can offer!

**Comment by sixlettervariables** [comment]
I can't speak to all usages of NATS with ASP.Net, but we use a single IConnection. We've not noticed any real performance issues with this, but we're not pushing any more than maybe 50-100 messages a second at peak.
