### ISSUE TITLE
Multi subjects for SubscribeAsync

### ISSUE THREAD

**Issue by ikkyuland** [nats-io/nats.net.v1#249]
I have issue with C# SubscribeAsync when I subscribe to a lot of subject (cannot use wildcard) it use too many thread to handle. (for my understand 1 SubscribeAsync create 1 thread)
```
C#
nc.SubscribeAsync("AAA",handle)
nc.SubscribeAsync("BBB",handle) 
```
In Java Nats I found  io.nats.client.Dispatcher it can add more subscribe to same Dispatcher
```
JAVA
val d = nc.createDispatcher((msg) => handle(msg))
d.subscribe("AAA")
d.subscribe("BBB")
//I think this work fine
```
I want to subscribe around 5000 subject
reason is I want nats to handle routing (remember who subscribe what subjects) 
so how to do this in C# , or we should not use nats in this way

**Comment by ColinSullivan1** [comment]
@ikkyuland , Thank you for using NATS!  

You'll want to look at using the [SubscriberDeliveryTaskCount](http://nats-io.github.io/csharp-nats/class_n_a_t_s_1_1_client_1_1_options.html#a030dfa5eac04072735d7529147d5c562) connection option to reduce the number of tasks handling subscriptions.

There's a bit more about that [here](https://github.com/nats-io/csharp-nats/issues/139#issuecomment-263314039).

Does this resolve your issue?

**Comment by ikkyuland** [comment]
@ColinSullivan1 , it work!  
Thank you very much :)
