### ISSUE TITLE
intermittent Authentication failed because the remote party has closed the transport stream  error

### ISSUE THREAD

**Issue by nithinkd-geon** [nats-io/nats.net.v1#250]
hello 

when trying to connect with NATS server on  TLS mode  there is an intermittent error throwing from
servers randomly
the error saying  that  Authentication failed because the remote party has closed the transport stream

**Comment by nithinkd-geon** [comment]
most probably  due to tls timeout configured in server closing now

**Comment by ColinSullivan1** [comment]
OK, glad you're figuring it out.  If you continue to have issues, feel free to reopen.
