### ISSUE TITLE
Is the behavior changed regarding DissconnectedEventHandler in version 0.9.0?

### ISSUE THREAD

**Issue by per-ove** [nats-io/nats.net.v1#269]
Tested with NATS Server version 1.04.
I have an application where I have registered eventhandlers for Options.ReconnectedEventhandler and Options.DisconnectedEventHandler.

If I stop and restart NATS server process and using the  0.9.0 client version.
None of the handlers is invoked. 
But they are invoked using 0.8.1 client version.

**Comment by ColinSullivan1** [comment]
Nothing should have changed in this area, and unit tests requiring these to be invoked are passing.  Do you have an example application?

**Comment by ColinSullivan1** [comment]
I've looked further into this and our tests are passing that use the reconnect/disconnect handler.
https://ci.appveyor.com/project/NATS-CI47222/csnats/builds/26636963/job/8gvhd34lfinx40cm/tests

Can you share more about your OS/.NET version?

Also, how is it you are shutting down the server?  e.g. If stopping docker images, connections can remain open but stale and by default you'll wait quite awhile before the client will identify the connection is down.

**Comment by ColinSullivan1** [comment]
@per-ove , I'm closing this issue - if you continue to encounter it please reopen this.  Thanks!
