### ISSUE TITLE
cannot build in vs 2015 and .net 4.5

### ISSUE THREAD

**Issue by coffeefedora** [nats-io/nats.net.v1#270]
Opening NATSnet45, and attempting to build.

I get many errors, and it appears it is reference code written for .net Core maybe?  

like so:
Options.cs, line 578:
public bool NoEcho { get => noEcho; set => noEcho = value; }  
error is "not all paths return a value"  and the entire expression is highlighted, it does not appear to like the => syntax.

also in Options.cs, line 130:
UserJWTEventHandler = userJWTEventHandler ?? throw new ArgumentNullException(nameof(userJWTEventHandler));

compiler does not seem to like throws in the null coalesce operator.  

I tried changing project to 4.6.1 (highest installed on box), and no joy either.

**Comment by watfordgnf** [comment]
What version of Visual Studio / C# compiler are you using?

**Comment by coffeefedora** [comment]
Visual studio 2015. professional.  standard C# compiler.

**Comment by watfordgnf** [comment]
I believe Visual Studio 2015 stops at C# 6.0 language features in the IDE support. Visual Studio 2017 picks up with C# 7.X support (which includes expression bodied properties and throw expressions).

**Comment by coffeefedora** [comment]
ah.  ok.  thanks.
