### ISSUE TITLE
Some published messages are lost while reconnecting

### ISSUE THREAD

**Issue by anjmao** [nats-io/nats.net.v1#271]
If connection to server is lost some messages are not flushed from internal pending messages buffer so they are lost. I created repro with latest nats.net source code here https://github.com/anjmao/nats-test-net-core/blob/master/Program.cs#L26

Steps to reproduce

1. `git clone git@github.com:anjmao/nats-test-net-core.git`
2. `docker-compose up -d`
3. `dotnet restore`
4. `dotnet run`
5. After some time stop running nats server `docker stop <id>`
6. Start it again `docker start <id>`

```
Pub 0
Recv 0
Pub 1
Recv 1
Pub 2
Recv 2
Pub 3
Recv 3
Pub 4
Recv 4
Pub 5
Recv 5
Pub 6
Recv 6
Pub 7
Pub 8
Pub 9
Pub 10
processReconnect
Pub 11
Pub 12
Pub 13
Pub 14
Pub 15
Recv 11
Recv 12
Recv 13
Recv 14
Recv 15
Pub 16
Recv 16
Pub 17
Recv 17
Pub 18
Recv 18
Pub 19
Recv 19
Pub 20
Recv 20
Pub 21
Recv 21
Pub 22
Recv 22
```

In this case messages 7, 8, 9, 10 are lost. This works fine in go nats client.

Few things which may cause issues:

1) .NET client logic for pending buffer is a bit different from go client. For example here https://github.com/nats-io/nats.net/blob/master/NATS.Client/Conn.cs#L1498 clearPendingFlushCalls is called before creating pending buffer. In go client pending buffer is created before calling clearPendingFlushCalls https://github.com/nats-io/nats.go/blob/master/nats.go#L1925.

2) Underlying TCP connection is closed before reconnect and write buffer is disposed which may contains few messages which are not yet in pending buffer https://github.com/nats-io/nats.net/blob/master/NATS.Client/Conn.cs#L1413

**Comment by anjmao** [comment]
After doing some more investigation I found this difference in .net and go clients.

Go client is calling processOpErr before publishing new message when there is no connection.
```
Pub: 4
Recv: 4
Pub: 5
Recv: 5
Pub: 6
Recv: 6
processOpErr
Pub: 7
Pub: 8
Pub: 9
Pub: 10
```

.NET client is getting processOpErr only after few messages which are already published while no connection to server. This is why it is losing these messages since on call to processOpErr buffer is cleared and switch to pending.

```
Pub 0
Recv 0
Pub 1
Recv 1
Pub 2
Recv 2
Pub 3
Recv 3
Pub 4
Pub 5
Pub 6
Pub 7
processOpError
```

@ColinSullivan1 Do you have any idea why .NET client may act this way?

**Comment by ColinSullivan1** [comment]
@anjmao , Thank you for the research and detail here.  Great information - ideally, the clients should behave the same.  Note that with any core NATS clients (including go), messages can be dropped upon disconnect.  There's an effort to buffer, but still no guarantee of delivery.   If you require at least once delivery, you'll want to look into NATS streaming.

**Comment by anjmao** [comment]
@ColinSullivan1 Thanks. Indeed this is a problem with TCP. Stan client works fine and I was able to use stanConn.PublishAsync(..) and wait for ack from the server.
