### ISSUE TITLE
Xamarin using NATS.NET

### ISSUE THREAD

**Issue by jmptrader** [nats-io/nats.net.v1#274]
Hi ,

You know if is possible integrate nats.net into a Xamarin App ?

In order to replace SignalR layer for functions pub/sub ...

Thank's

**Comment by ColinSullivan1** [comment]
@jmptrader, I'm not aware of any limitations, but haven't personally tried it myself.  The .NET core code is has a target framework of .NET standard 1.6, so you should be OK.

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

If anyone in the community has experience with NATS.net and Xamarin we'd appreciate your input!

**Comment by jmptrader** [comment]
Thanks @ColinSullivan1 , with my team we will test this asap!

**Comment by jmptrader** [comment]
@ColinSullivan1 , I can confirm that NATS.net in an Xamarin application works fine. We are using in our prototype netstandard 2.0 and Xamarin.Forms Version 4.0.0. Thank so much.
