### ISSUE TITLE
Auto reconnect

### ISSUE THREAD

**Issue by DeployChef** [nats-io/nats.net.v1#277]
When I connect to the cluster, when I disconnect one node but continue the producer to send messages to it, I get a TimeOut Exception.
Please, tell us how to make the Stan client automatically reconnect to other live nodes of the cluster.

**Comment by ColinSullivan1** [comment]
@DeployChef, thanks for asking, I responded in the stan.net repository, [here](https://github.com/nats-io/nats.net/issues/276#issuecomment-522645473).

Thank you for using NATS!
