### ISSUE TITLE
ArrivalSubcription: any reason why this field is misspelled?

### ISSUE THREAD

**Issue by CycoPH** [nats-io/nats.net.v1#285]
In the c# nats client in Msg.cs the 'ArrivalSubcription' field is missing an s in Subscription.  
Is this a typo or historic?

**Comment by ColinSullivan1** [comment]
This was a typo; thank you for raising the issue!

**Comment by CycoPH** [comment]
I made a pull request for a bunch of typo fixes and an Exception bug

**Comment by danielwertheim** [comment]
Closed via #346 which manually integrated changes from #286 that initially solved this issue.
