### ISSUE TITLE
Visual Studio being open impacts performance

### ISSUE THREAD

**Issue by CrossBound** [nats-io/nats.net.v1#297]
I have a very odd performance issue. I'm using C# NATS.Client package testing benchmarks with a complete request/reply pattern. I have a publisher that simply sends messages and then waits for a reply while the subscriber simply receives the reply and sends back the exact data it received to the reply subject. My benchmarks were very concerning to me because I was hitting very slow times. 17 ms just for the subscriber to receive the message and about ~34 ms for the complete round trip. My messages are 54 bytes.

Here's the odd part.... If I open visual studio and the open project dialog is in focus... my performance improves to what I would expect (< 5ms complete round trip). If I move the focus off of visual studio's dialog window... my performance instantly drops back to ~34 ms. 

I cannot for the life of me figure out why visual studio being in focus impacts the performance.... I've been able to replicate this on multiple machines. I had slow performance and then installed visual studio and run it and my performance instantly speeds up. I've used this code in both WinForms application and a Console application and I get the same results with both.

Any ideas?

I've tested this with both a local instance of NATS (nats://127.0.01:4222) and remote NATS instance. Same result either way.

**Comment by ColinSullivan1** [comment]
Hmm.  This is odd indeed.  I'm wondering if tasks are being prioritized differently in the different environments - could you be using different .NET framework versions between running in VS and running on the console?  Also, from a console, if you run your tests directly with the `/REALTIME` flag, do you see a significantly different performance difference?

**Comment by CrossBound** [comment]
Here's a sample application I'm using that is exhibiting the problem.

https://github.com/CrossBound/NATS-Performance-Benchmarking

**Comment by CrossBound** [comment]
In regard to your comment, this is not debugging vs. running release. In my scenario I'm compiling the release build and running it outside of visual studio directly from the command line. After it is already running and while it is running the performance fluctuates if I open/close visual studio. Let me see if I can find a way to record my screen and give you a video of it happening.

**Comment by watfordgnf** [comment]
I pulled your source and made some small modifications to track the RTT (on the producer side). Here is what I got on my machine without VS open:
```
X:\NATS-Performance-Benchmarking-master\Publisher\bin\Release\netcoreapp3.0>producer.exe 127.0.0.1 4222
Starting publisher
Publishing
3.207 25.358 3.993 ms RTT min/max/avg

Cancelling...
Subscription disposed
Connection disposed
```
And here is the same run with VS open (I did this a few times):
```
X:\NATS-Performance-Benchmarking-master\Publisher\bin\Release\netcoreapp3.0>producer.exe 127.0.0.1 4222
Starting publisher
Publishing
3.355 25.983 4.002 ms RTT min/max/avg

Cancelling...
Subscription disposed
Connection disposed
```
No real change in RTT between the two.

https://gist.github.com/watfordgnf/42ace261c38f701bcd2d34bdeaa4bfd9

**Comment by CrossBound** [comment]
I understand... it is very confusing. Attached is a video of me showing this in action.

[NATS symptoms.zip](https://github.com/nats-io/nats.net/files/3709085/NATS.symptoms.zip)

**Comment by CrossBound** [comment]
I actually have discovered it is not tied to VS either. I can't find a common link but other applications seem to be impacting it as well. For example, when I started the screen recording software that did the same thing (caused performance to improve). Does the C# client use some sort of fancy CPU / GPU optimizations that could somehow be impacted by the activity on the machine?

**Comment by watfordgnf** [comment]
1. How bizarre.
2. No CPU or GPU optimizations.

But what could be happening is foreground vs background. If you remove the `CancelKeyPress` event listener on the producer and consumer side, does that change anything?

**Comment by CrossBound** [comment]
No, removing it did not help.

**Comment by ColinSullivan1** [comment]
Wow!  I have never, ever, ever, seen anything like this.

Did you try starting everything (clients, NATS server) with the `/realtime` flag to see if it's windows task scheduling?

If that doesn't rule it out, if you replace NATS code with something simple - loop that checks for elapsed time (to do work), and then prints the elapsed time 100,000 iterations (or whatever works for you), do you see a difference based on focus - just to check if it's specifically NATS or is a wider problem?

**Comment by CrossBound** [comment]
How do I set that in the C# client?

**Comment by ColinSullivan1** [comment]
No need to in C#, you can from the command line through the start command.  Start will launch your apps in their own console windows.

* start /realtime nats-server.exe
* start /realtime consumer.exe
* start /realtime producer.exe 

(replace with whatever your consumer and producer executables are named...)

**Comment by CrossBound** [comment]
running with start /realtime did not make a difference. I'm still only through putting 30-60 Msgs/Sec

**Comment by ColinSullivan1** [comment]
Can you try adding a `_connection.Flush()` after publishing in each app?

**Comment by CrossBound** [comment]
that just caused a deadlock.

**Comment by ColinSullivan1** [comment]
...I'm really not sure how it would.  I'm busy at the moment, but will try this next.

**Comment by CrossBound** [comment]
I changed it to use a specified inbox name ("inbox") instead of _connect.NewInbox() and that resolved the deadlock... as a side note, that also seemed to make msgs/sec go crazy (> 22K /sec) so I'm not sure how much of that is caused by the flush or not.

**Comment by CrossBound** [comment]
Wow, that seems to have resolved the issue. I had to change the inbox because I guess the flush messages were coming in the same inbox name, but now I'm running 7,400+ /sec.... very nice.

Any idea why that fixes the issue?

**Comment by ColinSullivan1** [comment]
Great!  The using the result of NewInbox() should have worked, it just creates a unique subject - not sure what happened there.

About the change in performance, I suspect the underlying socket buffers aren't being flushed as expected, and the NATS flush api is pushing out the messages quicker, reducing latency.  I'm not sure why there, but will look into possible causes.  It sounds crazy, but now I'm wondering if having focus somehow prioritizes network usage in this case - it's a hypothesis that makes some sense with what you were seeing.

Also, your code is fine as is, but there's a [Request](http://nats-io.github.io/nats.net/interface_n_a_t_s_1_1_client_1_1_i_connection.html#a4210238627f16c565d8ce88421ada056) API you can use in your producer, so you can use that and get rid of the subscriber and the flush there.  There's also an async version in case you want to do some work waiting for the reply.

Glad you're up and running, and certainly let us know if you have any questions.  If you haven't already, I invite you to join our slack org, http://slack.nats.io.

**Comment by CrossBound** [comment]
Thanks for the help.
