### ISSUE TITLE
Soft flush

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.net.v1#298]
.NET network stacks seem be behave differently on different machines - sometimes data is flushed immediately, other times there's a delay.  We need a "soft" flush API to flush the underlying socket buffer without sending a PING in various cases.

This could be a modification of the `Connection.Flush(timeout)` API to accept a `-1`, defined by a constant, e.g. `Soft`?) that will flush the socket buffer but not send a PING.  We should investigate the performance impact of flushing after every publish.  If is too detrimental to performance, then a soft flush should be called after every latency sensitive API, namely the `Connection.Request` APIs and in `msg.Respond`.

See #297.

**Comment by CrossBound** [comment]
I am very interested in this. Per #297 calling `IConnection.Flush()` after each publish improved throughput significantly, but I've noticed that while my latency is not consistently high... it sporadically causes high latency. I've discovered that flush is what's causing the high latency randomly and therefore I have a lot more outliers in RTT. In the screenshot below, notice the P99 and the maximum times. Also notice that in my logs flush is causing high latency at random times. 

![image](https://user-images.githubusercontent.com/11417093/66589964-527a3900-eb55-11e9-81ea-c6dbc0bcd1fc.png)

**Comment by ColinSullivan1** [comment]
We'll get this in soon.  My experience on windows is that for more consistent latency, you need to run the applications and server with a higher priority (ideally `realtime` or `high`), and minimize the use of other applications that will impact CPU or network.
