### ISSUE TITLE
Add support for IObservable in the existing client

### ISSUE THREAD

**Issue by danielwertheim** [nats-io/nats.net.v1#303]
Implement support for making `IAsyncSubscription` observable (`IObservable<Msg>`).

Expose it as `INATSObservable<>` under namespace `Rx` so that official `System.Reactive` lib can be brought in and used if user wants to.

The `NATS.Rx` namespace is used to contain implementations and two extension methods for returning the `IObservable<>` implementation:
- `connection.Observe(subject)`
- `asyncSub.ToObservable()`

The `NATS.Rx.Ops` namespace is used (so that you instead can use `System.Reactive` if you want) to provide simple extension methods for allowing:
- Subscribe
- SubscribeSafe
- Where
- Select

**Delegating observer**
Provide extension methods (`Subscribe` and `SubscribeSafe`) for subscribing an observer without passing an observer implementation, but just anonymous methods (delegating observer).

**Subscribe vs SubscribeSafe**
If an observer is misbehaving, `Subscribe` will remove the observer subscription and dispose it so no further dispatches from the observable will be provided to that observer. The `SubscribeSafe` member will keep the observer and provide it with future messages.

**Where**
 Extension method for hooking in a `WhereObserver` which allows for filtering on `Msg`.

**Select**
Extension method for hooking in a `MapObserver` which allows for mapping/transforming from `Msg` to `T`.

**Sample**
```csharp
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using NATS.Client;
using NATS.Client.Rx;
using NATS.Client.Rx.Ops; //Can be replaced with using System.Reactive.Linq;

namespace RxSample
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var cn = new ConnectionFactory().CreateConnection())
            {
                var temperatures =
                    cn.Observe("temperatures")
                        .Where(m => m.Data?.Any() == true)
                        .Select(m => BitConverter.ToInt32(m.Data, 0));

                temperatures.Subscribe(t => Console.WriteLine($"{t}C"));

                temperatures.Subscribe(t => Console.WriteLine($"{(t * 9 / 5) + 32}F"));

                var cts = new CancellationTokenSource();

                Task.Run(async () =>
                {
                    var rnd = new Random();

                    while (!cts.IsCancellationRequested)
                    {
                        cn.Publish("temperatures", BitConverter.GetBytes(rnd.Next(-10, 40)));

                        await Task.Delay(1000, cts.Token);
                    }
                }, cts.Token);

                Console.ReadKey();
                cts.Cancel();
            }
        }
    }
}
```

**Comment by danielwertheim** [comment]
@ColinSullivan1 unsure if we close issues upon merged to master or when released?

**Comment by ColinSullivan1** [comment]
We can after merging.  If you leave a note like `Resolved by #<issue number>`, the merge will automatically close the issue.  Thanks for merging.

**Comment by danielwertheim** [comment]
@ColinSullivan1 yes, wasn't sure of the process used so didn't use the auto resolving feature.

Closing then.
