### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by buybackoff** [nats-io/nats.net.v1#31]
Which exactly code you run to get the performance of several millions messages per sec and what hardware do you use? Is it VM on *Nix? I played with pure .NET's TCP sockets recently and cannot get such numbers even on localhost loopback. I am looking through the code to try to understand is it buffering or something else that yields such results. Also, as far as I understand you do not use IOCP or SocketAsyncEventArgs?

**Comment by ColinSullivan1** [comment]
I run the publish/subscribe examples, in a Windows 7 64 bit VM on a macbook
pro, with a local NATS server (gnatsd), all with /REALTIME priority, with
20 million messages.

In three different command prompts, run:
start /B /REALTIME gnatsd
start /B /REALTIME publish -count 20000000
start /B /REALTIME subscribe -count 20000000

Publish alone, I can typically send between 3-4 million msgs/sec.   With
one publisher and one receiver, 1 million msgs/sec, but you may see
different results.

At the low level, we achieve these levels of throughput through a lot of
optimization - increasing socket buffer sizes, optimizing read buffer
sizes, and reducing contention.  At a higher level, we reduce connection
wherever possible, and take care to optimize the fast-path in the code
through using lower level .NET APIs to manipulate data.

I encourage you to dig through the code - please don't hesitate to ask any
questions or bring up any issues!

On Wed, Jan 20, 2016 at 11:22 AM, Victor Baybekov notifications@github.com
wrote:

> Which exactly code you run to get the performance of several millions
> messages per sec and what hardware do you use? Is it VM on *Nix? I played
> with pure .NET's TCP sockets recently and cannot get such numbers even on
> localhost loopback. I am looking through the code to try to understand is
> it buffering or something else that yields such results. Also, as far as I
> understand you do not use IOCP or SocketAsyncEventArgs?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nats-io/csnats/issues/31.

## 

_Colin Sullivan_ | Principal Engineer
colin.sullivan@apcera.com brian@apcera.com  | @ColinSullivan01

**Comment by buybackoff** [comment]
So that is probably related to my inline comment about latency - do you have the latency numbers? I am now designing a system that should send messages as fast as possible (no delays), but if I do batching (for historical data) - that is just a special kind of messages and buffers/batches are explicit responsibility of API users and not hidden inside internal optimizations. It looks like I will need two channels - one optimized for latency, one for throughput. With such channels the API could be the same and one could delegate batching to the transport layer.

Do you have a plan to implement server in other languages? I must say I almost learned Go while looking through gnatsd, but I have a lot of existing code in .NET and do not want to use a broker, but want to put my logic into the broker so that it becomes a central server.

**Comment by ColinSullivan1** [comment]
Right now, we don't have latency numbers.  What do you require?  NATS could very well meet your requirements today.  A relatively simple app could create an asynchronous subscriber, start a stopwatch, send a message, then stop the stopwatch and measure in the subscriber's event handler - that'd give you pub - sub latency locally in your environment...

**Comment by ColinSullivan1** [comment]
"I almost learned go" - you have me laughing - go is very terse, relatively easy to read, and the server exemplifies many of features Go's features.  I suggest you check it out!  We aren't planning on implementing the server in other languages at the moment...  Just curious - why do you want to embed the NATS server in your server?  You can write a server architecture using pub/sub while keeping NATS separate.  That offers flexibility in separating out apps to scale, distribute load, etc.  It'd also take advantage of NATS clustering for high availability.

**Comment by buybackoff** [comment]
I do not have concrete requirements now, just Thread.Sleep(1) and BufferedStream had caught my eye. Definitely sub-millisecond for 99.9% on very fast LAN or loopback. Will play with NATS more, I like the API and built-in auth/TLS (a lucrative promise to use the same API over LAN and WAN). I had almost created the same concept of reply subject with additional ZeroMQ frame, but in NATS it is built-in and overall the project looks more lightweight and even simpler.

RE: your server comment
Then I will have NATS as an opaque transport and as a brokered system it will have much higher (at least 2x) latency by design. I need custom auth and custom certificate validation at least. Also my subjects are much simpler and I have a custom matching logic. I am at design stage now and my requirements could easily adapt to available messaging systems. I am evaluating what would be easier - to adapt NetMQ or brokered NATS for this or to go to Go. As a language it could be learned in less than an hour, but it is another world of libraries and idioms - like an Englishman in New York :)

**Comment by ColinSullivan1** [comment]
I've added a benchmark application, https://github.com/nats-io/csnats/pull/33.  Please feel free to comment/improve upon.  It's relatively simple at this point.
