### ISSUE TITLE
Add ConnectionErrorEventHandler

### ISSUE THREAD

**Issue by danielwertheim** [nats-io/nats.net.v1#319]
@ColinSullivan1 regarding implementing same/similar functionality as:
- https://github.com/nats-io/nats.go/pull/462/files
- https://github.com/nats-io/nats.go/pull/464

Is the idea that we add:

```csharp
public EventHandler<ConnErrorEventArgs> ConnectionErrorEventHandler = null;
```

and if that is hooked in, we use that upon disconnect due to error instead of `DisconnectedEventHandler`?

**Comment by ColinSullivan1** [comment]
Looking at this further, it looks like this is a replacement for the disconnected handler that can handle an error. In go, it takes priority over the Disconnected Handler.  It's called during [reconnect](https://github.com/nats-io/nats.go/blob/master/nats.go#L1813), and also called in [close](https://github.com/nats-io/nats.go/blob/master/nats.go#L3719).

In .NET, we can do tings differently, and have two options.  We can extend the ConnEvent args to include an exception if the event was generated by an error, or create a new event.  I'm in favor of extending the event.  For most cases, the exception passed will be null, but for close and disconnected, it could be set when an error caused the connection event.

**Comment by danielwertheim** [comment]
Agree. Thought it had to be as the Go client. But I think we should go with the solution you mention. That way there's no obsolete member. I guess a downside is that the consumer need to add logic in the handler.

**Comment by danielwertheim** [comment]
`ConnEventArgs` is used in the following events:

```csharp
        /// <summary>
        /// Represents the method that will handle an event raised 
        /// when a connection is closed.
        /// </summary>
        public EventHandler<ConnEventArgs> ClosedEventHandler = null;

        /// <summary>
        /// Represents the method that will handle an event raised
        /// whenever a new server has joined the cluster.
        /// </summary>
        public EventHandler<ConnEventArgs> ServerDiscoveredEventHandler = null;

        /// <summary>
        /// Represents the method that will handle an event raised 
        /// when a connection has been disconnected from a server.
        /// </summary>
        public EventHandler<ConnEventArgs> DisconnectedEventHandler = null;

        /// <summary>
        /// Represents the method that will handle an event raised 
        /// when a connection has reconnected to a server.
        /// </summary>
        public EventHandler<ConnEventArgs> ReconnectedEventHandler = null;
```
Would an `Error:Exception` member in the event arg make sense in all of them but only actually used in `DisconnectedEventHandler`?

**Comment by danielwertheim** [comment]
@ColinSullivan1 see referenced commit. Is that the solution you had in mind?

**Comment by ColinSullivan1** [comment]
Yep, the `Error:Exception` member would be unused in most handlers, but imo better than adding a new event and associated args.  It could be set for the Disconnected and Closed events.  The commit looks great!
