### ISSUE TITLE
UWP unable to connect to server

### ISSUE THREAD

**Issue by stamri** [nats-io/nats.net.v1#330]
Am using NATS client from Unity 3d 2019and it works fine. I then export the project to Visual Studio 2019 and build a UWP app. The UWP is unable to connect to NATS server (tried demo server as well). I get "unable to connect to server". I already made sure i've enabled Internet capabilites in the app's manifest. Any ideas how to resolve it?

Update: By tracing the error seems like the connection is failing on this:

> Error on deserializing read-only members in the class: No set method for property 'nonce' in type 'NATS.Client.ServerInfo'.

**Comment by danielwertheim** [comment]
I just created a new UWP and added a ref to `v0.9.0` of NATS. I added a publisher connection and subscriber connection to it that produces and responds to messages. Running against a locally hosted nats-server. Worked. The only capability that I have checked is _"Internet (Client)"_

Sample (requires a Button1): https://gist.github.com/danielwertheim/3ebf14d87a417a5fd446a03aad3bcf28

Do you have any code that can be shared?

**Comment by odlex** [comment]
Hy,

@stamri have you solved your problem ?
we also have the problem with uwp and unity,
when we build .exe  all work fine but when we build the code to uwp and we launch it nats crash with the same error bellow

**Comment by ColinSullivan1** [comment]
@stamri , @odlex , could one of you try with the latest pre-release?  The JSON parsing for ServerInfo has been reworked there.

https://www.nuget.org/packages/NATS.Client/0.10.1-pre2

As we can't reproduce it, we'd appreciate it!

**Comment by odlex** [comment]
Hy @ColinSullivan1,
it seem ok for this error with the latest pre-release, thank you !

I have another bug with subscriptions who are disconnected after each one reception... i will open another issue...

**Comment by ColinSullivan1** [comment]
@odlex, I'm glad this is working for you - thank you for letting us know.  It'll be included in the next release, likely in a few weeks.  Sorry to hear about your subscription issue - thanks for opening it, we'll take a look.
