### ISSUE TITLE
Remove Dependencies on System.Runtime.Serialization

### ISSUE THREAD

**Issue by CrossBound** [nats-io/nats.net.v1#336]
Can the serialization portion of the library be split into it's own package? In my case I have no interest in the built-in serialization support, instead I'm using the new System.Text.Json namespace to serialize direct to bytes and back, however, because the NATS.Client package has dependencies on the system serialization packages I have to carry along all of those dependencies (and a host of other dependencies that they depend upon).

**Comment by CrossBound** [comment]
![image](https://user-images.githubusercontent.com/11417093/69101230-b3cedb00-0a24-11ea-92df-9b100e0cd9f4.png)

These are all dependencies that my app has to carry along (and Its not all the way expended either).

**Comment by danielwertheim** [comment]
The Client exchanges information with the server during the handshake phase using JSON as the data format protocol. As the library currently targets .NET 4.5 and .NET Standard 1.6 System.Text.Json can not be used. One solution could be to also target .NET 4.6.1 and .NET Standard 2.0 and when doing so use System.Text.Json for serialization. Adds a little more complexity for project maintainers. 

One option could be to introduce a NATS.Client.Core package that requires e.g. a JsonSerializer and JsonDeserializer to be hooked in, then the NATS.Client package can continue to be as it is and bootstrap with the current serialization construct. Then NATS.Client.Something could be the more shiny new parts where old frameworks are left behind and e.g. take dependency on System.Text.Json. If a consumer wants, he/she can use the Core package and hook in whatever is needed. This would increase the complexity further more for the maintainers.

@ColinSullivan1 What's your take on this? Is there a way to control the format from the server to not be JSON but e.g. a simple key-value construct without hierarchy or something that is "simple" and doesn't require an external dependency?

**Comment by watfordgnf** [comment]
As we begin our migration onto .NET Core and .NET Standard, it would be nice to see S.T.J used instead of the older S.R.S.J.

On one hand, I like the idea of abstracting the core components out into its own Core package, and layering on the improvements in a downstream package.

On the other hand, this may make it difficult to take other improvements into NATS, such as Span and UTF8 support.

**Comment by danielwertheim** [comment]
@ColinSullivan1 closing as we have merged solution with embedded serializer to master. Reopen if you want to keep open until release.
