### ISSUE TITLE
Clients hangs when trying to connect to a URL that is not NATS

### ISSUE THREAD

**Issue by per-ove** [nats-io/nats.net.v1#337]
Malformed URL throws exception but if you accidentally enter an URL that is valid but not nats-server the call hangs.

**Steps to reproduce:**

```
var cf = new ConnectionFactory();
var opts = ConnectionFactory.GetDefaultOptions()
opt.Servers = new[] {a valid URL to a web server e.g. http://localhost}
try
{
   var conn = cf.CreateConnection(opts)
}
catch(Exception ex)
{
   // Some Action
}
```
**Actual Result:**
Code hangs no exception thrown.
**Expected Result:**
Exception thrown

**Comment by per-ove** [comment]
NATS.Client 0.9.0

**Comment by danielwertheim** [comment]
Thanks for reporting. There was a bug fixed in the last release, where the client could hang if a server wasn't returning data as expected e.g. when it did shutdown etc. This also affects the scenario you report.

I tried the following with the latest release `v0.10.0`:

**1)** Spun up a Http-API accepting `GET` against `http://localhost:56382`

**2)** Tried to connect

```csharp
    class Program
    {
        static void Main(string[] args)
        {
            var cf = new ConnectionFactory();
            var opts = ConnectionFactory.GetDefaultOptions();
            opts.Servers = new[] {"http://localhost:56382"};

            try
            {
                var conn = cf.CreateConnection(opts);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                Console.WriteLine(e.InnerException?.Message);
            }
        }
    }
```

**3)** Resulted in:

```
Error while performing handshake with server. See inner exception for more details.

Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

@per-ove as I understand it, this is according to expected behavior or do you see further improvements that can be made?

**Comment by danielwertheim** [comment]
@ColinSullivan1 as an improvement do you believe `Options` should only allow certain "protocols" to be defined? Or can it be a case where we need to support a http-server accepting a initiation that is upgraded or something during handshake? Similar to WS.

**Comment by per-ove** [comment]
@danielwertheim  The result from v0.10.0 is perfect.

**Comment by per-ove** [comment]
@danielwertheim  About other improvement.
For our use case we see no need for such an option. 
And if we can trust the handshake to report errors we are very satisfied.

**Comment by ColinSullivan1** [comment]
I think there's value in throwing an exception on an invalid protocol - it'd help users more quickly identify a problem.  We could accept `nats://`, `tls://` (which sets up a secure connection, like go), and just empty that defaults to `nats://`.  It shouldn't break any existing deployments.
