### ISSUE TITLE
Flusher and Reader threads are not stopped when connection is disposed

### ISSUE THREAD

**Issue by Sergey-Terekhin** [nats-io/nats.net.v1#342]
Version of package we use: 0.10.0
It seems that `Flusher` and `Reader` threads can continue working when Connection is disposed. And because they are not background, application can not be stopped in usual way

**Steps to reproduce**
- Create connection
- Dispose connection
- Watch on Threads list in VS - you can see these threads

May be it will be enough to make them background

**Comment by danielwertheim** [comment]
I just tried with the following:

```csharp
    class Program
    {
        static void Main(string[] args)
        {
            using (var cn = new ConnectionFactory().CreateConnection())
            {
                Console.ReadKey();
            }

            Console.ReadKey(); //At this point I see no named flusher or reader threads
        }
    }
```
And pausing the application and inspecting the threads at the second `Console.ReadKey()` shows no named flusher or reader thread. Those have been cleaned up.

- Can you confirm that the sample above is what should have reproduced it?
- Does the sample above show those threads for you?

**Comment by Sergey-Terekhin** [comment]
I'm sorry. It seems to be issue in our wrapper code

**Comment by ColinSullivan1** [comment]
No worries!  Thanks for using NATS!
