### ISSUE TITLE
Quetsion: Connections pooling, reuse, thread-safety

### ISSUE THREAD

**Issue by asdonation** [nats-io/nats.net.v1#350]
Hi,

Let's say I have a component which uses NATS communication in 2 ways:
1. Subscription in startup - subscribe to a certain topic & queue, handle messages, etc..
2. Publish messages from HTTP context (unrelated to subscription handlers)

Now, for the first use (1), I would obviously open a *new* NATS connection to the server, right in the startup. The subscription will use that connection, which should never be closed.

My first question - is this recommended? A ratio of 1:1 between subscription and created connections?

For the second use (2), my options are to either open a new connection on each request, or to reuse connections with a pool.

What would you recommend regarding (2)? Is it okay to pool connections? My assumption is that they're thread-safe. Also - what's the recommended pool size in such scenario?

Thanks,
Shay

**Comment by ColinSullivan1** [comment]
@asdonation, Thanks for using NATS!  

I'd recommend using many subscribers to a connection.  Compared to subscribers, connections are expensive to establish (especially with TLS), and a single connection can handle thousands of subscriptions.  When doing this, be sure to set [Options.SubscriberDeliveryTaskCount](https://nats-io.github.io/nats.net/class_n_a_t_s_1_1_client_1_1_options.html#a030dfa5eac04072735d7529147d5c562) to something low, starting between 5-10 and scaling upward as your testing dictates.

Connections are thread-safe.  I would certainly recommend reusing connections, and try starting with a single connection before pooling.  NATS can handle millions of messages/second on a single connection so one should suffice for the majority of use cases.

**Comment by duyquoc124** [comment]
Hello ColinSullivan1,
I have a web socket that received message from NATS then send the messages to client, who connected to my web socket.
When user connect to my web socket, should I use one connection to NAT or I create new connection for each user (I mean one connection by one username). Currently I have about 10000 users connected to my web socket, there are about 100 subscribers  each users.
