### ISSUE TITLE
System.Random.NextBytes potentially called concurrently

### ISSUE THREAD

**Issue by jasper-d** [nats-io/nats.net.v1#351]
When using the old request-reply style, the reply subject is created using random bytes provided by `System.Random`. https://github.com/nats-io/nats.net/blob/2687668913d390f1b92d39bf8a9522adce090746/src/NATS.Client/Conn.cs#L3204 According to my understanding of the code, calls to `Connection.NewInbox` can occur concurrently. This is problematic because `System.Random` is not thread safe an may return 0 in that case.

The same issue could possible be true for `NUID` where `System.Random` is used
https://github.com/nats-io/nats.net/blob/2687668913d390f1b92d39bf8a9522adce090746/src/NATS.Client/NUID.cs#L60 but I haven't looked through it's usage yet. 
I don't know if `System.Cryptography.RandomNumberGenerator` https://github.com/nats-io/nats.net/blob/2687668913d390f1b92d39bf8a9522adce090746/src/NATS.Client/NUID.cs#L58 is thread safe on .NET Core (I assume it's not, but I've opened an issue over on https://github.com/dotnet/docs/issues/16562).

**Comment by ColinSullivan1** [comment]
@jasper-d , thank you for raising this - much appreciated!  We'll address this before the next release.

**Comment by jasper-d** [comment]
@ColinSullivan1 Welcome, I was actually preparing a PR for the NewInbox issue when I found the RNG usage in NUID. Since RNG and its underlying CLR interop code appears to be not thread safe (just skimmed through it), I would propose to lock it to be on the safe side.

That being said, is NUID actually used anywhere? I can't find it outside of tests.

**Comment by ColinSullivan1** [comment]
Looking at the code, it'd be great if we used NUID in Inbox generation to [mirror golang](https://github.com/nats-io/nats.go/blob/6063d679d23ae5b3edb4030d5e89a6e30ea53bc6/nats.go#L2816).  Somewhere along the line I diverged there.

**Comment by ColinSullivan1** [comment]
And a PR would be welcome!

**Comment by jasper-d** [comment]
> Looking at the code, it'd be great if we used NUID in Inbox generation to [mirror golang](https://github.com/nats-io/nats.go/blob/6063d679d23ae5b3edb4030d5e89a6e30ea53bc6/nats.go#L2816). Somewhere along the line I diverged there.

Alright, I had a look at nats.go, to summarize:

- Old request style (no subscription sharing) uses: `_INBOX.<nuid>` as the reply subject
- New request style (subscription sharing) uses: `_INBOX.<nuid>.<randomtoken>` as reply subject and subscribes to `_INBOX.<nuid>.*`

> And a PR would be welcome!

Will work on it. I'm wondering though why the random token is generated in this way:
https://github.com/nats-io/nats.go/blob/master/nats.go#L2822-L2826

Isn't sufficient to use a strictly increasing integer per subscription as [nats.net already does](https://github.com/nats-io/nats.net/blob/master/src/NATS.Client/Conn.cs#L2666)?

**Comment by ColinSullivan1** [comment]
Thanks!  The choice for the random token generation was [performance related](https://github.com/nats-io/nats.go/commit/139a6ac5e099e324fc19f0c75e3be3b39ceca880).

The random token provides some level of obfuscation (avoiding leaking of metadata) to mitigate bad actors injecting responses and to avoid wrap-around issues.  Looking forward to the PR!

**Comment by jasper-d** [comment]
Honestly, I've mixed feeling about the random token after giving it some thought.
Performance wise we won't be able to beat `Interlocked.Increment`, especially when using some RNG that must be locked and is slow in general (it's on a hot path when using request/reply a lot).
I think if one is concerned about bad actors, server side authorization is the way to go.

**Comment by jasper-d** [comment]
Closing this since the fix got merged and released.
