### ISSUE TITLE
Define and adopt coding style

### ISSUE THREAD

**Issue by jasper-d** [nats-io/nats.net.v1#352]
Given that [contributors are encouraged the write idiomatic C# code](https://github.com/nats-io/nats.net#about-the-code-and-contributing), I would like to propose the definition and adoption of a common coding style too.

Personally, I like this one: https://github.com/dotnet/runtime/blob/master/.editorconfig.

**Comment by ColinSullivan1** [comment]
Formalization of the coding style is OK by me.  @watfordgnf, wdyt?

We could also add warnings to CI using https://github.com/dotnet/format.

**Comment by watfordgnf** [comment]
I love the idea of an editorconfig. Internally we use the one @jasper-d has cited.
