### ISSUE TITLE
Foreground threads preventing process from terminating

### ISSUE THREAD

**Issue by SkinnySackboy** [nats-io/nats.net.v1#353]
During recent experimentation with NATS.Client we discovered that if we do not disconnect or dispose of an existing NATS connection, our WPF app process is prevented from shutting down. I've got a feeling that this is because NATS.Client is creating foreground threads, i.e. the IsBackground property is not set to true. 

Of course under normal conditions I understand that we want to be disconnecting connections and shutting down cleanly, but on the off chance that something unexpected happens it would be nice not to have to keep the entire application process in memory.

Does anyone know whether this is done intentionally, or whether it would be possible in future versions to make sure that any explicitly instantiated threads (i.e. new Thread()) also set the IsBackground property to true?

Thanks in advance.

**Comment by SkinnySackboy** [comment]
> false

e

**Comment by SkinnySackboy** [comment]
> false

ue

> false

ue.

*Accidentally closed the issue.*

**Comment by ColinSullivan1** [comment]
Thanks for using NATS!  There wasn't any specific intention in using foreground threads - we just went with the default.  We can look into this - shouldn't see a performance difference.

**Comment by SkinnySackboy** [comment]
Thanks @ColinSullivan1 that sounds fair. Agreed, performance wise it should make no difference. If we really want to make it bulletproof we could also add a finalizer just in case the object never gets disposed, but setting the threads as background threads would already be a start.

Would you be happy if i made a PR or would you rather take care of it?

**Comment by ColinSullivan1** [comment]
I'd certainly be happy - a PR would be welcome!

**Comment by SkinnySackboy** [comment]
Excellent thanks, will take care of it.

**Comment by watfordgnf** [comment]
@SkinnySackboy I'm available to help with this if needed.

**Comment by SkinnySackboy** [comment]
Thanks @watfordgnf I've created #354
