### ISSUE TITLE
Calling Drain on a closed connection throws NATSTimeoutException instead of NATSConnectionClosedException

### ISSUE THREAD

**Issue by jadurda** [nats-io/nats.net.v1#356]
Any exceptions that occur during the private drain(int timeout) method gets replaced by a NATSTimeoutException. This is particularly unexpected in the case that Drain is called on a closed connection:

https://github.com/nats-io/nats.net/blob/c50d7f6854a556fbc5d0bae646d147499dc683b9/src/NATS.Client/Conn.cs#L3897-L3939

**Comment by ColinSullivan1** [comment]
Good catch - thanks!  I'll take a look.
