### ISSUE TITLE
unsubscribe with limit is missing on reconnect

### ISSUE THREAD

**Issue by matthiashanel** [nats-io/nats.net.v1#363]
in go, on reconnect, a subscription with a limit is followed up by unsubscribe(max-received)
This can cause unnecessary traffic and unnecessarily dropped messages in queue subscribers.

https://github.com/nats-io/nats.net/blob/3558232a673d65d4440050bb96492f2645f43892/src/NATS.Client/Conn.cs#L3594-L3605

**Comment by scottf** [comment]
There is no subscribe with a limit in .net
