### ISSUE TITLE
Publish  through connect.ngs.global

### ISSUE THREAD

**Issue by mabouchalkha** [nats-io/nats.net.v1#377]
Hi,
I want to try to publish through connect.ngs.global but cannot get any message and i don't have any error.
Are the options I made were enough?

```csharp
            var options = ConnectionFactory.GetDefaultOptions();
            options.Url = "connect.ngs.global";
            options.SetUserCredentials(@"S:\syndia-nats\synadia-keys\.nkeys\creds\synadia\NATS_CONNECT\NATS_CONNECT.creds");
            options.Secure = true;
```

Thank you

**Comment by ColinSullivan1** [comment]
Thanks for using NATS!

Those options look OK and you'd get an exception if there were problems connecting.  Can you share the code that publishes/subscribes?

**Comment by mabouchalkha** [comment]
Thank you for the quick response.
I used the sample in this repo
https://github.com/nats-io/nats.net/blob/master/src/Samples/Subscribe/Subscribe.cs
https://github.com/nats-io/nats.net/blob/master/src/Samples/Publish/Publish.cs

i just changed the options
Publisher:
```csharp
          int count = 10;
        string url = "connect.ngs.global";
        string subject = "foo";
        byte[] payload = Encoding.Unicode.GetBytes("test");
        string creds = @"S:\syndia-nats\synadia-keys\.nkeys\creds\synadia\NATS_CONNECT\NATS_CONNECT.creds";
```
Subscriber:
```csharp
       int count = 1000000;
        string url = "connect.ngs.global";
        string subject = "foo";
        bool sync = false;
        int received = 0;
        bool verbose = false;
        string creds = @"S:\syndia-nats\synadia-keys\.nkeys\creds\synadia\NATS_CONNECT\NATS_CONNECT.creds";
```

**Comment by kozlovic** [comment]
Just to be clear, NATS does not have persistence (unless using NATS Streaming or JetStream), so you would need to subscribe *before* you publish to get those messages. Could it be that you were publishing, and then subscribing?

**Comment by mabouchalkha** [comment]
Yes i know. I subscribed before publishing and both are up running.

**Comment by mabouchalkha** [comment]
I got this exception when publishing System.NotSupportedException: 'Stream does not support writing.'

In the subscriber i add this event and i've got 
```csharp
 options.ServerDiscoveredEventHandler += (sender, args) => Console.WriteLine("NATS server discovered");

            options.ReconnectedEventHandler +=
                (sender, args) => Console.WriteLine("NATS server reconnected.");
            options.ClosedEventHandler +=
                (sender, args) => Console.WriteLine("NATS connection closed");
            options.DisconnectedEventHandler += (sender, args) =>
                Console.WriteLine("NATS connection disconnected");
            options.AsyncErrorEventHandler +=
                (sender, args) => Console.WriteLine("NATS async error: {0}, Message={1}, Subject={2}", args.Conn.ConnectedUrl,
                    args.Error, args.Subscription.Subject);
```
NATS connection disconnected
NATS server reconnected.
NATS connection disconnected
NATS server reconnected.
NATS connection disconnected
NATS server reconnected.
NATS connection disconnected

I tested this with nats server local and everthing works but when i try to do with connect.ngs.global doesn't work, i don't know what i'm doing wrong

Thank you

**Comment by ColinSullivan1** [comment]
Thank you for the information, let me try to reproduce it here and I'll let you know.  I'm glad this works locally for you.

**Comment by ColinSullivan1** [comment]
Which version of the client and .NET are you using?

**Comment by mabouchalkha** [comment]
Version 0.10.0 and dotnet core 3.1

**Comment by ColinSullivan1** [comment]
Thanks @mabouchalkha.  We're looking into this, and will keep this issue up to date.

**Comment by ColinSullivan1** [comment]
I've updated the NATS Client and published a minor release with the bugfix, if you update to 0.10.1, this should work.  Let us know how it goes!

**Comment by mabouchalkha** [comment]
Yes just test it and it works perfectly 💯  now 👍 .
You are the best seriously.

Thank you a lot have good weekend

**Comment by ColinSullivan1** [comment]
Happy to help, and likewise!  Have a good weekend!
