### ISSUE TITLE
Sync data handling error in QueueGroup sample 

### ISSUE THREAD

**Issue by necdet** [nats-io/nats.net.v1#380]
Every first received message is missing in QueueGroup  sample app when running **-sync** mode.
According to my understanding from the code, the current flow which implemented in **receiveSyncSubscriber** function;

https://github.com/nats-io/nats.net/blob/1f5d474922f7134c39074f91fe7aad9942f6ed13/src/Samples/QueueGroup/QueueGroup.cs#L121-L134

could be changed as;

```C#
            using (ISyncSubscription s = c.SubscribeSync(subject, qgroup))
            {
                Stopwatch sw = Stopwatch.StartNew();
                
                while (received < count)
                {
                    if (received == 0)
                        sw.Start();
                        Msg m = s.NextMessage();
                        received++;
  
                     if (verbose)
                        Console.WriteLine("Received Message: " + m); 

                }
```

**Comment by scottf** [comment]
https://github.com/nats-io/nats.net/pull/639
