### ISSUE TITLE
Slow Subscription Consumption

### ISSUE THREAD

**Issue by Greatsamps** [nats-io/nats.net.v1#382]
We have been using NATS in production for a couple of years now with a single server and around 1,500 consumers using the NATS.net client, but have finally started analyzing in detail performance and are seeing quite regularly big delays in consuming messages on the consumer.

To keep things simple, we have a ping-pong style message that is generated on a consumer, sent to a central server via NATS which processes it and sends a reply back. Both messages have timestamps on them and identify the message that it is replying to.

What we are seeing is no issues at all between the consumer and central server, it seems to get them all the time, but at times there can be delays of several minutes before the reply message is consumed by the consumer.

To be clear we have 2 separate NATS connections for each direction of the flow.

This is the code where we are consuming from the subscription:

```
var thread = new Thread(() =>
{
    using (_subscription = _queueGroup == null 
        ? NATSConnection.Connection.SubscribeSync(_subject) 
        : NATSConnection.Connection.SubscribeSync(_subject, _queueGroup))
    {
        Connection.RaiseSubscriberConnected();
        while (_active)
        {
            try
            {
                var nextMessage = _subscription.NextMessage();

                if (nextMessage != null)
                {
                    Log.Debug("Subscriber Message Received");

                    using (var stream = new MemoryStream(nextMessage.Data))
                    {
                        NewSubscriptionItem.Invoke(Envelope.Parser.ParseFrom(stream));
                    }
                }
            }
            catch (Exception ex)
            {
                Connection.RaiseException(ex);
            }
        }
    }
})
{
    IsBackground = true
};

thread.Start();
```

The `Log.Debug("Subscriber Message Received");` line does not get hit at all during the period where we are missing replies, then after a period of time, all the outstanding messages come in in one hit... its as if there is a 'blockage' that gets cleared.

The machine(s) that the consumers are running on does have a lot going on them, but CPU never breaches around 50%.

Any pointers as to what to check next would be much appreciated!

**Comment by watfordgnf** [comment]
Two questions:
1. What connection options are you using?
2. When are you logging the timestamps on the send side? During message creation or just before calling `Publish`?

**Comment by Greatsamps** [comment]
Hi,

Thanks for the reply.

We are using these options:

var opts = ConnectionFactory.GetDefaultOptions();
            opts.MaxReconnect = 35000;
            opts.ReconnectWait = 5000;
            opts.NoRandomize = false;
            opts.Timeout = 30000;
            opts.Servers = servers;

with regards to when we are timestamping, its just before publish

**Comment by ColinSullivan1** [comment]
Thanks for using NATS!

I'd be useful to check for client side [slow consumer errors](https://docs.nats.io/developing-with-nats/events/slow), you can do that with an error handler, here's an [example](https://github.com/nats-io/nats.net/blob/1f5d474922f7134c39074f91fe7aad9942f6ed13/src/Benchmarks/Benchmark/Benchmark.cs#L205).  Are you experiencing this when there are bursts of messages from producers?

If you find you're getting these errors due to bursty data you can increase buffers with [SubChannelLength](https://nats-io.github.io/nats.net/class_n_a_t_s_1_1_client_1_1_options.html#a82c9580a9c7dd0367c53f2c1d309a039).

If your subscriber isn't keeping up and ordering of messages isn't important, load balancing via queue subscribers would be the way to do.

**Comment by Greatsamps** [comment]
Hi, sorry for the late reply here. Found the issue. Turns out that linux has a very low value for the hard and soft cap on an ARP cache (1000). It was killing of connections at random once we exceeded the 1000 mark.

**Comment by ColinSullivan1** [comment]
@Greatsamps, We're glad you have resolved your issue, and thanks for letting us know - we appreciate it!
