### ISSUE TITLE
Blazor webassembly using using NATS.NET

### ISSUE THREAD

**Issue by jmptrader** [nats-io/nats.net.v1#383]
Hi @ColinSullivan1 ,

You know if is possible integrate nats.net into a Blazor webassembly App ?

In order to provides an simple layer for functions pub/sub ...

Thank's

**Comment by ColinSullivan1** [comment]
To be honest, I haven't tried but am not aware of any limitations that would prevent it - will give it a shot.

If anyone in the NATS ecosystem has tried we'd love to hear about it!

**Comment by ColinSullivan1** [comment]
I've looked into this.  It works server-side, but not client side.  Client-side, the browser running WASM sandboxed, so the NATS client isn't allowed to create a TCP connection to the NATS server.

Server side though, there is not that restriction and NATS seems to work fine from within WASM.  I was able to send and receive messages with this (hastily written) module, based off of the default blazor server application.

```html
@page "/counter"

<h1>Counter</h1>

<p>Current count: @currentCount</p>
<p>Updates: @updated_data</p>
<p>Exception: @exceptionMsg</p>

<button class="btn btn-primary" @onclick="SendNatsMsg">Click me</button>

@code {
    private int currentCount = 0;
    private string exceptionMsg = "none";
    private string updated_data = "";
    NATS.Client.IConnection c = null;

    private void SendNatsMsg()
    {
        currentCount++;
        try
        {
            if (c == null)
            {
                c = new NATS.Client.ConnectionFactory().CreateConnection();
                c.SubscribeAsync("foo", (obj, args) =>
                {
                    updated_data = System.Text.Encoding.ASCII.GetString(args.Message.Data);
                });
            }
            c.Publish("bar", System.Text.Encoding.ASCII.GetBytes("hello_from_wasm"));
            c.Flush();
        }
        catch (Exception ex)
        {
            exceptionMsg = ex.Message;
        }
    }
}
```


If I have a nats subscriber listening to bar, the counter button sends a message:

```bash
$ nats-sub bar
Listening on [bar]
[#1] Received on [bar]: 'hello_from_wasm'
```

If I publish a message, when the page gets updated it'll reflect the new value.
```bash
 $ nats-pub foo "here's updated data"
Published [foo] : 'here's updated data'
```

The resulting page will look like this:

<img width="538" alt="Screen Shot 2020-05-29 at 4 53 02 PM" src="https://user-images.githubusercontent.com/11180189/83311616-f8ee7980-a1cc-11ea-879a-f5f7ecd3ff6f.png">

**Comment by jmptrader** [comment]
I understand this. 

I think that another option is used client websocket from blazor wasm app when websocket server for nats-server is available. 

Although this is beyond the reach of nats-net.

Thanks to you for you effort. 👍

**Comment by ColinSullivan1** [comment]
Happy to help, and I wish I had a better answer for you.  I've re-opened this issue as a reminder to investigate when websockets support lands in the NATS.net client.

**Comment by jmptrader** [comment]
Very very cool !!! in same day coincidentally @derekcollison  announces that there is support for websockets in the master , you can see it in https://github.com/nats-io/nats-server/issues/315. 👍

**Comment by derekcollison** [comment]
Yep it is there on main branch. Will be in next release.

**Comment by unicomp21** [comment]
@jmptrader any alternate strategies for websockets?

**Comment by aktxyz** [comment]
> Yep it is there on main branch. Will be in next release.

Has anyone confirmed that you can connect to a nats.io server now using blazor client in the browser?

**Comment by caleblloyd** [comment]
The library will need to implement a connection method using [ClientWebSocket](https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocket?view=netstandard-2.0) before this will work in client-side Blazor

**Comment by caleblloyd** [comment]
The library currently contains a mix of Sync and Async calls.  To work correctly with Blazor WebAssembly, we would have to ensure that all Async calls only call other Async calls.

Additionally, we would need to look into the behavior of Background Thread handling in Blazor WebAssembly, since certain parts of the library use `Task.Factory.StartNew` with `TaskCreationOptions.LongRunning` [example](https://github.com/nats-io/nats.net/blob/d6b50df0db6d84b9f2af15df448eb4b041ebf1c4/src/NATS.Client/Conn.cs#L240).  Blazor WebAssembly is single-threaded so I am not sure how this will behave.

It _may_ make sense to publish multiple copies of the library, for example `NATS.Client` with both Sync and Async calls, and `NATS.ClientAsync` with just Async calls.  The latter would ensure that Blazor WebAssembly consumers could not accidentally make a blocking call and freeze the UI thread.

**Comment by scottf** [comment]
See V2 client
