### ISSUE TITLE
Connect to IPv6 server with hostname provided

### ISSUE THREAD

**Issue by alheld** [nats-io/nats.net.v1#386]
Hi I have trouble with connect to server via IPv6 if server address is provided as a hostname.

`var cf = new ConnectionFactory();`
`var c = cf.CreateConnection("nats://somehost.domain.net:4222");`

In this case GetInterNetworkAddressFamily method gets address family of address (it's AddressFamily.DNS) and returns null. Then default TcpClient is created (IPv4) and I can't connect to server.

Basically this issue is similar to  [https://github.com/danielwertheim/nats.net/commit/1c3bcba27e2be3d90e1c8147ffeed8506adc9beb](url), which is closed but is not fully fixed because it doesn't resolve host address from DNS. 
I think `Dns.GetHostAddresses(s.url.Host);.`  should be added to GetInterNetworkAddressFamily : 

```
var ipAddress = Dns.GetHostAddressesAsync(uri.Host).GetAwaiter().GetResult().FirstOrDefault();

            if (ipAddress == null)
            {
                throw new NATSConnectionException("Cannot resolve server endpoint");
            }

            return ipAddress.AddressFamily != AddressFamily.InterNetwork &&
                   ipAddress.AddressFamily != AddressFamily.InterNetworkV6
                ? (AddressFamily?)null
                : ipAddress.AddressFamily;
```
This issue reproduces only on .Net Core < 3.0 and on .Net Framework.

**Comment by ColinSullivan1** [comment]
Would you like to submit a PR for this?

**Comment by DavidSimner** [comment]
@ColinSullivan1 I've submitted #406 to fix this issue, can you please take a look :)
