### ISSUE TITLE
Mixing async and sync requests on the same connection doesn't work

### ISSUE THREAD

**Issue by tstenvi** [nats-io/nats.net.v1#395]
Using the same connection for sending async and sync requests does not work if the async request is sent prior to the synchronous one. The second request times out. The scenario works if the old request style option is set when creating the connection. The code below can be used to reproduce the problem. The issue has been reproduced using the 0.11.0-pre1 and 0.10.0 releases of the library.

```csharp
var cf = new ConnectionFactory();
var opts = ConnectionFactory.GetDefaultOptions();

var subject = Guid.NewGuid().ToString();

var subscribeCon = cf.CreateConnection();

void EventHandler(object sender, MsgHandlerEventArgs eventArgs)
{
    subscribeCon.Publish(eventArgs.Message.Reply, eventArgs.Message.Data);
}

var s = subscribeCon.SubscribeAsync(subject, EventHandler);

//opts.UseOldRequestStyle = true; // Uncomment this and it works
var requestConn = cf.CreateConnection(opts);

var m = await requestConn.RequestAsync(subject, Encoding.UTF8.GetBytes("Async request"), 10000);
Console.WriteLine(Encoding.UTF8.GetString(m.Data));

// This request time's out
m = requestConn.Request(subject, Encoding.UTF8.GetBytes("Sync request"), 10000);
Console.WriteLine(Encoding.UTF8.GetString(m.Data));
```

**Comment by jasper-d** [comment]
Hi @tstenvi, I just pushed some changes here: https://github.com/nats-io/nats.net/pull/401
You may wanna give it a shot. It's not nice, it doesn't fix the underlying problem, but it __may__ avoid the deadlock I suspect here.
