### ISSUE TITLE
Is there any chance that nats or network or something else that block a specific subject?

### ISSUE THREAD

**Issue by haiduong87** [nats-io/nats.net.v1#398]
My previous issue https://github.com/nats-io/nats.net/issues/392
I'm now production with that code, because the actual traffic is about 1/10 of my stress test, so we can safe with that code (no out of memory, no high latency to sql server)

But now I'm facing another issue.
One or 2 of our 5 db hostings can't stably send message to subject start with "business-event.*"

My situation:
- I create new controller: BusinessEventController (we defined new NATS' based event to listen on)
- I clone all the code, duplicate everything and send to the new subject
-- Sometime it works
-- Sometime it doesn't
-- It happens on 2 of our 5 hostings
-- I change the subject to any other, it works fine too
- The old controller (CustomerController with database-notification.*) still work fine

Please help me here

**Comment by ColinSullivan1** [comment]
@haiduong87.  There isn't anything in the client that should block that subject. I have a few questions,

* What does your NATS deployment look like (# of servers, are they clustered)
* Do you have security setup to authorize subjects?
* Do some messages get through and others do not?  Or is it all or nothing?
* Is there anything in the server logs to indicate lost connections, either by a client or routes?

 May I see the code that creates the subscriptions?

Thanks,
Colin

**Comment by haiduong87** [comment]
@ColinSullivan1 
- We have 3 docker servers
-- sudo docker run -i -t --restart unless-stopped -d --name nats -p 4222:4222 -p 6222:6222 -p 8222:8222 nats:1.3.0 -c nats-server.conf --routes=nats-route://ruser:T0pS3cr3t@XXX.XXX.XXX.XXX:6222,nats-route://ruser:T0pS3cr3t@XXX.XXX.XXX.XXX:6222
-- sudo docker run -i -t --restart unless-stopped -d --name nats -p 4222:4222 -p 6222:6222 -p 8222:8222 nats:1.3.0 -c nats-server.conf --routes=nats-route://ruser:T0pS3cr3t@XXX.XXX.XXX.XXX:6222,nats-route://ruser:T0pS3cr3t@XXX.XXX.XXX.XXX:6222
-- sudo docker run -i -t --restart unless-stopped -d --name nats -p 4222:4222 -p 6222:6222 -p 8222:8222 nats:1.3.0 -c nats-server.conf --routes=nats-route://ruser:T0pS3cr3t@XXX.XXX.XXX.XXX,nats-route://ruser:T0pS3cr3t@XXX.XXX.XXX.XXX:6222
- "Do you have security setup to authorize subjects?" - I don't think so, I will ask my colleague who handle these servers 
- "Do some messages get through and others do not? Or is it all or nothing?"
-- Some messages of "business-event.*" get through, the rest of them don't
-- All messages of other subject get through. Example "businessevent.*"
- "Is there anything in the server logs to indicate lost connections, either by a client or routes?" I will check and reply tomorrow

Here's an interesting clip that demo my case (send message to "business-eventt" and "business-event")
[TestNatsSubject.mp4.zip](https://github.com/nats-io/nats.net/files/4961086/TestNatsSubject.mp4.zip) (just remove ".zip")
The code of the publisher: 
[WindowsFormsApp39.zip](https://github.com/nats-io/nats.net/files/4961128/WindowsFormsApp39.zip)
I don't have the subscriber code for now, I will update later

Thank,

Duong Nguyen

* Updated to remove IPs by @ColinSullivan1

**Comment by ColinSullivan1** [comment]
Can you update the version of the NATS server you are using to the latest?  It should be 100% compatible with clients.  There have been many fixes since v1.3.0.

**Comment by haiduong87** [comment]
@ColinSullivan1 
I will plan for updating version at weekend.
I will double check every server that sends this subject to NATS.

Thank you,

Duong Nguyen

**Comment by haiduong87** [comment]
@ColinSullivan1 

Sorry for wasting your time.
I've just checked source code of that subscriber tool, it's hard-coding a "queue1", so messages aren't delivered as expected.

Thanks for supporting me.

Duong Nguyen

**Comment by ColinSullivan1** [comment]
@haiduong87, these things happen, and thank you for letting us know - I appreciate that.

Reach out anytime if you run into other issues.
