### ISSUE TITLE
Cannot Disable Buffering in Reconnecting Mode

### ISSUE THREAD

**Issue by dara-na** [nats-io/nats.net.v1#405]
Hi! in my use case, I don't need any buffering in reconnecting mode and I can not disable this by:
```c#
var opts = ConnectionFactory.GetDefaultOptions();
opts.ReconnectBufferSize = 0; 
```
and every time in publishing message the connection state should be checked to prevent publishing with reconnecting state

**Comment by ColinSullivan1** [comment]
Hi @dara-na,

Thank you for using NATS!

You can disable buffering by setting the reconnect buffer size to `Options.ReconnectBufferDisabled;`

e.g.
`opts.ReconnectBufferSize = Options.ReconnectBufferDisabled;`

When you do that, publishing during reconnect will then throw a `NATSReconnectBufferException`.

An example can be found [here](https://github.com/nats-io/nats.net/blob/50cb20dfa3b405f540c405789adf558f21f295e8/src/Tests/IntegrationTests/TestReconnect.cs#L495).
