### ISSUE TITLE
Clients cannot connect to server when debugging if more than one Visual Studio solution is open

### ISSUE THREAD

**Issue by mattmodene** [nats-io/nats.net.v1#410]
When debugging in Visual Studio, clients cannot connect when more than one VS solution is open. Encountered using v2.1.6 of the Windows amd64 NATS server.

Recreated multiple times with the following steps and different solutions:
1. Open two Visual Studio solutions (one containing the project you plan to debug)
2. Start NATS server
3. Attempt to connect, nothing shows up on server when running with -DV flag, client gets NATSNoServerException
4. Close second VS instance
5. Reconnect to already running server with same error, but this time the server logs the client being created and then instantly closed
6. Stop and restart NATS server
7. Debug VS project and successfully connect client

**Comment by ron-gabriel** [comment]
For reference, I originally experienced this bug. It happened in VS2019 Version 16.6.5, it happened with both nats-server-v2.1.8-windows-amd64 and nats-streaming-server-v0.18.0-windows-amd64 using NATS.Client 0.10.1 on Windows 10 Pro

**Comment by ColinSullivan1** [comment]
Thanks.  I honestly don't see what could cause this, but will test it out.

**Comment by scottf** [comment]
@mattmodene This seems like a Visual Studio issue. Is it possible an exe is locked or something? Have you tried running your app from the command line?

**Comment by mattmodene** [comment]
From what I can remember at the time, this was an issue even if just one VS solution contained code that would connect to the server. I've got no idea if this is resolved at this point, not currently using NATS in a project.

**Comment by aakashratkal1** [comment]
I am experiencing the same problem even with one VS code open. Did anyone figure out what was the issue?
Versions:
VS Code: 1.64.2 (Universal)
Nats: nats-streaming-server version 0.24.3, nats-server: v2.7.4
OS: Mac OS Monterey 12.1 
Chip: Apple M1 Pro

**Comment by scottf** [comment]
@aakashratkal1 This client does not connect to STAN, just nats server and nat server running JetStream.
