### ISSUE TITLE
What's the state of JetStream support?

### ISSUE THREAD

**Issue by dorny** [nats-io/nats.net.v1#416]
Looking at a [roadmap](https://github.com/nats-io/nats-general) it looks like JetStream should be available soon.
if it's actually going to happen, what needs to be implemented in this .NET client to be able to use it?
Are there just some minor changes or some bigger rework needed?

I'm trying to get some rough overview if JetStream with .NET client will be usable in some weeks, months or it's still a 1+ year in the future.

Thanks 👍

**Comment by ColinSullivan1** [comment]
Thanks for asking - I need to update the roadmap.  Jetstream will be delivered sometime in Q4, and while accessible from the NATS.net client as is, it'd be cumbersome.

We'll want helper APIs;  the equivalent of these:
https://github.com/nats-io/nats.go/pull/585
https://github.com/nats-io/nats.go/pull/596

I aim to have these complete by end of Q4, ideally before Jetstream is released.

**Comment by dorny** [comment]
Thanks for quick reply. So I'm looking forward to test it sometime around Christmas :slightly_smiling_face:

**Comment by ColinSullivan1** [comment]
I'm going to try to carve some time out this week to start work on a branch.  The reason for end of Q4 (for an official release) is that things may require API changes as we get closer to the NATS server 2.2 (jetstream) release.  I don't anticipate any, but better to play it safe.

One I start work the added APIs can be tested against the nightly builds of the NATS server (https://hub.docker.com/r/synadia/nats-server/tags).  I could do some pre-releases for early testing as the Jetstream APIs near completion...

Of course, early feedback at that time would be welcome!

**Comment by ColinSullivan1** [comment]
An update.. Apologies, but I had to first add [java support for JetStream](https://github.com/nats-io/nats.java/pull/354), so need to postpone this.  This will come sometime in December.

**Comment by plaisted** [comment]
This still on the horizon? I want to experiment with JetStream but would be pretty cumbersome without the built in helpers so have been holding off for now.

**Comment by ColinSullivan1** [comment]
This is still on the horizon.  The java JetStream client has taken longer than anticipated.  I'm hoping to be able to get to this later this month.

**Comment by iskandersierra** [comment]
Hi @ColinSullivan1 I'm very interested in having the client for C# soon enough. I'm using STAN but want to move to JetStream if at all possible, to be able to use the better integration with NATS 2.x feature set.

I'm willing to put some effort on this issue. If you have any guideline on how to approach the API changes, I can start working under your supervision to move the client changes to the public.

Let me know if you are interested in my collaboration.

**Comment by ColinSullivan1** [comment]
@iskandersierra , thank you for offering!  We're wrapping up design of the golang and java clients, after that is complete we'll start on the JetStream API.  We'll keep your offer in mind!

**Comment by AndyPook** [comment]
Is there a roadmap for this work? It seems the dotnet bits are last in the queue and are continually bumped for other languages :(
I understand the pressures on a small org. Choices must be made.
My current project is getting desperate for some form of durable messaging but really does not want to engineer to stan then have to redo for jetstream. They are more likely to switch to some other tech. I am trying to suggest patience, but... without some guidance on timeline, it's getting harder

**Comment by ColinSullivan1** [comment]
I can understand your frustration.  We just released the java and go clients last week, so we'll start working on this next.

To be entirely transparent, the maintainers for some of the common client libraries are employed by Synadia who prioritizes how the engineering hours they donate toward the NATS project are used.  Usually this is aligned with business goals, and success there ends up providing the much of the funding to keep the NATS.io project rolling.

This client is one of the more popular so it is next and will likely mirror the java client's API, of course being .NET idiomatic where possible.

I will commit to update issue https://github.com/nats-io/nats.net/issues/417 sometime this coming week with various work items to line up and delegate for volunteers and maintainers.  I'm hoping for completion around the end of April or beginning of May.  The good news is that a lot of of the java work can be provide a nice template for the .NET implementation and that work has (hopefully) already addressed many of the tricky client issues around JetStream.

**Comment by khabalevskyi** [comment]
Hi @ColinSullivan1,

Does
> will likely mirror the java client's API, of course being .NET idiomatic where possible.

mean that .NET client will have the api to manage JetStream?
Some of our upcoming features rely on that. 
Will .NET client have something similar to [JetStreamManagement.java](https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/JetStreamManagement.java)?

Best regards,
Andrii

**Comment by ColinSullivan1** [comment]
@khabalevskyi , yes, that is the plan.  Some work has already been started on interfaces and we'll setup a branch so the community can comment.

**Comment by khabalevskyi** [comment]
@ColinSullivan1, thanks for the information. :)

**Comment by michaelkacher** [comment]
@ColinSullivan1 Are there any items the community can help with now or do we need to wait until you get your branch in? If there are any areas to help, please let me know.

**Comment by ColinSullivan1** [comment]
@michaelkacher , Thanks!  Much appreciated!

Some really low hanging fruit would be to setup testing for JetStream.  This could be to add an override to the [NATSServer](https://github.com/nats-io/nats.net/blob/master/src/Tests/IntegrationTests/TestUtilities.cs#L27) that accepts a boolean to enable JetStream (the `-js` parameter), or a NATSJetStreamServer subclass that does the same.  Other ideas would are welcome too.

I'm hoping to get an API proposed this week and then it'll be easier to separate out areas to contribute.

Many thanks @michaelkacher!

**Comment by michaelkacher** [comment]
@ColinSullivan1 I somehow missed the notification of the response, I can get that this weekend and will keep my eyes open for other items.

**Comment by WiDoWMaKeS** [comment]
Is there a current ETA for JetStream support in the .NET library?

**Comment by ColinSullivan1** [comment]
Aiming for the next few weeks.

**Comment by paulclavier** [comment]
Issue 417 does not have much in the way of information or pointers to additional issues for tracking purposes, is there an update on getting JetStream support in the .NET library?

Thank you for all your hard work :)

**Comment by sergeyshaykhullin** [comment]
@paulclavier Work in progress pr https://github.com/nats-io/nats.net/pull/465

**Comment by scottf** [comment]
Both Colin and I are working on the implementation and are doing the best we can to wrap this up. We have two other .NET contributors assisting us with some implementation and code reviews. Our goal is that we will have a beta release in a few weeks. 
I am closing this ticket. Please follow here.
The most recent PR of work in progress is https://github.com/nats-io/nats.net/pull/465
The best place to track the issue is https://github.com/nats-io/nats.net/issues/417 I'm adding line items here as well.
