### ISSUE TITLE
Add Jetstream Connection/Client APIs

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.net.v1#417]
Build the equivalent of these APIs.

Java Client: https://github.com/nats-io/nats.java/blob/main/src/main/java/io/nats/client/JetStream.java
Golang Client:  https://github.com/nats-io/nats.go/blob/master/js.go

In Progress (Draft) PR https://github.com/nats-io/nats.net/pull/465
Issue For Readme: #459 
Issue for Examples: #457 
Issue for Validation of Publish Async Validation #475 

- [x] Api Data Objects
- [x] Header Support
- [x] Protocol Status Object
- [x] JetStream Message Recognition
- [x] JetStream Management Context
- [x] Stream Management 
- [x] Consumer Management
- [x] JetStream Context
- [x] Publish Sync
- [x] Publish Async
- [x] Publish Expectations
- [x] Consumer Configuration
- [x] Push Sync Subscription
- [x] Push Async Subscription
- [x] Event Handler(s)
- [x] Pull Subscription
- [x] Pull Batch
- [x] Pull No Wait
- [x] Pull Expires
- [x] Pull Fetch
- [x] Options
- [x] AutoAck
- [x] Alternate Prefixes
- [x] Heartbeat
- [x] Flow Control
- [x] Bind Mode
- [x] Deliver Subject  (Todo: Test / Validate)
- [x] Filter Subject  (Todo: Test / Validate)
- [x] ACK - Consumer Pending Counts, domain and account
- [x] server v.2.4.0 Queue

**Comment by ripienaar** [comment]
Also https://github.com/nats-io/nats.go/pull/599

**Comment by scottf** [comment]
Pre-release 1 is available. https://www.nuget.org/packages/NATS.Client/0.14.0-pre1

**Comment by scottf** [comment]
Pre-release 3 is available. 
https://github.com/nats-io/nats.net/releases/tag/0.14.0-pre3
https://www.nuget.org/packages/NATS.Client/0.14.0-pre3

**Comment by scottf** [comment]
0.14.0 is released. https://www.nuget.org/packages/NATS.Client
