### ISSUE TITLE
Does nats. net client works for. Net 5.0 apps

### ISSUE THREAD

**Issue by imtiazpk** [nats-io/nats.net.v1#428]
Hi,
I want to use nats. Net client in. Net 5.0 worker service. This is compatible with. Net 5.0?

Regards
IK

**Comment by ColinSullivan1** [comment]
@watfordgnf , would you mind taking a look at this?

**Comment by jasper-d** [comment]
It works, we are using it in production.

**Comment by ColinSullivan1** [comment]
Excellent - thanks @jasper-d.  Much appreciated!

**Comment by watfordgnf** [comment]
We use it as well in QA on .NET 5.
