### ISSUE TITLE
Remove Sleep before flush

### ISSUE THREAD

**Issue by israellot** [nats-io/nats.net.v1#429]
https://github.com/nats-io/nats.net/blob/221f46b8d80e7f8936604f46fb9959437a03f3c5/src/NATS.Client/Conn.cs#L2283

1. I understand the intention here, but for scenarios where delivery speed is more important than throughput, I believe this should be off. Maybe we can have it as a configuration? 

2. We could probably yield AFTER flushing to the buffer

**Comment by ColinSullivan1** [comment]
@israellot , Thanks for the observation and suggestions!

We could surface this as a configuration option...  

For some history, this came about after quite a bit of performance testing.  For highly latency sensitive applications, I've added a flushBuffer() api on the connection, which directly flushes the underlying buffer.

2. certainly sounds feasible....  Thanks!  Really wish we'd thought of that. :)

There's a lot on our plate with Jetstream right now so it may be a bit before we can look into this in depth.  This is in the fastpath so we are very cautious with changes.  Would you happen to have a performance comparison of these options?

**Comment by israellot** [comment]
Thanks for the quick reply @ColinSullivan1 ! 
I was just searching for reasons to explain a 1 to 1.5ms added latency when using NATS over a raw tcp. 
I will fork and test and report back here if there's indeed any difference. Thanks for pointing out the FlushBuffer, that might be enough indeed.

**Comment by israellot** [comment]
![image](https://user-images.githubusercontent.com/840042/104665787-08192d80-56b1-11eb-8a71-65c8283a5be9.png)

This is a simple rtt measure for a setup consisting of a 5 nodes NATS cluster. That's the mean rtt observed at each time window. Application uses C# client and the pong is written at the same thread the ping comes from. 
The the impact moving `Task.Sleep(1)` to after flushing the buffer is a 1ms drop, from ~3ms to ~2ms. 
Not a very scientific test, but validates the proposal at least for further investigation. 

```while (!isFlusherDone())
            {
                bool val = waitForFlusherKick();
                if (val == false)
                    return;

                lock (mu)
                {
                    if (!isConnected())
                        return;

                    if (bw.CanWrite)
                    {
                        try
                        {
                            bw.Flush();
                        }
                        catch (Exception) {  /* ignore */ }
                    }
                }

                // Yield for a millisecond.  This reduces resource contention,
                // increasing throughput by about 50%.
                Thread.Sleep(1);
            }
