### ISSUE TITLE
ISubscription should inherit IDisposable

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.net.v1#433]
From a user:

> Wouldn't it be better to make ISubscription inherit IDisposable rather than ISyncSubscription and IAsyncSubscription inherit both ISubscription and IDisposable individually? That way, if I want to maintain multiple subscriptions of both sync and async for a single connection where I keep all subscriptions as ISubscription in a dictionary keyed by subject, I have to cast appropriately to dispose all subscriptions when the connection close.

Would want to test to be sure an upgrade wouldn't break any code.

**Comment by watfordgnf** [comment]
I think this is a safe addition to the API. Our end users do not create instances of ISubscription's used by NATS, so the usual problems listed here do not apply:
https://docs.microsoft.com/en-us/dotnet/core/compatibility/
