### ISSUE TITLE
IAsyncSubscription loosing messages published immediately after subscription

### ISSUE THREAD

**Issue by blstjohnson** [nats-io/nats.net.v1#440]
Hello!

I have an issue with synchronizing instances of my service via nats. Each instance can either start an async subscription or publish message to a topic. 
The problem is when time elapsed between subscription and publish is less than 100ms. In this case i can't get message published, and there are also no errors indicating that something went wrong.

Don't know if this is related, but in debug i found, that readloop function in Conn.cs throws NullReferenceException on line 1753:
`len = br.Read(buffer, 0, Defaults.defaultReadLength);`

Nats client version: 0.11.0
Nats server: 2.1.9

**Comment by jasper-d** [comment]
You can flush after subscribring and before publishing to minimize the chance of loosing messages. See #403

**Comment by blstjohnson** [comment]
Yes, that's worked. Thanks a lot.
Suppose that nre is not an issue.

**Comment by ColinSullivan1** [comment]
A bit concerned about the NRE - the BufferedReader should not be nulled out under a lock.

**Comment by blstjohnson** [comment]
Looks like this NRE is caused in disposing connection. In this code I always get NRE in pubConnection's readloop after Dispose is called:

`var subConnectionFactory = new NATS.Client.ConnectionFactory();
            var pubConnectionFactory = new NATS.Client.ConnectionFactory();

            var subConnection = subConnectionFactory.CreateConnection(natsOptions);
            var sub1 = subConnection.SubscribeAsync("test.sub1");
            
            sub1.MessageHandler += (o, e) => this.trace.WriteLine("1: {2} got message topic: {0} message: {1}", e.Message.Subject, Encoding.UTF8.GetString(e.Message.Data), DateTime.Now);
            
            sub1.Start();
            
            using (var pubConnection = pubConnectionFactory.CreateConnection(natsOptions))
            {
                pubConnection.Publish("test.sub1", Encoding.UTF8.GetBytes("publish 1"));
            }`

**Comment by ColinSullivan1** [comment]
@sharoukin , thanks for raising this issue - we'll take a look.

**Comment by scottf** [comment]
@sharoukin Can you test this out with a recent release. We made a change where the consumer was setup before the subscription. If the server isn't busy, it might start sending messages right away, before the subscription is setup. We changed the order so the subscription is setup first so there is a place for messages to go. https://github.com/nats-io/nats.net/pull/597
