### ISSUE TITLE
Add Reconnect API

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.net.v1#442]
Add an API to trigger a reconnect.

Just Reconnect:
`IConnection.Reconnect();`

Reconnect and Replace URLs:
`IConnection.Reconnect(string newUrls);`
`IConnection.Reconnect(string []urls);`

**Comment by watfordgnf** [comment]
Is this intended to be synchronous or asynchronous? I'd suggest including `ReconnectAsync` as well.

**Comment by ColinSullivan1** [comment]
Good idea, could provide `Task<IConnection> IConnection.ReconnectAsync();` and overloads...
