### ISSUE TITLE
processOpError does not propagate its Exception to the DisconnectedEventHandler when reconnecting

### ISSUE THREAD

**Issue by esadaoui** [nats-io/nats.net.v1#444]
Hello, I am using NATS.Client 0.11.0.

When `processOpError(Exception e)` is called, the Exception `e` is not propagated in `lastEx`.
Thus, the method `doReconnect()` find nothing [here](https://github.com/nats-io/nats.net/blob/0.11.0/src/NATS.Client/Conn.cs#L1568) and trigger the event `Opts.DisconnectedEventHandler` with the property `Error` set to `null`.  

It can be easily reproduced by creating "Connection is stale" error. Run any of your process connected to NATS with a `MaxPingsOut` set to 1 and `PingInterval` set to a very little value.

**Comment by scottf** [comment]
It appears that this is intended. Not sure why, but there is a unit test just for it.
https://github.com/nats-io/nats.net/blob/master/src/Tests/IntegrationTests/TestConnection.cs#L145
