### ISSUE TITLE
demo server

### ISSUE THREAD

**Issue by furesoft** [nats-io/nats.net.v1#446]
can i use the demo server for small production apps or can i host a sevrer anywhere for free?

**Comment by watfordgnf** [comment]
What demo server are you referring to?

NATS (the server) is free as in beer. NATS (the client) is free as in beer.

**Comment by furesoft** [comment]
im referring to demo.nats.io:4222

**Comment by kozlovic** [comment]
Do not use `demo.nats.io` for production since it is not protected and anyone could see your data. If you want a hosted solution, you may want to look at NGS (this is a Synadia offering, which has free plans): https://synadia.com/ngs/pricing

**Comment by ColinSullivan1** [comment]
Synadia has a free tier (100% free, no credit card required) but the SLAs are best effort.  It's great for experimenting and playing around, but no guarantees.

There is a better developer tier that accepts a credit card and under typical usage would be 100% free, and does have the same SLAs as project or business plans - 4KB max message size, 50 concurrent connections and 5GB allowed per month.

The NATS server is OSS, so you can deploy that yourself anywhere and just pay for the cloud resources you'd use from your vendor of choice.
