### ISSUE TITLE
Header support for separators

### ISSUE THREAD

**Issue by scottf** [nats-io/nats.net.v1#448]
See https://github.com/nats-io/nats.deno/issues/147 for details

```
separators  = "(" | ")" | "<" | ">" | "@" | "," | ";" | ":" | "\" | <">
              | "/" | "[" | "]" | "?" | "=" | "{" | "}" | space | tab
```

**Comment by watfordgnf** [comment]
So, per https://tools.ietf.org/html/rfc2616#section-2.2 and https://tools.ietf.org/html/rfc822#section-3.2 we would need to do two things:
1. Quote the containing string
2. Escape the value if `\` or `"` (although we could escape _any_ visible character if we so chose)

**Comment by scottf** [comment]
Yes. I would only bother with escaping `\` and `"` when serializing but we need to handle anything when de-serializing
> 1. Quote the containing string
> 2. Escape the value if `\` or `"` (although we could escape _any_ visible character if we so chose)

**Comment by watfordgnf** [comment]
I'm a bit pressed for time for the next two weeks (job change), so if this is an immediate need I can't work on it right now.

**Comment by scottf** [comment]
Based on [ADR-4](https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-4.md) this is not necessary anymore. Values are not encoded.
