### ISSUE TITLE
Don't block thread on each subscription.

### ISSUE THREAD

**Issue by AlexanderButs** [nats-io/nats.net.v1#449]
Hi.

Thanks for such a good product. NATS is great!

Context: I want to build a scalable architecture where I need to push notifications from backend to websocket connection. I want to use NATS as a messaging platform for this solution. So each websocket server needs to make a NATS subscription per each websocket client. So each websocket server needs to create thousands of NATS subscriptions.

Issue: library is no scalable in terms of thread usage. When subscription is added separate Task is started to process messages for this subscription in AsyncSub.enableAsyncProcessing. Then this task/thread is blocked waiting for incoming messages in Conn.deliverMsgs#1803 which is not a best practice. Good practice is to use non-blocked approach to "wait" for incoming messages.

Any thoughts?

Cheers.

**Comment by watfordgnf** [comment]
I think having 1 subscription per websocket connection would not be best, no matter the NATS Client. But you're correct that the particular implementation in the .NET client makes that doubly so.

Is there a requirement that each WS connection be able to handle their _own_ subject, or do they all listen for every message?

I have an app which manages websocket clients that require pub-sub, and do so with two subscriptions per server:
- A broadcast pub/sub subscription (e.g. `namespace.{base-subject}.broadcast`)
- A direct-to-client subscription (e.g. `namespace.{base-subject}.direct.{server-id}.>`)

A SignalR hub manages pushing the received messages to the appropriate WS clients in both cases. Routing to specific WS clients is done inside the hub as well, using a unique ID for the WS client. The WS client unique ID is appended to a unique ID the server creates at service startup when choosing a subject for direct messages. This way per WS client messages can be filtered per-server, reducing unnecessary traffic to the SignalR hub.

**Comment by AlexanderButs** [comment]
Thanks for sharing your thoughts with me.

> Is there a requirement that each WS connection be able to handle their own subject

Correct. When client connects to websocket server it (websocket server) creates personal subscription in NATS to route messages for this particular client to proper websocket server (using client unique id). I'm doing so to be able to publish messages from backed services directly to NATS and it will do the rest (proper routing to proper websocket server).

Your approach will work as well but to push message from any backed service you need to know which subject to publish to (by server id). So you will need to know on any backed service which websocket server client is connected to.

I agree, there are several "right" solutions for this problem, but issue is still there :-)

**Comment by ColinSullivan1** [comment]
Check out https://github.com/nats-io/nats.net/issues/384#issuecomment-636129728.

You can set [Options.SubscriberDeliveryTaskCount](https://nats-io.github.io/nats.net/class_n_a_t_s_1_1_client_1_1_options.html#a030dfa5eac04072735d7529147d5c562) to something low and scale upward as necessary.

I'm thinking we should default to a sane number of tasks (3-5) to handle subscriptions rather than one Task per subscription (aimed at performance out of the box).

**Comment by watfordgnf** [comment]
In our case the backend services know about these clients due to their registration messages (`ClientRegistrationNotification`) coming over: `namespace.{base-subject}.broadcast`. This message includes the full ID (e.g. `{server-id}.{client-id}`, which is enough to route messages to them.

**Comment by AlexanderButs** [comment]
> Check out [#384 (comment)](https://github.com/nats-io/nats.net/issues/384#issuecomment-636129728).
> 
> You can set [Options.SubscriberDeliveryTaskCount](https://nats-io.github.io/nats.net/class_n_a_t_s_1_1_client_1_1_options.html#a030dfa5eac04072735d7529147d5c562) to something low and scale upward as necessary.
> 
> I'm thinking we should default to a sane number of tasks (3-5) to handle subscriptions rather than one Task per subscription (aimed at performance out of the box).

Oh, I see. Thanks for clarification. This would work, I guess.

> In our case the backend services know about these clients due to their registration messages (`ClientRegistrationNotification`) coming over: `namespace.{base-subject}.broadcast`. This message includes the full ID (e.g. `{server-id}.{client-id}`, which is enough to route messages to them.

What do you do in case of scale out (dynamically spawning new backed services)? New backed services will not know about client connections, as I understand.

**Comment by watfordgnf** [comment]
Two details left unsaid in our pattern:
1. Registrations are not persisted but instead repeated as a heart beat (sacrifice traffic for dealing with removing stale clients from any data stores). This is also how new ephemeral encryption keys are published (ephemeral ECDH).
2. New backend services are on queue groups and would only be talking with a WS Client directly if the WS Client interacted with them.

**Comment by ColinSullivan1** [comment]
Do the back end services need to maintain any state about a client between requests?  If not, then as @watfordgnf suggested, certainly use queue groups.  You can scale up or scale down subscribers in a queue group seamlessly and NATS would act as a layer 7 load balancer for you.  If your application does require to maintain client state between requests you'll need to have some place to store that in your application (or between application if clients can traverse your servers).  

More can be found queue subscriptions here:  https://docs.nats.io/developing-with-nats/receiving/queues

Also, back to scalability, checkout the unit test [here](https://github.com/nats-io/nats.net/blob/master/src/Tests/IntegrationTests/TestSubscriptions.cs#L824); the .NET client should scale to handle thousands of subscribers; most of the resources should be spent on your application logic.

**Comment by AlexanderButs** [comment]
Yeah, thanks guys for your advice regarding possible architecture approaches. I appreciate that. Will consider these patterns for our use cases.

SubscriberDeliveryTaskCount would solve my problem partially. You can close this issue if you are not going to get rid of those blocked threads.

Thanks.

**Comment by ColinSullivan1** [comment]
Absolutely - we're happy to help, and thank you for using NATS.  If you aren't there already, feel free to join us on [slack](https://slack.nats.io/).  Many of the NATS maintainers are there to answer questions and provide guidance.  It also provides an opportunity to discuss your architecture with others in the NATS community who may share their experiences.
