### ISSUE TITLE
Update the default SubscriberDeliveryTaskCount

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.net.v1#450]
The [SubscriberDeliveryTaskCount](https://nats-io.github.io/nats.net/class_n_a_t_s_1_1_client_1_1_options.html#a030dfa5eac04072735d7529147d5c562) default should be set to something sane like 3.  Currently it is zero which is too strongly biased toward high throughput with a low number of subscriptions and does not support many subscriptions in one application as one thread to be created per subscription.

This issue has come up a number of times - we should default to scalability over throughput, supporting many subscriptions.  It is more common to need many thousands of subscriptions versus millions of messages per second.

Some testing would be appreciated to find a default that would support 1000 subscriptions at 100 msgs/sec on common hardware, like a laptop.  It is set [here](https://github.com/nats-io/nats.net/blob/59eca379ead07610244a385b4c110ce7987c13f3/src/NATS.Client/Options.cs#L209).

See:  https://github.com/nats-io/nats.net/issues/449#issuecomment-825454061

**Comment by scottf** [comment]
Closing - will not be changed.
