### ISSUE TITLE
Add JetStream Functionality for Integration Testing

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.net.v1#456]
Enhance the integration tests to provide JetStream functionality.  This could be a subclass of the [NatsServer](https://github.com/nats-io/nats.net/blob/master/src/Tests/IntegrationTests/TestUtilities.cs#L27) with JetStream enabled.

**Comment by michaelkacher** [comment]
@ColinSullivan1 I started this with the pull request https://github.com/nats-io/nats.net/pull/461. Let me know if there is feedback or items that would be valuable to change or add.

**Comment by ColinSullivan1** [comment]
@michaelkacher - Thanks!  I'll take a look.

**Comment by michaelkacher** [comment]
@ColinSullivan1 I believe this issue has been completed with #461 being merged. Please let me know when there is help that is needed to get the JetStream client in!

**Comment by ColinSullivan1** [comment]
It has been completed - thanks!

I've made some progress with the client APIs, will hopefully have a PR this week for review.  At that point we should have more opportunities for collaboration or to contribute.  Thanks for offering to help, much appreciated!
