### ISSUE TITLE
Add JetStream Examples

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.net.v1#457]
JetStream Examples

- [x] JetStreamManageConsumers
- [x] JetStreamManageStreams
- [x] JetStreamPublish
- [x] JetStreamPublishAsync
- [x] JetStreamPublishVsCorePublish
- [x] JetStreamPublishWithOptionsUseCases
- [x] JetStreamPushSubcribeBasicSync
- [x] JetStreamPushSubcribeBasicAsync
- [x] JetStreamPushSubscribeBindDurable
- [x] JetStreamPushSubscribeFilterSubject
- [x] JetStreamPushSubscribeDeliverSubject
- [x] JetStreamPullSubBatchSize
- [x] JetStreamPullSubBatchSizeUseCases
- [x] JetStreamPullSubExpiresIn
- [x] JetStreamPullSubExpiresInUseCases
- [x] JetStreamPullSubFetch
- [x] JetStreamPullSubFetchUseCases
- [x] JetStreamPullSubNoWaitUseCases
- [ ] JetStreamPushSubscribeQueueDurable

The examples should take command line parameters for # of messages, subject name, streams, AckMode, auto-creation consumers and streams, etc.

Metrics should be published when complete for rudimentary client benchmarking.

**Comment by scottf** [comment]
0.14.0 is released. https://www.nuget.org/packages/NATS.Client
