### ISSUE TITLE
Using .NET client Version (0.10.1) sometime connection takes 10 seconds.

### ISSUE THREAD

**Issue by imtiazpk** [nats-io/nats.net.v1#469]
I am facing an issue posted on this link https://github.com/nats-io/nats-server/issues/2298

One of my .NET 5.0  service checks the NATS server TCP health by connecting and then disconnecting from from NATS server port 4222 after some interval 10 seconds. Some time the connection takes 10 seconds which causes the NLB to fail the health check of my service. Not sure the issue is with the .NET client or not please have look on the above issue.

**Comment by scottf** [comment]
@imtiazpk You might want to look into using the cli for health checks. But a straight connection should not take anywhere near 10 seconds so something is wrong with the server, network, client configuration or client use. Without code I really can't help much more.

**Comment by scottf** [comment]
Closing - no response from reporter
