### ISSUE TITLE
Missing Maual ACK Method in Subscribe/Message

### ISSUE THREAD

**Issue by Exagram** [nats-io/nats.net.v1#471]
I have workers that subscribe to messages and sometimes I don't want to ACK messages.

Looking at the docs I see that NATS supports the concept of Ack's: [https://docs.nats.io/nats-concepts/acks](https://docs.nats.io/nats-concepts/acks)

However this sister package seems to support Ack's: [https://github.com/nats-io/stan.net](https://github.com/nats-io/stan.net)

Should I switch over from NATS to NATS Streaming (STAN)?

**Comment by sergeyshaykhullin** [comment]
No, please consider to try JetStream as soon as it will released on dotnet https://github.com/nats-io/nats.net/pull/465

Docs: https://docs.nats.io/jetstream/jetstream

**Comment by scottf** [comment]
@Exagram We are working on the .NET client adding support for JetStream. If you are not already using STAN, I would wait for the .NET client work to be completed. See https://github.com/nats-io/nats.net/issues/417 for more information.
