### ISSUE TITLE
.NET Core NuGet package?

### ISSUE THREAD

**Issue by dedale** [nats-io/nats.net.v1#474]
Hello!

Do you know when a NuGet package will include a .NET Core version of nats.io official .NET Client?

Currently, latest 0.12 version only support .NET Framework 4.6 or .NET Standard 1.6.

We would need at least .NET Standard 2.0.

Thanks
Vianney

**Comment by sixlettervariables** [comment]
.NET Standard 1.6 is implemented by .NET Core 1.0+ and .NET 5.0+. See https://docs.microsoft.com/en-us/dotnet/standard/net-standard

Why would you need .NET Standard 2.0 exactly?

**Comment by dedale** [comment]
> 
> 
> .NET Standard 1.6 is implemented by .NET Core 1.0+ and .NET 5.0+. See https://docs.microsoft.com/en-us/dotnet/standard/net-standard
> 
> Why would you need .NET Standard 2.0 exactly?

Well I thought this was a requirement to be able to use this lib for both Windows and linux in .NET Core 3.1.
Thanks for your help!

**Comment by sixlettervariables** [comment]
Given Microsoft needs an implementation matrix for .NET Standard to make sense of it I can understand the confusion. Makes it harder for us all!

Happy to see the day when we're all on just plain ole ".NET".
