### ISSUE TITLE
Lots of code in the files

### ISSUE THREAD

**Issue by ilhom0258** [nats-io/nats.net.v1#480]
Hello, 
My name is Ilhomjon Buriev. I want to share my 2 cents to the community of Jetstream. Due to analyzing the codebase I have noticed of too many lines of code. Therefore, due to code styling I want to break to some little files. Could you please say if it's a good idea?)
Thanks

**Comment by scottf** [comment]
I personally agree that it is best practice to have more, smaller files, but I'm also coming from a Java background. The paradigm in the .NET world may not be exactly the same. Could you provide some examples? Also, please feel free to propose code changes via PR.

**Comment by scottf** [comment]
@ilhom0258 could you add some more comments, maybe even make a fork and refactor something in the style you suggest?
