### ISSUE TITLE
Request Reply deadlocking coming from WPF application

### ISSUE THREAD

**Issue by kharkins-23** [nats-io/nats.net.v1#496]
**Description**

Hello, I am currently attempting to use the NATS Request/Reply functionality from within a WPF app. The behavior I am currently seeing however, is that once my request goes into the NATSConnection, my application deadlocks until the timeout is completed. The subscriber never receives the message. Below is an example of the basic WPF I have spun up to recreate the issue, have tried both async and sync.

```
namespace TestWPFNats
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private async void Button_Click(object sender, RoutedEventArgs e)
        {
            var guid = Guid.NewGuid().ToString();
            var clientId = Guid.NewGuid().ToString();
            var configurationRetriever = new MessagingConfigurationRetriever();
            
            var natsConnectionOptions = NatsOptionsFactory.Create().Build(configurationRetriever.HostsAndPorts, clientId);
            var natsConnection = new ConnectionFactory().CreateConnection(natsConnectionOptions);
            
            var proto = new RandomProtoObject();
            
            var response = await natsConnection.RequestAsync("my_topic_name", proto.ToByteArray(), 60000);
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            var guid = Guid.NewGuid().ToString();
            var clientId = Guid.NewGuid().ToString();
            var configurationRetriever = new MessagingConfigurationRetriever();
            
            var natsConnectionOptions = NatsOptionsFactory.Create().Build(configurationRetriever.HostsAndPorts, clientId);
            var natsConnection = new ConnectionFactory().CreateConnection(natsConnectionOptions);
            
            var proto = new RandomProtoObject();
            
            var response = natsConnection.Request("my_topic_name", proto.ToByteArray(), 60000);
        }
    }
}
```

Any help would be greatly appreciated, not sure where else to look. I suspected at first it may have had to do with the InFlightResponse TaskCompletionSource, but unsure if thats the case, since the message is never even being sent out.

**Versions**

C# nats.net (0.12.0)
nats-server (2.5.0)
nats-c (2.4.0)

**Comment by scottf** [comment]
@kharkins-23 So we know by running Requestor and Replier samples in the project (https://github.com/nats-io/nats.net/tree/master/src/Samples) that the core request reply functionality works.
Is your subscriber up and running before your request? If it's not, those publish requests go into the ether and it would make sense that they wait the entire timeout.
You basic button click code as far as NATS looks fine. Can you run the server with -DV to see what's going on, maybe to see if the server see's messages coming in?

**Comment by jasper-d** [comment]
I cannot reproduce that, neither on .NET 5 nor on .NET 4.something. Could you provide an minimal (not) working example, including the XAML, .csproj, and a responder?

@scottf Shouldn't it throw a NoResponderException if there isn't anyone who is subscribed to the subject?

With `-DV` you should see a message flow like this for req/reply:

```
[::1]:57346 - cid:47 - "v0.0.0.0:.NET" - <<- [SUB _INBOX.DQlKW_9cf63VxfzMod1Yf1.*  1]               
[::1]:57346 - cid:47 - "v0.0.0.0:.NET" - <<- [PUB my_topic_name _INBOX.DQlKW_9cf63VxfzMod1Yf1.1 1]  
[::1]:57346 - cid:47 - "v0.0.0.0:.NET" - <<- MSG_PAYLOAD: ["\x18"]                                  
[::1]:57341 - cid:42 - "v0.0.0.0:.NET" - ->> [MSG my_topic_name 1 _INBOX.DQlKW_9cf63VxfzMod1Yf1.1 1]
[::1]:57341 - cid:42 - "v0.0.0.0:.NET" - <<- [PUB _INBOX.DQlKW_9cf63VxfzMod1Yf1.1 1]                
[::1]:57341 - cid:42 - "v0.0.0.0:.NET" - <<- MSG_PAYLOAD: ["\x18"]                                  
[::1]:57346 - cid:47 - "v0.0.0.0:.NET" - ->> [MSG _INBOX.DQlKW_9cf63VxfzMod1Yf1.1 1 1]              
```

**Comment by wilstoff** [comment]
To give some more clarity, we agree the request reply generally works.  We have nunit tests that prove it works from a .netcore as well as regular .net 4.7.2.  I believe this has to do with asynchronous continuations when coming from the UI thread, but our normal techniques ConfigureAwait(false) and analyzing all the awaits and tasks for .Result/.Wait haven't come up with anything out of the norm in your code. We'll run with the -DV flags and see what's going on.

**Comment by kharkins-23** [comment]
Thanks for the quick response! Heres what I see on the nats-server with -DV enabled

```
[636] 2021/10/04 13:51:41.998052 [DBG] 10.10.161.110:55175 - cid:121 - Client connection created
[636] 2021/10/04 13:51:42.014533 [TRC] 10.10.161.110:55175 - cid:121 - <<- [CONNECT {"verbose":false,"pedantic":false,"ssl_required":false,"name":"b398830f-e019-4b09-b764-d9e7e4266f5c","lang":".NET","version":"1                                                                       .2.3.0","protocol":1,"echo":true,"headers":true,"no_responders":true}]
[636] 2021/10/04 13:51:42.014680 [TRC] 10.10.161.110:55175 - cid:121 - "v1.2.3.0:.NET:b398830f-e019-4b09-b764-d9e7e4266f5c" - <<- [PING]
[636] 2021/10/04 13:51:42.014717 [TRC] 10.10.161.110:55175 - cid:121 - "v1.2.3.0:.NET:b398830f-e019-4b09-b764-d9e7e4266f5c" - ->> [PONG]
[636] 2021/10/04 13:51:42.083092 [TRC] 10.10.161.110:55175 - cid:121 - "v1.2.3.0:.NET:b398830f-e019-4b09-b764-d9e7e4266f5c" - <<- [SUB _INBOX.uHgt21IfmyJOZiwF3EyTv2.*  1]
[636] 2021/10/04 13:51:42.103626 [TRC] 10.10.161.110:55175 - cid:121 - "v1.2.3.0:.NET:b398830f-e019-4b09-b764-d9e7e4266f5c" - <<- [PUB safetysettings.upsert.click _INBOX.uHgt21IfmyJOZiwF3EyTv2.1 111]
[636] 2021/10/04 13:51:42.103665 [TRC] 10.10.161.110:55175 - cid:121 - "v1.2.3.0:.NET:b398830f-e019-4b09-b764-d9e7e4266f5c" - <<- MSG_PAYLOAD: ["\n>\x1a<\n\x05ApplicationName\x10\x01\x1a\x10Firm\"\fInfosys*\nWhereAmIB\x05Saber\"-\b\x01\x12)\n'\n\x1fLimitStringr\x10\x80ȯ\xa0%"]
[636] 2021/10/04 13:51:44.381818 [DBG] 10.10.161.110:55175 - cid:121 - "v1.2.3.0:.NET:b398830f-e019-4b09-b764-d9e7e4266f5c" - Client Ping Timer
[636] 2021/10/04 13:51:44.381889 [TRC] 10.10.161.110:55175 - cid:121 - "v1.2.3.0:.NET:b398830f-e019-4b09-b764-d9e7e4266f5c" - ->> [PING]
```

Nothing ever comes after that last [PING] and we hit the timeout. And something to note, this does work totally fine from a normal nunit test case I have setup doing the same thing/sending the exact same proto object to the same topic, it only does not work coming from the WPF application

**Comment by jasper-d** [comment]
@kharkins-23 That looks like nobody is responding to your message. Your message (request) is published on subject `safetysettings.upsert.click`, awaiting a response on `_INBOX.uHgt21IfmyJOZiwF3EyTv2.1`. But apparently the server never receives a response message.

I think the missing ` ->> [MSG safetysettings.upsert.click ...]` line after `MSG_PAYLOAD` indicates that there is no subscriber. Can you double check that Request/RequestAsync does not throw a NATSNoRespondersException?

**Comment by wilstoff** [comment]
If we don't have a listener, on the new version of Nats server don't we expect to get a NoResponderException immediately, at least that's what other tests have show us.  So if we get a NatsTimeoutException, then that would tell me the responder is failing to send the reply message (exceptions or whatever)?

**Comment by ColinSullivan1** [comment]
Yes, exactly.  If there's no responder present (no interest in the subject you requesting on), you should get a `NATSNoRespondersException`, which is a subclass of a timeout (for backward compatibility).

If you are actually timing out, you'll get a `NATSTimeoutException`.  This means the responder is connected and subscribed to your request subject, but is not responding.

**Comment by wilstoff** [comment]
We'll get back to you, i'm sure there is something we're doing silly in our responder then, but odd because we've vetted out a bunch of the responder's logic through other tests (that don't have UI threads) and unsure of where we messed up on replying.

**Comment by kharkins-23** [comment]
Thanks for all the replies, this can be closed. Turns out it was an issue with our requester sending something unexpected to our replier, and our replier not handling it. 

Thanks again!

**Comment by ColinSullivan1** [comment]
Absolutely!  Thanks letting us know.  Glad to hear you resolved the issue!

**Comment by wilstoff** [comment]
As a side question, if a client subscription callback handler does throw an exception, there's no handler on the connection we can trigger off to see that error? Seems like the code just catches the exception to avoid crashing the subscription, which is nice. My first thought was that the AsyncErrorEventHandler would have been raised on the connection, but perhaps that's only for nats errors and not our accidental exception throwing callback.

**Comment by ColinSullivan1** [comment]
True, the async error handler is only for NATS related errors/exceptions today.  I can see how the exception being swallowed could make it difficult to debug.  I think that'd be a good addition, and will open an issue to track that.  Thanks!
