### ISSUE TITLE
GA release date for JetStream

### ISSUE THREAD

**Issue by hitesheic** [nats-io/nats.net.v1#499]
Hi,

Just wanted to know, if there is any GA release is defined for NATS.Client JetStream?

Regards,
Hitesh Darji

**Comment by scottf** [comment]
This PR is in progress. https://github.com/nats-io/nats.net/pull/498
It needs a final pass at subscription handling and status management. This should be completed this week.  At that time it can be released.

**Comment by hitesheic** [comment]
Thanks for the update!

**Comment by scottf** [comment]
@hitesheic The 0.14.0 is released. Please try it out. https://www.nuget.org/packages/NATS.Client

**Comment by hitesheic** [comment]
Thanks a lot!
