### ISSUE TITLE
Just binding to an existing consumer now throws [SUB-90016] Existing consumer cannot be modified.

### ISSUE THREAD

**Issue by kleferbe** [nats-io/nats.net.v1#502]
In the current master when doing
```
   var subOptions = PushSubscribeOptions.BindTo(InStreamName, InConsumerName);
   var subscription = js.PushSubscribeAsync(InSubject, InQueueName, MessageHandler, false, subOptions);
```
PushSubscribeAsync throws an Exception: "[SUB-90016] Existing consumer cannot be modified."
I think using bind mode should relieve us from supplying a complete consumer configuration. All information is already present at the server.

And to go one step further with bind mode: 
Actually when using bind mode I whish I would not even have to supply `InSubject`, and `InQueueName` but it's not allowed to call `PushSubscribeAsync()` with `null` values.

**Comment by scottf** [comment]
Agreed, this is confusing. Does your existing consumer that you are binding to have queue setup? Can you show me the code that is creating the consumer.

**Comment by kleferbe** [comment]
thank you for taking this up, scott.

The consumer is set up with this consumer.json:
``` json
{
    "description": "Ingress Unitizer",
    "ack_policy": "explicit",
    "deliver_policy": "all",
    "deliver_subject": "_INBOX.ingressunitizer_47F8B36C",
    "deliver_group": "default",
    "durable_name": "ingressunitizer",
    "max_ack_pending": 65000,
    "max_deliver": 5,
    "replay_policy": "instant"
}
```
And this command: `./nats -s $NatsUrl --creds=pipeline.creds con add ingress-raw-from-eventhub --config ./consumer.json`

I'm not providing stuff like description when using PushSubscribeOptions.BindTo(InStreamName, InConsumerName); but it later checks, if these details match the info received by server lookup...

**Comment by scottf** [comment]
There must be a bug in the way I'm comparing the existing consumer configuration with what is "supplied" in the bind. I'll follow up

**Comment by scottf** [comment]
This is fixed in PR https://github.com/nats-io/nats.net/pull/503 The comparison of a default consumer to pre-made consumers was failing indicating a change was requested, when it was not.

**Comment by scottf** [comment]
This is fixed and is in the process of being released as 0.14.1

**Comment by scottf** [comment]
@nayanparegi There is code in progress to make this comparison more lenient. This is on top of the bug fix referenced here. Can you let me know what your consumer configuration looks like and I will make sure it's working.

**Comment by nayanparegi** [comment]
@scottf  I have reverted installation. Below is the configuration that I am using for stream:

`Configuration:

        Durable Name: XXX
         Description: XXX
    Delivery Subject: _INBOX.scpXcbKmre1RVDjhDw_sxa
      Filter Subject: X.XXX
      Deliver Policy: All
 Deliver Queue Group: XXXX
          Ack Policy: Explicit
            Ack Wait: 1m0s
       Replay Policy: Instant
     Max Ack Pending: 20,000
        Flow Control: false

Cluster Information:

                Name: nats
              Leader: nats-0
             Replica: nats-2, current, seen 0.06s ago
             Replica: nats-1, current, seen 0.06s ago

State:

   Last Delivered Message: Consumer sequence: 21,581 Stream sequence: 751,188 Last delivery: 16m6s ago
     Acknowledgment floor: Consumer sequence: 21,581 Stream sequence: 750,923 Last Ack: 16m6s ago
         Outstanding Acks: 0 out of maximum 20,000
     Redelivered Messages: 0
     Unprocessed Messages: 0
          Active Interest: Active using Queue Group XXX`

**Comment by scottf** [comment]
@nayanparegi I need the code version, the builder block would be just fine. For instance what are you setting for max ack pending. 20000 is no longer the default value, it has been changed to 1000. Either way, I've got a PR waiting for approval that should address this by being properly lenient, hopefully the release will be done tomorrow.

**Comment by scottf** [comment]
@nayanparegi can we also continue this conversation in #595
