### ISSUE TITLE
Update the documentation regarding jetstream according to its current status

### ISSUE THREAD

**Issue by VCuzmin** [nats-io/nats.net.v1#505]
Please update the documentation regarding jetstream. I know that jetstream has been released lately(alpha version) but in the documentation, there is the title as in the below image: 
![image](https://user-images.githubusercontent.com/40390118/140021383-7f6a2d52-f381-4831-a805-3863899d4a3b.png)

This could lead to confusion when it comes to using it. 

Thank you!

**Comment by scottf** [comment]
Doh! Fixed in PR https://github.com/nats-io/nats.net/pull/507
