### ISSUE TITLE
Permissions Violation for Publish does not throw an exception

### ISSUE THREAD

**Issue by Drew40B** [nats-io/nats.net.v1#525]
Steps to repro:
1) Create a user that has these permissions:
 CLIENT = {
    publish = { allow: ["sub.>"]}
    subscribe = "sub.>"
  }
 
  users = [
   {user: client,  password: ccc, permissions: $CLIENT}
    ]
    
 Run the following xUnit test and observe no exception is thrown
 ```
 [Theory]
        [InlineData("client", "ccc", "BAD!", true)]
        public void PublishPermission(string userName, string password, string subject, bool pass)
        {

            ConnectionFactory cf = new ConnectionFactory();

            var options = ConnectionFactory.GetDefaultOptions();
            options.User = userName;
            options.Password = password;

            using (var connection = cf.CreateConnection(options))
            {

            
                connection.Publish(subject, Encoding.UTF8.GetBytes("Hello"));

                var error = connection.LastError;

            }

        }
```

**Comment by Drew40B** [comment]
I forgot the add the corresponding nats log entry:

[1] 2021/12/17 18:05:17.268144 [ERR] 172.17.0.1:41262 - cid:10 - "v1.13.0:go:NATS CLI Version 0.0.28" - Publish Violation - User "client", Subject "aa"
[1] 2021/12/17 18:05:17.268468 [DBG] 172.17.0.1:41262 - cid:10 - "v1.13.0:go:NATS CLI Version 0.0.28" - Client connection closed: Client Closed

**Comment by scottf** [comment]
I'll look into this. At first glance, this is not a connection error, I would expect an exception to thrown.

**Comment by scottf** [comment]
I did a little digging. Since I'm most familiar with Java, I tried this with the Java client and it calls it's error handler to notify of error, which seems like a perfectly reasonable thing to do when no function return is expected. The question is then why isn't there similar behavior in the .NET client. I think it's fair to say that connection.LastError would not be set, since this is not a connection issue, but it does seem like there should be a call to the Error Event handler.
I'm pretty close to marking this as a bug to be fixed, but I want to run it by one of the guys on the team to see if there was an intentional reasons this was not done. Thanks for posting the issue @Drew40B, I'll comment again when I know what the plan is.

**Comment by tbeets** [comment]
Is the server's defensive close of the connection (which I believe is automatic when a client tries to do an unpermitted action) masking the publish violation error just before?  i.e. what would we expect `connection.LastError` to hold?

**Comment by scottf** [comment]
No. The violation comes across the wire. .NET just discards -ERR protocol messages where java surfaces them through the error listening mechanism

**Comment by ColinSullivan1** [comment]
This is a race condition between processing the error and closing the connection and Publish is non-blocking w/r/t publish errors.  If the client detects the closed connection first, it'll handle things as if the the connection was closed. If the client processes the error first, you'll get an async error notification if an async error handler is set and LastError would be set.

For this test, if you put a sleep or Flush() after the publish to allow the test time to process the error message, you should see LastEx set.

I don't believe the server will close the connection on a publish error, I suspect the connection is being closed by dispose when falling out of the using block.

**Comment by tbeets** [comment]
You're right @ColinSullivan1 , connection authentication errors give you the boot, but pub/sub authorization (permissions) errors leave the connection open.

**Comment by scottf** [comment]
I'll dig into this a little more, try the sleep.

**Comment by scottf** [comment]
@Drew40B Please see Colin's note. I added a Thread.Sleep(2000) after the publish and before reading LastError and saw the error.

**Comment by Drew40B** [comment]
I am designing a system that will have a high volume of message throughput I don't think sleeping is a viable option.  How expensive / reliable is the flush to avoid the race condition?

Alternatively, is there an another publish call that I can make that will guarantee the Nat server has received and processed the call?

**Comment by scottf** [comment]
So the sleep is just there because the example programs is ending and the connection is closing. Why are you publishing to the wrong subject anyway?

**Comment by Drew40B** [comment]
I am evaluating how nats client handles permission / publish errors.
