### ISSUE TITLE
Get NATSTimeoutException when executing first example code 

### ISSUE THREAD

**Issue by Tommy95271** [nats-io/nats.net.v1#534]
**Description**

I run the fist example in .NET page Basic Usage section `https://github.com/nats-io/nats.net#creating-a-nats-net-application`  in Visual Studio 2022 and .NET 6 console app, it always shut down the app in this line `Msg m = sSync.NextMessage(1000);` and throws an error `NATS.Client.NATSTimeoutException: 'Timeout occurred.'`

**Reproduction**

- Clone the code and build in Release mode
- Reference the dll in new .NET 6 console project
- Copy the Basic Usage section code and paste in Program.cs
- Press F5 to run

**Expected result**

See hello world in Microsoft Visual Studio Debug Console

**Actual result**

Program shuts down at `Msg m = sSync.NextMessage(1000);`

![image](https://user-images.githubusercontent.com/55481017/148179951-bd7496c3-c119-4ffc-b05c-4791558820b0.png)

**Comment by scottf** [comment]
There are no messages available on foo, that's why it times out. I would suggest starting with the samples https://github.com/nats-io/nats.net/tree/master/src/Samples

**Comment by scottf** [comment]
@Tommy95271 There are no messages available on foo, that's why it times out. I would suggest starting with the samples https://github.com/nats-io/nats.net/tree/master/src/Samples
