### ISSUE TITLE
Instrument the library so it can send observability data on demand

### ISSUE THREAD

**Issue by saboco** [nats-io/nats.net.v1#567]
## Feature Request
Instrument the library with dotnet activity api ([ActivitySource](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/extending-the-sdk/README.md#writing-own-instrumentation-library)) so it can be used to send observability data.

To be noted that normally there is no overhead if the client code does not explicitly add the source to be listen, and even there the overhead from the point of view of NATS.Client is minimal.

#### Use Case:
Use opentelemetry to have basic observability data like:
*Message received
*Message published

#### Proposed Change:
Instrument very lightly the Connection

#### Who Benefits From The Change(s)?
All community using NATS.net 

#### Alternative Approaches
[Activity Api](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/README.md#instrumenting-a-libraryapplication-with-net-activity-api) is the dotnet way to instrument a dotnet library, but there are also[ shims to use the OpenTelemetry API](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/README.md#instrumenting-using-opentelemetryapi-shim)

**Comment by scottf** [comment]
Not going to do.
