### ISSUE TITLE
Move from netstandard1.6 to netstandard2.0

### ISSUE THREAD

**Issue by caleblloyd** [nats-io/nats.net.v1#569]
Moving from `netstandard1.6` to `netstandard2.0` would open a significant number of APIs including [ClientWebSocket](https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocket?view=netstandard-2.0)

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

> .NET Standard 1.6 has 13,501 of the 37,118 available APIs.

> .NET Standard 2.0 has 32,638 of the 37,118 available APIs.

It would drop support for .NET Core 1.x, however maintenance ended on that [June 27, 2019](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)

**Comment by caleblloyd** [comment]
This issue is a pre-requisite for #383 and #407

**Comment by caleblloyd** [comment]
https://learn.microsoft.com/en-us/lifecycle/faq/dotnet-framework

> Support for .NET Framework 4.5.2, 4.6, and 4.6.1 ended on April 26, 2022. Customers and developers must have completed the in-place update to .NET Framework 4.6.2 or later by April 26, 2022 to continue receiving technical support and security updates.

.NET Framework 4.6.2 fully supports `netstandard2.0` so we can also drop support for `net46` and still support all of the .NET Framework versions that Microsoft officially supports

**Comment by scottf** [comment]
See V2 client
