### ISSUE TITLE
No responders are available for the request

### ISSUE THREAD

**Issue by m1stegmann** [nats-io/nats.net.v1#572]
We have a cluster with three pods and a stream with three replicas. 
Now, when we restart a pod and continue writing messages in the meantime, we briefly get the error message: "NATS.Client.NATSNoRespondersException: No responders are available for the request."

Apparently, this happens exactly when the pod is restarted and NATS determines that the stream of this pod is "outdated".
Shouldn't it be the case that if there are three replicas, one pod is allowed to fail and this does not cause a failure?

**Comment by scottf** [comment]
@m1stegmann Could you please ask this on our slack #jetstream channel

**Comment by scottf** [comment]
Closed no response.
