### ISSUE TITLE
Handle OCSP and CRL cert checks with option to ignore when unavailable

### ISSUE THREAD

**Issue by sspates** [nats-io/nats.net.v1#588]
## Feature Request
When doing validation of the certificates in authentication, allow through options the ability to validate the certificates using OCSP with failback to CRL.

Option for this feature should include:
Validation Order (e.g. CRL, OCSP, Fallback)
Custom Fallback
Timeouts for Http requests
Ability to Ignore Http Timeouts
Ability to Ignore specific Http Error codes (e.g. 404, 500, etc.)
Caching of OCSP/CRL for use as fallback when error codes are experienced. 

#### Use Case:
Checking for Revocation of certificates is a necessary feature for proper validation and security of certificates.  When validating signatures on authencation calls OCSP and CRL validation should be available.  In order to support offline handling, the fallback to prior responses and ignoring the failures when specific http codes are received is necessary to prevent invalid failures. 

#### Proposed Change:
Add the ability to perform OCSP and CRL validation as part of the Signature validation in JWT token validation. 

#### Who Benefits From The Change(s)?
Higher security for those who chose to use it. 

#### Alternative Approaches
Unknown

**Comment by scottf** [comment]
Looking into whether this is viable: https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.security.x509clientcertificateauthentication.revocationmode?view=netframework-4.8

**Comment by caleblloyd** [comment]
Looks like it is not available in .NET core and is only in the full framework?

**Comment by caleblloyd** [comment]
This appears to be the way to do it with .net core:

https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions.certificaterevocationcheckmode?view=net-6.0#system-net-security-sslclientauthenticationoptions-certificaterevocationcheckmode

**Comment by scottf** [comment]
Please see [PR #615 tls variations example](https://github.com/nats-io/nats.net/pull/615)

It demonstrates using setting the `CheckCertificateRevocation` Options flag and provides example code for manual verification indlucing some example usage of BouncyCastle
