### ISSUE TITLE
Error after upgrading to version 2.8.1 from 2.7.4 

### ISSUE THREAD

**Issue by nayanparegi** [nats-io/nats.net.v1#595]
I have upgraded NATS server to 2.8.1 whenever consumer restart even without any changes getting below error.

NATS.Client.NATSJetStreamClientException: [SUB-90016] Existing consumer cannot be modified

After I remove durable consumer and it starts working, but again if I restart it will throw same error.

**Comment by kozlovic** [comment]
I have transferred this issue to the nats.net repo since it looks like this is what you are using. Please check similar report here: https://github.com/nats-io/nats.net/issues/502

**Comment by nayanparegi** [comment]
Thanks

**Comment by kozlovic** [comment]
@nayanparegi The issue was already transferred, so I am not sure if you close this issue because it is resolved or because you thought you closed the issue reported against the server. Let me know and I will re-open this issue if the latter.

**Comment by scottf** [comment]
@nayanparegi @kozlovic This is a client issue. What version of the  Can you please show me the consumer configuration. Bet

**Comment by scottf** [comment]
@nayanparegi @kozlovic There is code in progress to make this comparison more lenient. Should be available early next week.

**Comment by nayanparegi** [comment]
> ported against the server. Let me know and I will re-open this issue if the latter.

It's not yet resolved, I thought it is transferred hence I closed it.

**Comment by scottf** [comment]
@nayanparegi Continue here instead of #502

**Comment by nayanparegi** [comment]
@scottf  below is sample code:
This is for durable:
```
var consumerConfigurationBuilder=ConsumerConfiguration.Builder().
            WithDescription($"{ServiceName}.{eventName}").
            WithAckWait(NATS.Client.Internals.Duration.OfSeconds(_ackTimeout)).
            WithFilterSubject($"XXXX.{eventName}").
            WithDeliverPolicy(DeliverPolicy.All);
if(_rateLimit!=null){
    consumerConfigurationBuilder=consumerConfigurationBuilder.WithRateLimit(_rateLimit);
}
if(_maxAckPending!=null){
    consumerConfigurationBuilder=consumerConfigurationBuilder.WithMaxAckPending(_maxAckPending);
}
var durableName=ServiceName +"_" + eventName;
if(eventName=="*"){
    durableName=ServiceName +"_" + "all";
}

var pushSubscribeOptionsWithDurable = PushSubscribeOptions.Builder().WithStream("XXXX")
        .WithDurable(durableName)
        .WithConfiguration(consumerConfigurationBuilder.Build())
        .Build();
var consumer = JetStream.PushSubscribeAsync("XXXX." + eventName, ServiceName, (msg, args) =>
```

This is for non durable:
```
var consumerConfigurationBuilder=ConsumerConfiguration.Builder().
            WithDescription($"{ServiceName}.{eventName}").
            WithAckWait(NATS.Client.Internals.Duration.OfSeconds(_ackTimeout)).
            WithFilterSubject($"XXXX.{eventName}").
            WithDeliverPolicy(DeliverPolicy.All);
if(_rateLimit!=null){
    consumerConfigurationBuilder=consumerConfigurationBuilder.WithRateLimit(_rateLimit);
}
if(_maxAckPending!=null){
    consumerConfigurationBuilder=consumerConfigurationBuilder.WithMaxAckPending(_maxAckPending);
}

var pushSubscribeOptions = PushSubscribeOptions.Builder().WithStream("XXXXX")
            .WithConfiguration(consumerConfigurationBuilder.Build())
            .Build();

var consumer = JetStream.PushSubscribeAsync("XXXXX." + eventName, (msg, args) =>
 {
```

Please let me know if I need to do any changes in above for the issue.

**Comment by scottf** [comment]
@nayanparegi I have made a release. https://github.com/nats-io/nats.net/releases/tag/0.14.6 Not sure how fast it propagates https://www.nuget.org/packages/NATS.Client/0.14.6

**Comment by nayanparegi** [comment]
Thanks, I will try it out tomorrow.
