### ISSUE TITLE
JetStream pull subscription does not respect max wait time

### ISSUE THREAD

**Issue by BalazsArva** [nats-io/nats.net.v1#598]
## Defect

Hi everyone,

While working with NATS using JetStream, I noticed that the pull subscription API handles the max wait time parameter passed to the Fetch method oddly. The method's summary tells that this parameter controls _"The maximum time to wait for the first message."_. However, it appears that this timeout is not really respected. I've included the example code down below, using 4 different values for the max wait time.

To force the issue to happen, we also need to be aware of the MaxAckWaitDurationInMillis, during which the server won't hand out the same message to a consumer. This is set to a constant 6000 ms in the example. This value is used as a reference for the max wait time as well:

When max wait time = MaxAckWaitDurationInMillis (=6k ms), the test passes, and the test output says the following, which seems fine:

    Standard Output: 
    Using max poll: 6000 ms, ack wait: 6000 ms
    Published 1. msg. Elapsed: 48 ms
    Published 2. msg. Elapsed: 49 ms
    Fetched messages for the 1st time. Elapsed: 565 ms
    Fetched messages for the 2nd time. Elapsed: 7092 ms

When max wait time = 2 * MaxAckWaitDurationInMillis (=12k ms), the test passes, however, note how the last output line says that the second fetch took 12.5k ms. This is odd as the server should hand out the previously handed out messages after 6 seconds has passed. While the max wait time is 12k sec, this could be fine including latency and whatnot, since the fetch batch size is 10, the operation may take that long to allow the batch to be filled. What's strange to me is that in this case, it appears that the entirety of the wait time is occupied to potentially get more messages if they existed, but the same thing does not seem to occur while fetching the messages for the firs time. There, despite using the same batch size (10), the batch is returned after just ~500ms.

    Standard Output: 
    Using max poll: 12000 ms, ack wait: 6000 ms
    Published 1. msg. Elapsed: 0 ms
    Published 2. msg. Elapsed: 1 ms
    Fetched messages for the 1st time. Elapsed: 512 ms
    Fetched messages for the 2nd time. Elapsed: 13025 ms

In the third case, when max wait time = MaxAckWaitDurationInMillis / 2 (=3k ms), the test just passes, but the wait period is odd here as well. Despite maximizing the wait time at 3k ms, we only get the batch back after 6k ms, double the allowed maximum:

    Standard Output: 
    Using max poll: 3000 ms, ack wait: 6000 ms
    Published 1. msg. Elapsed: 1 ms
    Published 2. msg. Elapsed: 2 ms
    Fetched messages for the 1st time. Elapsed: 508 ms
    Fetched messages for the 2nd time. Elapsed: 6516 ms

And finally, in the fourth case, we use max wait time = MaxAckWaitDurationInMillis / 2 - 300 (=2700 ms). Here, the test fails, because the wait time is noticeably shorter than the MaxAckWaitDurationInMillis, so the server will not hand out the messages reserved by the first fetch call. Despite that, the second fetch still takes 3 times the maximum allowed time to not even return any items:

    Standard Output: 
    Using max poll: 2700 ms, ack wait: 6000 ms
    Published 1. msg. Elapsed: 0 ms
    Published 2. msg. Elapsed: 1 ms
    Fetched messages for the 1st time. Elapsed: 516 ms
    Fetched messages for the 2nd time. Elapsed: 8625 ms

Can someone please clarify what's going on, am I doing something wrong or misunderstanding something, or is this an issue with the library? From what I remember from browsing the source it appeared as if the max wait time was once used for capping the actual polling, then again separately when reading from the response that's being read back from the server, perhaps this is how they add up like this.

<hr/>

### Code to reproduce:

Project:

    <Project Sdk="Microsoft.NET.Sdk">
    
      <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
    
        <IsPackable>false</IsPackable>
      </PropertyGroup>
    
      <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
        <PackageReference Include="NUnit" Version="3.13.2" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.0.0" />
        <PackageReference Include="coverlet.collector" Version="3.1.0" />
        <PackageReference Include="NATS.Client" Version="0.14.5" />
      </ItemGroup>
    
    </Project>

Test file for repro:

    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Linq;
    using System.Threading.Tasks;
    using NATS.Client;
    using NATS.Client.JetStream;
    using NUnit.Framework;
    
    namespace NatsRepro.Tests
    {
        public class Tests
        {
            private const string StreamName = "IssueReproStream";
            private const string SubjectName = "IssueReproSubject";
            private const string ConsumerName = "IssueReproConsumer";
    
            private const int FetchBatchSize = 10;
    
            private const int MaxAckWaitDurationInMillis = 6000;
    
            private IJetStream jetStreamContext = default!;
            private IJetStreamPullSubscription subscriber = default!;
    
            [SetUp]
            public void Setup()
            {
                var connectionFactory = new ConnectionFactory();
                var connection = connectionFactory.CreateConnection();
    
                // Start fresh
                DeleteStreamIfExists(connection);
                InitializeJetStream(connection);
    
                jetStreamContext = connection.CreateJetStreamContext();
                subscriber = CreatePullSubscription(jetStreamContext);
            }
    
            [TestCase(MaxAckWaitDurationInMillis)]
            [TestCase(MaxAckWaitDurationInMillis * 2)]
            [TestCase(MaxAckWaitDurationInMillis / 2)]
            [TestCase(MaxAckWaitDurationInMillis / 2 - 300)]
            public async Task Test1(int maxPollDurationInMillis)
            {
                TestContext.WriteLine($"Using max poll: {maxPollDurationInMillis} ms, ack wait: {MaxAckWaitDurationInMillis} ms");
    
                var sw = Stopwatch.StartNew();
    
                var result1 = await jetStreamContext.PublishAsync(
                    new Msg(SubjectName, new byte[] { 1 }),
                    PublishOptions.Builder().WithStream(StreamName).Build());
    
                TestContext.WriteLine($"Published 1. msg. Elapsed: {sw.ElapsedMilliseconds} ms");
    
                var result2 = await jetStreamContext.PublishAsync(
                    new Msg(SubjectName, new byte[] { 2 }),
                    PublishOptions.Builder().WithStream(StreamName).Build());
    
                TestContext.WriteLine($"Published 2. msg. Elapsed: {sw.ElapsedMilliseconds} ms");
    
                // For failing fast
                Assert.IsFalse(result1.HasError);
                Assert.IsFalse(result2.HasError);
    
                var messagesBeforeAck = FetchMessages(FetchBatchSize, maxPollDurationInMillis);
                Assert.AreEqual(2, messagesBeforeAck.Count);
    
                TestContext.WriteLine($"Fetched messages for the 1st time. Elapsed: {sw.ElapsedMilliseconds} ms");
    
                var messagesAfterAck = FetchMessages(FetchBatchSize, maxPollDurationInMillis);
    
                TestContext.WriteLine($"Fetched messages for the 2nd time. Elapsed: {sw.ElapsedMilliseconds} ms");
    
                Assert.AreEqual(2, messagesAfterAck.Count);
                CollectionAssert.AreEquivalent(messagesAfterAck[0].Data, new byte[] { 1 });
                CollectionAssert.AreEquivalent(messagesAfterAck[1].Data, new byte[] { 2 });
            }
    
            private IList<Msg> FetchMessages(int batchSize, int maxPollDuration)
            {
                return subscriber
                    .Fetch(batchSize, maxPollDuration)
                    .ToList();
            }
    
            private void DeleteStreamIfExists(IConnection connection)
            {
                try
                {
                    connection.CreateJetStreamManagementContext().DeleteStream(StreamName);
                }
                catch
                {
                    return;
                }
            }
    
            private void InitializeJetStream(IConnection connection)
            {
                var jetStreamManagementContext = connection.CreateJetStreamManagementContext();
    
                try
                {
                    var streamInfo = jetStreamManagementContext.GetStreamInfo(StreamName);
                }
                catch (NATSJetStreamException e) when (e.ErrorCode == 404)
                {
                    var streamConfig = new StreamConfiguration.StreamConfigurationBuilder()
                        .WithName(StreamName)
                        .WithSubjects(SubjectName)
                        .WithStorageType(StorageType.File)
                        .Build();
    
                    jetStreamManagementContext.AddStream(streamConfig);
                }
            }
    
            private IJetStreamPullSubscription CreatePullSubscription(IJetStream jetStreamContext)
            {
                var consumerConfiguration = ConsumerConfiguration
                    .Builder()
                    .WithAckWait(MaxAckWaitDurationInMillis)
                    .WithAckPolicy(AckPolicy.Explicit)
                    .Build();
    
                var pullSubscribeOptions = PullSubscribeOptions
                    .Builder()
                    .WithConfiguration(consumerConfiguration)
                    .WithDurable(ConsumerName)
                    .WithStream(StreamName)
                    .Build();
    
                var subscription = jetStreamContext.PullSubscribe(SubjectName, pullSubscribeOptions);
    
                return subscription;
            }
        }
    }

#### Versions of `NATS.Client` and `nats-server`:

- Client: 0.14.5
- Server: Docker Desktop, nats:2.8.2-linux, sha256:d7022e467f53812285667fd004413e8cb15920efbb01d1d0f7c4194a2e084959

#### OS/Container environment:

Docker Desktop on Win10, Linux containers in WSL, versions above

#### Steps or code to reproduce the issue:

See included code

#### Expected result:

The Fetch call from start to finish should not take much longer than the specified maximum wait time.

#### Actual result:

Maximum wait time is not respected, it is occasionally a few times as much as allowed.

**Comment by scottf** [comment]
The maxWaitMillis technically refers the the time used for polling. The rest is processing overhead but... If you look at the code starting at [JetStreamPullSubscription.cs Line 77](https://github.com/nats-io/nats.net/blob/master/src/NATS.Client/JetStream/JetStreamPullSubscription.cs#L77) you can see that there is a stopwatch in place that will take into account some of the processing overhead so the intent is try to keep the entire processing within the timeout.

Also, I noticed in your code that you include several costly things in your timing and counted them against the Fetch call, including multiple outputs, multiple other overhead like function calls and the ToList in your timing as well.

What happens when you do this code, that limits the timing to exactly only the fetch itself. I expect there to be some overhead, but nowhere near the times you show.

```
private IList<Msg> FetchMessages(int batchSize, int maxPollDuration)
{
    var sw = Stopwatch.StartNew();
    IList<Msg> list = subscriber.Fetch(batchSize, maxPollDuration);
    long elapsed = sw.ElapsedMilliseconds
    TestContext.WriteLine($"Fetched messages elapsed: {elapsed} ms");
    return list;
}
```

**Comment by BalazsArva** [comment]
@scottf Thanks for your quick response. Yes, I did just use one stopwatch only, however, I considered the time that elapsed prior the last fetch when evaluated the results. I checked the fetch call in isolation as well, but the results are similar:

    Standard Output: 
    Using max poll: 12000 ms, ack wait: 6000 ms
    Fetched messages elapsed: 504 ms
    Fetched messages elapsed: 12517 ms
    
    Standard Output: 
    Using max poll: 2700 ms, ack wait: 6000 ms
    Fetched messages elapsed: 513 ms
    Fetched messages elapsed: 8095 ms
    
    Standard Output: 
    Using max poll: 3000 ms, ack wait: 6000 ms
    Fetched messages elapsed: 507 ms
    Fetched messages elapsed: 5998 ms
    
    Standard Output: 
    Using max poll: 6000 ms, ack wait: 6000 ms
    Fetched messages elapsed: 516 ms
    Fetched messages elapsed: 6517 ms

**Comment by scottf** [comment]
I don't see any issue. Here is my unit test:
```
private const int MaxAckWaitDurationInMillis = 6000;
private const int FetchBatchSize = 10;

[Theory]
[InlineData(MaxAckWaitDurationInMillis)]
[InlineData(MaxAckWaitDurationInMillis * 2)]
[InlineData(MaxAckWaitDurationInMillis / 2)]
[InlineData(MaxAckWaitDurationInMillis / 2 - 300)]
public void Test598(int maxPollDurationInMillis)
{
    Context.RunInJsServer(c =>
    {
        // create the stream.
        CreateDefaultTestStream(c);

        // Create our JetStream context.
        IJetStream jetStreamContext = c.CreateJetStreamContext();

        jetStreamContext.Publish(SUBJECT, new byte[] { 1 });
        
        var consumerConfiguration = ConsumerConfiguration
            .Builder()
            .WithAckWait(MaxAckWaitDurationInMillis)
            .WithAckPolicy(AckPolicy.Explicit)
            .Build();

        var pullSubscribeOptions = PullSubscribeOptions
            .Builder()
            .WithConfiguration(consumerConfiguration)
            .WithDurable(DURABLE)
            .WithStream(STREAM)
            .Build();

        var subscription = jetStreamContext.PullSubscribe(SUBJECT, pullSubscribeOptions);

        var sw = Stopwatch.StartNew();
        IList<Msg> list = subscription.Fetch(FetchBatchSize, maxPollDurationInMillis);
        long elapsed = sw.ElapsedMilliseconds;
        output.WriteLine($"maxPollDurationInMillis {maxPollDurationInMillis} | Fetched messages elapsed: {elapsed} ms | message count {list.Count}");
    });
}
```

Here are the results:
```
maxPollDurationInMillis 2700 | Fetched messages elapsed: 2705 ms | message count 1
maxPollDurationInMillis 3000 | Fetched messages elapsed: 3008 ms | message count 1
maxPollDurationInMillis 6000 | Fetched messages elapsed: 6007 ms | message count 1
maxPollDurationInMillis 12000 | Fetched messages elapsed: 12010 ms | message count 2
```

**Comment by scottf** [comment]
I do want to make a note, you can see that in the test with maxPollDurationInMillis 12000, the server redelivered the message because it had not received an ack within the Ack Wait window (12000 vs 6000). This is the correct behavior and shows the importance of setting the Ack Wait window properly to account for the fetch time and the time you will need to process the message before acking it. I think the default server ack wait time is 30 seconds (default being if you don't set it in your consumer config)
