### ISSUE TITLE
nuget package?

### ISSUE THREAD

**Issue by skrusty** [nats-io/nats.net.v1#6]
Have you considered adding a pre-built package to nuget?

https://www.nuget.org

**Comment by ColinSullivan1** [comment]
Ben,

Thanks for the suggestion!  It'd certainly enhance the .NET user experience
for nuget users, and is something we should think about.

What do you envision the prebuilt package including?

Thanks,
Colin

On Mon, Nov 9, 2015 at 8:36 AM, Ben Merrills notifications@github.com
wrote:

> Have you considered adding a pre-built package to nuget?
> 
> https://www.nuget.org
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nats-io/csnats/issues/6.

## 

_Colin Sullivan_ | Principal Engineer
colin.sullivan@apcera.com brian@apcera.com  | @ColinSullivan01

**Comment by skrusty** [comment]
Just the .NET client library and of course any dependencies (looks like there aren't any though).

**Comment by ColinSullivan1** [comment]
Ben,

This is a great idea.  However, we should probably wait a little while
until we get more feedback and the C# client is beta, in case there are API
changes, etc.

Thanks,
Colin

On Mon, Nov 9, 2015 at 10:06 AM, Ben Merrills notifications@github.com
wrote:

> Just the .NET client library and of course any dependencies (if there are
> any).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nats-io/csnats/issues/6#issuecomment-155126800.

## 

_Colin Sullivan_ | Principal Engineer
colin.sullivan@apcera.com brian@apcera.com  | @ColinSullivan01

**Comment by skrusty** [comment]
That's fine, although nuget does support semantic visioning with lables like alpha or beta, so it's easy to exclude anything that's not ready for production. (see https://docs.nuget.org/create/versioning)

My only thought is, it's an easy route to adoption, and will maybe increase the potential audience of the client for feedback etc.

Either way, nice to see more .net adoption and a few people I know will be pushing me to move from RMQ to nats now there's a .NET client :D

**Comment by ColinSullivan1** [comment]
Ben,

Agreed -  I'll work on getting a package up on nuget soon.  

That's great to hear you are moving toward NATS with the .NET client!  

Any feedback would certainly be appreciated.

Thanks,
Colin

**Comment by ColinSullivan1** [comment]
Ben, 

Here you go - would you mind giving it a go?

https://www.nuget.org/packages/NATS.Client/0.2.1.1

Thanks,
Colin

**Comment by skrusty** [comment]
Will check it out in a short while, cheers! :)

**Comment by ColinSullivan1** [comment]
Ben, thanks again for bringing this up!   It has already been downloaded a number of times.  Look good to close the issue?

**Comment by skrusty** [comment]
Glad I could contribute something so simple :) Good luck with the project.
