### ISSUE TITLE
Unable to create an ephemeral pull consumer

### ISSUE THREAD

**Issue by robertmircea** [nats-io/nats.net.v1#608]
## Defect

I am trying to create a pull subscription with ephemeral consumer using the following code:
```
var cc = ConsumerConfiguration.Builder()
    .WithMaxAckPending(20)
    .WithAckWait(Duration.OfSeconds(40))
    .WithMaxDeliver(1)
    .WithReplayPolicy(ReplayPolicy.Instant)
    .WithFilterSubject("auditevents")
    .Build();
jetStreamManagementContext.AddOrUpdateConsumer("auditevents", cc);
```
The `JetStreamManagement.AddOrUpdateConsumer` always verifies if `Durable` name is set and it is impossible to create an ephemeral consumer using any other method from JetStreamManagement.

```
public ConsumerInfo AddOrUpdateConsumer(
  string streamName,
  ConsumerConfiguration config)
{
  Validator.ValidateStreamName(streamName, true);
  Validator.ValidateNotNull((object) config, nameof (config));
  Validator.ValidateNotNull(config.Durable, "Durable");
  return this.AddOrUpdateConsumerInternal(streamName, config);
}
```

#### Versions of `NATS.Client` and `nats-server`:
Client: 0.14.6
Server: 2.8.4

#### OS/Container environment:
MacOs Monterey

#### Expected result:

Possibility to create a Jetstream pull subscription with ephemeral consumer.

#### Actual result:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'Durable')
   at NATS.Client.Internals.Validator.ValidateNotNull(String s, String fieldName)
   at NATS.Client.JetStream.JetStreamManagement.AddOrUpdateConsumer(String streamName, ConsumerConfiguration config)
```

**Comment by scottf** [comment]
@robertmircea I'm waiting for this PR to be merged (https://github.com/nats-io/nats.net/pull/605), then you will be able to create ephemeral pulls.

**Comment by scottf** [comment]
This will go with the next release.

**Comment by robertmircea** [comment]
Any ETA on next library release?

**Comment by scottf** [comment]
0.14.7 has been released.

**Comment by robertmircea** [comment]
I've upgraded to 0.14.7. I am sorry but it is still failing with the same error as described initially in 0.14.6: AddOrUpdateConsumer verifies if "Durable" field is set when trying to create an ephemeral consumer.

This line part of AddOrUpdateConsumer throws:
```
Validator.ValidateNotNull(config.Durable, "Durable");
```

**Comment by scottf** [comment]
Ephemeral consumers cannot be created ahead of time using management, they can only be created during the subscribe call. Please see this example and comment out the durable: https://github.com/nats-io/nats.net/blob/master/src/Samples/JetStreamPullSubBatchSize/JetStreamPullSubBatchSize.cs
