### ISSUE TITLE
Passwords with special chars do not work

### ISSUE THREAD

**Issue by sylr** [nats-io/nats.net.v1#630]
## Defect

Password: `Rmwuukd0QsJI^RMkFGHz1J7vjz0A*27oCA#j6!WYf#`
URL: `tls://user:Rmwuukd0QsJI%5ERMkFGHz1J7vjz0A%2A27oCA%23j6%21WYf%23@nats-euc1a-01.:4222,tls://user:Rmwuukd0QsJI%5ERMkFGHz1J7vjz0A%2A27oCA%23j6%21WYf%23@nats-euc1b-02:4222`

This Connection String works using the nats.go lib and the nats cli but does not work using the nats.net lib.

**Comment by scottf** [comment]
@sylr Thank you for the bug report, I will be fixing this in the next day or so, I'll let you know when it's ready.

**Comment by scottf** [comment]
https://github.com/nats-io/nats-architecture-and-design/issues/123
