### ISSUE TITLE
Jetstream PublishSyncInternal does not timeout

### ISSUE THREAD

**Issue by jlumsden-mts** [nats-io/nats.net.v1#641]
Noticed some inconsistency between Publish and PublishAsync when testing with MaxReconnects = Forever

If you call Publish (synchronous) and your connection is down then it blocks forever on Conn.Request() as no timeout passed in even though it is supported.
https://github.com/nats-io/nats.net/blob/9db4db4de740195ac6378f98e7de44954719abc3/src/NATS.Client/JetStream/JetStream.cs#L89

However PublishAsync does timeout correctly based on the options provided and you don't end up waiting forever for it to fail.
https://github.com/nats-io/nats.net/blob/9db4db4de740195ac6378f98e7de44954719abc3/src/NATS.Client/JetStream/JetStream.cs#L103

Happy to put in a PR for this

**Comment by scottf** [comment]
Yes I will happily review a PR. Please make sure your code is signed.

**Comment by scottf** [comment]
@jlumsden-mts Hey just wanted to let you know I haven't forgotten about these, I've jsut been out of office for a personal issue.

**Comment by jlumsden-mts** [comment]
No problem @scottf, no huge rush for me, all the best with your personal issue.

**Comment by scottf** [comment]
Fixed in https://github.com/nats-io/nats.net/pull/642
