### ISSUE TITLE
Wrong error message when using ordered consumer, having set AckPolicy other than None

### ISSUE THREAD

**Issue by baltie** [nats-io/nats.net.v1#648]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [X] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `NATS.Client` and `nats-server`:
NATS.Client version 0.14.8

#### OS/Container environment:
Not relevant

#### Steps or code to reproduce the issue:

```cs
ConsumerConfiguration consumerConfiguration = ConsumerConfiguration.Builder()
    .WithAckPolicy(AckPolicy.Explicit)
    .Build();
PushSubscribeOptions options = PushSubscribeOptions.Builder()
    .WithConfiguration(consumerConfiguration)
    .WithOrdered(true)
    .Build();
```

#### Expected result:
The error message clearly states that AckPolicy must be None.

#### Actual result:
The error message states "[SO-90108] Deliver subject is not allowed with an ordered consumer." It is the right error code, I think, but the wrong message.

Also, the summary for the PushSubscribeOptions.PushSubscribeOptionsBuilder.WithOrdered method states "FOR FUTURE BEHAVIOR. TODO / NOT YET USED". Is this still the case? Because I really want to use it.. 😃

**Comment by scottf** [comment]
@baltie Thank you for the report, fixing here: https://github.com/nats-io/nats.net/pull/652 It was just a text issue. I also made sure the documentation was up to date.
