### ISSUE TITLE
Option to connect via TLS (start on TLS connection rather than an upgrade)

### ISSUE THREAD

**Issue by rbinder-vg** [nats-io/nats.net.v1#658]
#### Use Case:

I would like to use a TLS termination reverse proxy. At the moment i can't set a option to tell the client to use TLS right from the beginning. 

See:
- https://github.com/nats-io/nats-server/issues/291 
- https://docs.nats.io/running-a-nats-service/configuration/securing_nats/tls#tls-terminating-reverse-proxies

#### Proposed Change:

Provide a new option to start on TLS connection

#### Who Benefits From The Change(s)?

Those who use TLS termination reverse proxy

#### Alternative Approaches

Support Websockets

**Comment by caleblloyd** [comment]
Implemented in #767
