### ISSUE TITLE
When is NATSNoRespondersException thrown other than when the Stream/Subject is not existing ? 

### ISSUE THREAD

**Issue by andronachev** [nats-io/nats.net.v1#752]
Hello, 

**TL;DR**:  we get NATSNoRespondersException on the productive environment, but the Stream,Subject and Consumers (subscriptions) are properly setup so question is: when/why would this exception be raised for other reasons ? Not reproducible locally unless Stream does not exist. 

We are facing an issue only on the prodcutive environment and I am not able to reproduce it. We get thousands of NATSNoRespondersException on Publishing a message to jetstream. 

Exception is thrown when calling IJetStream.   Task<PublishAck> PublishAsync(string subject, byte[] data);  method. 

So far we are handling this exception on purpose, in order to **upsert** the Stream and Subject on the server, to achieve kind of a "self configuring at runtime" of our publishers and subscribers on the NATS JetStream. 

However this spamming of NATSNoRespondersException  is happenign after the Stream exists, the Subject exists, so something else is causing this exception adn I have no idea what: 

- is it a lack of consumers defined on the server for the Subject ? no, tested that on localhost and anyway there is the consumer on the server in prod, I checked 
- too many concurrent publishes ? not sure, but on localhost I tested with 3 nested parallel foreaches of 1000, 37 and 25 items respectively so we can do the math how many publish and subscribe that is to the same stream :D : result is: no problem 

So what other scenarios may be causing teh NATSNoRespondersException ? 

No logs or error logs of any kind on the JetStream docker pod: 

![image](https://user-images.githubusercontent.com/16139612/227180838-474d0a53-1269-497b-a74c-fdb058160286.png)

Thoughts ?

**Comment by andronachev** [comment]
What I don't understand, is that I see in this pull request when this exception was introduced in NATS.NET, it says that it's thrown when "there are no subscribes" : https://github.com/nats-io/nats.net/pull/413  

However, I am testing locally with a single stream and 600 subjects to it, and thousands of parallel publishes on these subjects and the stream has zero consumers on the server (durable or ephemeral, no type of consumer at all). Did not call subscribe on this stream or any subject. And there is no exception. The messages are stored on the nats server (the stream is configured with File retention... until delivery) 

![image](https://user-images.githubusercontent.com/16139612/227193109-4f27f42b-2b51-45aa-b090-c89f10062a65.png)

**Comment by scottf** [comment]
So there are 2 cases where you get no responders.
1. When you make a core request and there are no repliers listening to the subject.
2. When you JetStream publish to a subject that does not exist. Consider that  JS Publish is actually a core request where the server/subject is the replier.
