### ISSUE TITLE
Improve performance of the Request API

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.net.v1#78]
Look into enhancing performance of the Connection.Request API.
- Improve latency in the benchmark through usage of a synchronous subscription when replying.
- Replace calls to the public API with directly writing the protocol commands to the write buffer.  This reduces contention in a number of ways, primarily through eliminating unnecessary kicks to the flusher thread.
- Evaluate a "soft" flush - flushing the write buffer without a ping.

Based on #73.

**Comment by dotnetchris** [comment]
I saw this project on The Morning Brew, just read over the readme and was going to create an issue but this seems fitting enough to stick here. I can split it out to a different issue if you think it deserves to be elsewhere

I saw the default serializer is the BinaryFormatter, this is just awfully slow. I also believe they killed the BinaryFormatter in regards to .NET Core (.NET Standard? i don't even what things are named anymore they've changed it so many times). 

In order of preference, the reference and default implementation for serialization should be: [JIL](https://github.com/kevin-montrose/Jil), [Microsoft Bond](https://microsoft.github.io/bond/why_bond.html), or [Protobuf.NET](https://github.com/mgravell/protobuf-net)

**Comment by ColinSullivan1** [comment]
@dotnetchris Thanks!  Much appreciated!  I agree, the BinaryFormatter should probably go, and it does seem to have been killed (rightfully so).  We're trying to maintain 4.0 code compatibility for legacy applications, but a re-evaluation of encoding strategies in the client is certainly due.  As to minimize direct dependencies on third party components (holding to the NATS tenet of simplicity), I'm wondering if it'd be best to include examples that use these in an IEncodedConn, and move the BinaryFormatter out...

**Comment by dotnetchris** [comment]
It would be really easy to provide a series of nuget packages: NATS.Client.JIL, NATS.Client.Bond, NATS.Client.Protobuf that each depend on NATS.Client and the respective serializer.

That have out of box implementations ready to consume any or each of those encoders.

I still will stress that i believe you must be opinionated out of box since unopinionated doesn't provide any path forward given the end of life to the BinaryFormatter. I believe all of those projects are compatible with .NET 4.0, some of them might even be compatible as low as 2.0 or 3.5

**Comment by ColinSullivan1** [comment]
The BinaryFormatter will be deprecated moving forward.  Layering implementations of encoders on top of core NATS is a nice approach and we can certainly look into that.  Also, we'll certainly accept user contributions in that area as well. ;)

**Comment by ColinSullivan1** [comment]
Request/Reply performance issues were mitigated with #106, but leaving this open for for now.

**Comment by ColinSullivan1** [comment]
Closing this; request reply will be further evaluated in the next performance pass.
