### ISSUE TITLE
Basic auth string not handling non standard chars

### ISSUE THREAD

**Issue by danielwertheim** [nats-io/nats.net.v1#81]
When trying to pass credentials via URL, `nats://user:pwd@ubuntu01:4223`

you don't seem to handle passwords that contains e.g. "@".

Tried switching for %40, did not work either.

**Comment by ColinSullivan1** [comment]
@danielwertheim Thank for opening this issue.  I did look into it, some changes will likely be coming to support usernames/passwords related to auto-discovery.  Alongside those changes, we'll provide extended support for passwords that will cover this.  I'll keep this issue up to date.
