### ISSUE TITLE
Jetstream: Receiving duplicate message retries

### ISSUE THREAD

**Issue by jbasants** [nats-io/nats.net.v1#812]
### What version were you using?

**nats-server**
Version:  2.9.21
Git:      [b2e7725]

**nats.net**
1.0.8

### What environment was the server running in?

Laptop with Windows 10 Enterprise x64 21H1
Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz   2.71 GHz
32.0 GB RAM

### Is this defect reproducible?

The issue happens when there are re-deliveries of NATS messages sent to a Jetstream stream. We reproduce this by connecting 16 clients to the same Jetstream consumer and then sending **once** 3 messages to the stream topic. The messages are never acknowledged, so they are re-sent by the server after the ACK timeout. After some time, we can see the same message appearing in two different clients, as you can see in the image. Each line color represents a different client. The message format is:

`[consumer id]<timestamp> message (info)`

![nats_cur](https://github.com/nats-io/nats.net/assets/91270446/5f547ec1-a06a-4f25-b0bd-af3d6036f9a0)

We found that the `NumDelivered` metadata property is always one when there is a repeated message.

We've attached the client code we are using. The probability of occurrence is reduced by increasing the `Fetch` command timeout.

We were able to reproduce the effect in three different machines, using the same versions of nats-server and nats.net. This also occurs if the clients are in separate processes.

 This is most likely a server issue. Nevertheless, we opened the issue here as we found this using the .NET client, so we leave the full troubleshooting to you.

We also tested this with acks (with a background producer that keeps sending unique messages), but no duplicates were found.

[NatsEventsConsumer.zip](https://github.com/nats-io/nats.net/files/12465586/NatsEventsConsumer.zip)

### Given the capability you are leveraging, describe your expectation?

We expect that each message is only delivered to one client at a time. This way, we don't have two replicas processing the same message, if retries occur.

### Given the expectation, what is the defect you are observing?

The same message is sent to two different clients.

**Comment by scottf** [comment]
What are the consumer configs for these consumers? Are they pull or push consumers? Are they durable or named? If they are push are they queue consumers (share the same deliver group)? Is your output showing the stream sequence or the consumer sequence?

**Comment by jbasants** [comment]
They are durable pull consumers. The consumers are created also using the .NET client, using this code, which you can find in the .NET project attached to the original message:

```
consumer1Configuration = ConsumerConfiguration.Builder()
           .WithDurable(Consumer1Name)
            
            .WithDeliverPolicy(DeliverPolicy.All)
            .WithAckPolicy(AckPolicy.Explicit)
            .WithAckWait(Duration.OfSeconds(15))
            .WithReplayPolicy(ReplayPolicy.Instant)
            .WithMaxDeliver(-1)
            .WithHeadersOnly(false)
            .WithBackoff(Array.Empty<long>())
            
            .Build();
```

We use sync pull subscriptions, which keep asking the nats-server for messages with a 20ms `Fetch` timeout.
The `Seq` in the output shows the stream sequence

**Comment by scottf** [comment]
By `[consumer id]` there are 9 different consumers. Do they all have unique names or are you subscribing to the same consumer repeatedly?

**Comment by scottf** [comment]
Also, you may want to look into simplification. We have endless varieties of pull. `iterate` where you just keep doing next and `consume` where you provide a MessageHandler. There is also the simplification version of `fetch` which is more like the old iterate as it does not block until the entire batch is finished.

Start here with the Migration Example: https://natsbyexample.com/examples/jetstream/api-migration/java
And continue here with more examples in the client repo: https://github.com/nats-io/nats.java/tree/main/src/examples/java/io/nats/examples/jetstream/simple
ContextExample.java
FetchBytesExample.java
FetchMessagesExample.java
IterableConsumerExample.java
MessageConsumerExample.java
NextExample.java

**Comment by jbasants** [comment]
> By `[consumer id]` there are 9 different consumers. Do they all have unique names or are you subscribing to the same consumer repeatedly?

`[consumer id]` is misleading, it really should say `[client id]`. They all use the same durable consumer. So, just to be clear, there are 16 client connections, 1 durable consumer, and only 3 messages. The messages are never ACKed, so they keep being resent by the server.

We will look into the simplified API, but this API uses the same underlying mechanism, right?

**Comment by scottf** [comment]
I think I see the issue. I followed one sequence in your data. It gets resent every 15 seconds, matching your ack wait. And yes it gets sent to different _instances_ of the consumer. This is also correct. When a message is redelivered, it is redelivered to the _consumer_, not a specific instance. The server doesn't track which exact instance of the consumer, because to it, there is only one consumer. It just sends the message to the next instance in round robin.

FYI, these are all defaults, you don't have to set them
```
.WithDeliverPolicy(DeliverPolicy.All)
.WithAckPolicy(AckPolicy.Explicit)
.WithAckWait(Duration.OfSeconds(15))
.WithReplayPolicy(ReplayPolicy.Instant)
.WithMaxDeliver(-1)
.WithHeadersOnly(false)
.WithBackoff(Array.Empty<long>())
```

And yes, simplification uses pull underneath.

**Comment by jbasants** [comment]
Yes, we understand that behavior. There is no guarantee that the same consumer instance will always receive `message1`, for example. But that's not what we are trying to show. The issue here is that, in the same instant, the **same** message is sent to multiple consumer instances. We have repeated messages for the same retry.
You can see that in our image. The last message set has `message2` being received both in instances 15 and 10, at the same time.

**Comment by scottf** [comment]
So if this is the case, it's a server issue. I'll take a look at the code and pass it on to the server team, but it might be faster if you repost in the server repo. They also might have an explanation that I'm not aware of.

**Comment by jbasants** [comment]
Ok, we will repost in the server repo then and close this one. Thanks for the help.

**Comment by scottf** [comment]
@jbasants @Jarema I am able to reproduce this, but have not yet determined if it's a client issue, for instance something in the Fetch code, or a server issue. The Delivered count points to the server, but at least I can reproduce it

**Comment by scottf** [comment]
@jbasants Notes added to https://github.com/nats-io/nats-server/issues/4460
