### ISSUE TITLE
Provide out of the box encoders for popular serializers

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.net.v1#82]
A great suggestion from @dotnetchris:

"It would be really easy to provide a series of nuget packages: NATS.Client.JIL, NATS.Client.Bond, NATS.Client.Protobuf that each depend on NATS.Client and the respective serializer."

Referred in #78 

User contributions here are welcome!

**Comment by BrannonKing** [comment]
You're welcome to use my common serializer interface: https://github.com/BrannonKing/CommonSerializer . That's what I'm doing in my other project where I am synchronizing two object instances using NATS: https://github.com/BrannonKing/Kts.ObjectSync . This latter library is not quite feature complete.

**Comment by scottf** [comment]
Left to the user to implement.
