### ISSUE TITLE
IJetStreamPullSubscription Fetch Duplicate

### ISSUE THREAD

**Issue by evendou** [nats-io/nats.net.v1#836]
### Observed behavior

first i create a new jetstream.  then publish 2 messages with JsUtils.Publish(js, helper.Subject, "A", 2),  and then fetch the message with sub.Fetch(10, 3000);  the fetch result is 4 messages.

### Expected behavior

i think i should fetch 2 messages.  because i see 2 messages with nats stream view <stream-name>

### Server and client version

the client version : v1.1.0
the server version: v2.10.2

### Host environment

server: centos 7.9
client: vs2022,  win10

### Steps to reproduce

1. see the sample \src\Samples\JetStreamPullSubFetchUseCases
2. add code before first fetch (line: 77):    JsUtils.Publish(js, helper.Subject, "A", 2);
3. IList<Msg> messages = sub.Fetch(10, 3000);  while return 4 messages

**Comment by evendou** [comment]
![image](https://github.com/nats-io/nats.net/assets/6456732/b6f70f84-fcb4-4510-b9b4-61510dfcacff)

**Comment by scottf** [comment]
So the problem is the Ack Wait
```
.WithAckWait(2500)
```
is less than the Fetch timeout
```
IList<Msg> messages = sub.Fetch(10, 3000);
```
So because the entire fetch loop takes 3 seconds, and there is no chance to ack, the server redelivers the messages at 2.5 seconds like it should.
