### ISSUE TITLE
IJetStreamPullSubscription Fetch Duplicate messages

### ISSUE THREAD

**Issue by evendou** [nats-io/nats.net.v1#842]
### Observed behavior

i publish 5 message to the new stream. so the stream's message count is 5.  
but the sub.fetch result are 10 messages.

![image](https://github.com/nats-io/nats.net/assets/6456732/064e65dd-8ef3-42a4-9b3f-590c64970b5a)

### Expected behavior

i think the sub.fetch result is 5 messages.

### Server and client version

Server: 2.10.2
Client:

### Host environment

the server running in centos 7.9
the client running in win10

**Comment by evendou** [comment]
The original sample code also has bugs

![image](https://github.com/nats-io/nats.net/assets/6456732/d4489d72-6048-4da6-a533-6f2ff4216e1e)

**Comment by scottf** [comment]
I've already responded to this. When you add the publish in that exact place, and the consumer ack wait is 2500 ms and the fetch timeout is more than the ack wait, then redeliveries will happen. Please don't report this again.
