### ISSUE TITLE
Add reconnect method

### ISSUE THREAD

**Issue by scottf** [nats-io/nats.net.v1#868]
## Overview

Client should have a way that allows users to force reconnection process.
This can be useful for refreshing auth or rebalancing clients.

When triggered, client will drop connection to the current server and perform standard reconnection process.
That means that all subscriptions and consumers should be resubscribed and their work resumed after successful reconnect where all reconnect options are respected.

For most clients, that means having a `reconnect` method on the Client/Connection handle.

Connection spec has been updated in #258 

#### ADR Issue
https://github.com/nats-io/nats-architecture-and-design/issues/259

**Comment by ideahitme-github** [comment]
any update on this feature ?
