### ISSUE TITLE
Support nats streaming

### ISSUE THREAD

**Issue by sfrooster** [nats-io/nats.net.v1#90]
Add C# support for NATS streaming

**Comment by bjflanne** [comment]
Thanks @sfrooster; Good news - this is actually under active development from the team. Stay tuned..

**Comment by ColinSullivan1** [comment]
@sfrooster Thanks for the issue - I'm aiming to have the first release wrapped up soon, in a matter of a week or two.  I'd certainly like to hear some feedback when it is released!

**Comment by ColinSullivan1** [comment]
@sfrooster Here you go - please see:  https://github.com/nats-io/csharp-nats-streaming

**Comment by sfrooster** [comment]
@ColinSullivan1 Great! Tried to respond to your Apcera address, but I seem to have guessed poorly...
