### ISSUE TITLE
Requestor sample does not work

### ISSUE THREAD

**Issue by garrardkitchen** [nats-io/nats.net.v1#98]
Hi,

I'm using server 0.9.2 in Docker container on different machine (Ubuntu 14.04) to client (Windows 10).  Subscribe and Publish work as designed. However, `c.Request(subject, payload, 1000);` times out.  I modified the sample to add a timeout as the original `c.Request(subject, payload);` just hung. Url = `"nats://i-am-hiding-server-ip-address:4222"`:

```
NATS.Client.NATSTimeoutException: Timeout occurred.
   at NATS.Client.Channel`1.get(Int32 timeout) in F:\csnats-master\csnats-master\NATS\Channel.cs:line 70
   at NATS.Client.SyncSubscription.NextMessage(Int32 timeout) in F:\csnats-master\csnats-master\NATS\SyncSub.cs:line 61
   at NATS.Client.Connection.request(String subject, Byte[] data, Int32 timeout) in F:\csnats-master\csnats-master\NATS\Conn.cs:line 1901
   at NATS.Client.Connection.Request(String subject, Byte[] data, Int32 timeout) in F:\csnats-master\csnats-master\NATS\Conn.cs:line 1917
   at NATSExamples.Requestor.Run(String[] args) in F:\csnats-master\csnats-master\examples\Requestor\Requestor.cs:line 40
```

Any ideas?

Warmest regards,

Garrard.

**Comment by ColinSullivan1** [comment]
Hi Garrard,

Thank you for using NATS!

Could you try starting:
`replier -count 100 -sync`
and then running separately:
`requestor -count 100`

Thanks,
Colin

**Comment by ColinSullivan1** [comment]
Hi Garrard,

I did find an issue with the replier example in async mode, and have checked in some changes.  If you test with master branch, you should see no issues - can you let me know how it works for you?  

Thank you for bringing this up!

Colin

**Comment by garrardkitchen** [comment]
Hi Colin,

I appreciate the rapid response!

I have now tried this.  It worked.

When running without the -sync flag it throws the timeout.

Warmest regards,

Garrard.

**Comment by garrardkitchen** [comment]
Hi Colin, I will do this now.

Warmest regards,

Garrard.

**Comment by garrardkitchen** [comment]
Hi Colin, perfect!  Thank you again for your rapid resolution.

Warmest regards,

Garrard.

**Comment by ColinSullivan1** [comment]
@garrardkitchen Happy to help, and again thank you for opening the issue.   If you have any comments or questions please don't hesitate to ask.  Also, if you have't already, feel free to join our slack channel - it is very active, and I highly suggest joining.  You can find the link to request on the [NATS community page](http://nats.io/community/).
